###############################################################
# Catalog Table

catalog = [
    { "id":  1, "version": "2023-2024" }
]

################################################################
# Degrees Table

degrees = [
    { "id":  1, "name": "AA", "type": "Associate" },
    { "id":  2, "name": "BA", "type": "Bachelor's" },
    { "id":  3, "name": "BS", "type": "Bachelor's" },
    { "id":  4, "name": "BSN", "type": "Bachelor's" },
    { "id":  5, "name": "Minor", "type": "Bachelor's Minor" },
    { "id":  6, "name": "MA", "type": "Master's" },
    { "id":  7, "name": "MAT", "type": "Master's" },
    { "id":  8, "name": "MBA", "type": "Master's" },
    { "id":  9, "name": "MDE", "type": "Master's" },
    { "id": 10, "name": "MEd", "type": "Master's" },
    { "id": 11, "name": "MS", "type": "Master's" },
    { "id": 12, "name": "DBA", "type": "Doctorate" },
    { "id": 13, "name": "DM", "type": "Doctorate" },
    { "id": 14, "name": "ucert", "type": "Undergraduate Certificate" },
    { "id": 15, "name": "gcert", "type": "Graduate Certificate "}
]

################################################################
# Programs Table

programs = [
    { "id":   1, "name": "General Studies", "degree_id": 1 },
    { "id":   2, "name": "Accounting", "degree_id": 3 },
    { "id":   3, "name": "Accounting", "degree_id": 5 },
    { "id":   4, "name": "African American Studies", "degree_id": 5 },
    { "id":   5, "name": "Applied Technology", "degree_id": 3 },
    { "id":   6, "name": "Art", "degree_id": 5 },
    { "id":   7, "name": "Art History", "degree_id": 5 },
    { "id":   8, "name": "Biology", "degree_id": 5 },
    { "id":   9, "name": "Biotechnology", "degree_id": 3 },
    { "id":  10, "name": "Business Administration", "degree_id": 3 },
    { "id":  11, "name": "Business Administration", "degree_id": 5 },
    { "id":  12, "name": "Communication Studies ", "degree_id": 2 },
    { "id":  13, "name": "Communication Studies ", "degree_id": 5 },
    { "id":  14, "name": "Computer Science", "degree_id": 3 },
    { "id":  15, "name": "Computer Science", "degree_id": 5 },
    { "id":  16, "name": "Criminal Justice", "degree_id": 3 },
    { "id":  17, "name": "Criminal Justice", "degree_id": 5 },
    { "id":  18, "name": "Cybersecurity", "degree_id": 5 },
    { "id":  19, "name": "Cybersecurity Management and Policy", "degree_id": 3 },
    { "id":  20, "name": "Cybersecurity Technology", "degree_id": 3 },
    { "id":  21, "name": "Data Science", "degree_id": 3 },
    { "id":  22, "name": "Data Science", "degree_id": 5 },
    { "id":  23, "name": "Diversity Awareness", "degree_id": 5 },
    { "id":  24, "name": "East Asian Studies", "degree_id": 2 },
    { "id":  25, "name": "East Asian Studies", "degree_id": 5 },
    { "id":  26, "name": "Economics", "degree_id": 5 },
    { "id":  27, "name": "Emergency Management", "degree_id": 5 },
    { "id":  28, "name": "English", "degree_id": 2 },
    { "id":  29, "name": "English", "degree_id": 5 },
    { "id":  30, "name": "Environmental Health and Safety ", "degree_id": 3 },
    { "id":  31, "name": "Environmental Health and Safety ", "degree_id": 5 },
    { "id":  32, "name": "Finance", "degree_id": 3 },
    { "id":  33, "name": "Finance", "degree_id": 5 },
    { "id":  34, "name": "Fire Service Administration", "degree_id": 5 },
    { "id":  35, "name": "Forensics", "degree_id": 5 },
    { "id":  36, "name": "General Studies", "degree_id": 3 },
    { "id":  37, "name": "Gerontology and Aging Services", "degree_id": 3 },
    { "id":  38, "name": "Gerontology and Aging Services", "degree_id": 5 },
    { "id":  39, "name": "Graphic Communication", "degree_id": 2 },
    { "id":  40, "name": "Health Services Management ", "degree_id": 3 },
    { "id":  41, "name": "Health Services Management ", "degree_id": 5 },
    { "id":  42, "name": "History", "degree_id": 2 },
    { "id":  43, "name": "History", "degree_id": 5 },
    { "id":  44, "name": "Homeland Security", "degree_id": 3 },
    { "id":  45, "name": "Homeland Security", "degree_id": 5 },
    { "id":  46, "name": "Humanities", "degree_id": 2 },
    { "id":  47, "name": "Human Resource Management", "degree_id": 3 },
    { "id":  48, "name": "Human Resource Management", "degree_id": 5 },
    { "id":  49, "name": "Laboratory Management", "degree_id": 3 },
    { "id":  50, "name": "Law for Business", "degree_id": 5 },
    { "id":  51, "name": "Legal Studies", "degree_id": 3 },
    { "id":  52, "name": "Management Information Systems", "degree_id": 3 },
    { "id":  53, "name": "Management Information Systems", "degree_id": 5 },
    { "id":  54, "name": "Management Studies ", "degree_id": 3 },
    { "id":  55, "name": "Marketing", "degree_id": 3 },
    { "id":  56, "name": "Marketing", "degree_id": 5 },
    { "id":  57, "name": "Mathematical Sciences ", "degree_id": 5 },
    { "id":  58, "name": "Natural Science", "degree_id": 5 },
    { "id":  59, "name": "Nursing for Registered Nurses", "degree_id": 4 },
    { "id":  60, "name": "Personal Financial Planning", "degree_id": 5 },
    { "id":  61, "name": "Philosophy", "degree_id": 5 },
    { "id":  62, "name": "Political Science", "degree_id": 3 },
    { "id":  63, "name": "Political Science", "degree_id": 5 },
    { "id":  64, "name": "Psychology", "degree_id": 3 },
    { "id":  65, "name": "Psychology", "degree_id": 5 },
    { "id":  66, "name": "Public Safety Administration", "degree_id": 3 },
    { "id":  67, "name": "Public Safety Administration", "degree_id": 5 },
    { "id":  68, "name": "Small Business Management and Entrepreneurship", "degree_id": 5 },
    { "id":  69, "name": "Social Science", "degree_id": 3 },
    { "id":  70, "name": "Sociology", "degree_id": 5 },
    { "id":  71, "name": "Software Development and Security", "degree_id": 3 },
    { "id":  72, "name": "Speech Communication", "degree_id": 5 },
    { "id":  73, "name": "Terrorism and Critical Infrastructure", "degree_id": 5 },
    { "id":  74, "name": "Web and Digital Design", "degree_id": 3 },
    { "id":  75, "name": "Web and Digital Design", "degree_id": 5 },
    { "id":  76, "name": "Women, Gender, and Sexuality Studies", "degree_id": 5 },
    { "id":  77, "name": "Accounting and Financial Management", "degree_id": 11 },
    { "id":  78, "name": "Acquisition and Contract Management", "degree_id": 11 },
    { "id":  79, "name": "Biotechnology: Bioinformatics", "degree_id": 11 },
    { "id":  80, "name": "Biotechnology: Biosecurity and Biodefense", "degree_id": 11 },
    { "id":  81, "name": "Biotechnology: Biotechnology Management", "degree_id": 11 },
    { "id":  82, "name": "Biotechnology: Biotechnology Regulatory Affairs", "degree_id": 11 },
    { "id":  83, "name": "Business Administration", "degree_id": 8 },
    { "id":  84, "name": "Cloud Computing Systems", "degree_id": 11 },
    { "id":  85, "name": "CyberAccounting", "degree_id": 11 },
    { "id":  86, "name": "Cyber Operations", "degree_id": 11 },
    { "id":  87, "name": "Cybersecurity Management and Policy", "degree_id": 11 },
    { "id":  88, "name": "Cybersecurity Technology", "degree_id": 11 },
    { "id":  89, "name": "Data Analytics", "degree_id": 11 },
    { "id":  90, "name": "Digital Forensics and Cyber Investigation", "degree_id": 11 },
    { "id":  91, "name": "Distance Education and E-Learning", "degree_id": 9 },
    { "id":  92, "name": "Environmental Management", "degree_id": 11 },
    { "id":  93, "name": "Health Information Management and Technology ", "degree_id": 11 },
    { "id":  94, "name": "Information Technology: Database Systems Technology", "degree_id": 11 },
    { "id":  95, "name": "Information Technology: Homeland Security Management", "degree_id": 11 },
    { "id":  96, "name": "Information Technology: Informatics", "degree_id": 11 },
    { "id":  97, "name": "Information Technology: Information Assurance", "degree_id": 11 },
    { "id":  98, "name": "Information Technology: Project Management", "degree_id": 11 },
    { "id":  99, "name": "Information Technology: Software Engineering", "degree_id": 11 },
    { "id": 100, "name": "Information Technology: Systems Engineering", "degree_id": 11 },
    { "id": 101, "name": "Instructional Technology", "degree_id": 10 },
    { "id": 102, "name": "Learning Design and Technology ", "degree_id": 11 },
    { "id": 103, "name": "Management: Accounting", "degree_id": 11 },
    { "id": 104, "name": "Management: Criminal Justice Management", "degree_id": 11 }, 
    { "id": 105, "name": "Management: Emergency Management", "degree_id": 11 },
    { "id": 106, "name": "Management: Financial Management", "degree_id": 11 },
    { "id": 107, "name": "Management: Homeland Security Management", "degree_id": 11 },
    { "id": 108, "name": "Management: Human Resource Management", "degree_id": 11 },
    { "id": 109, "name": "Management: Information Systems and Services", "degree_id": 11 },
    { "id": 110, "name": "Management: Intelligence Management", "degree_id": 11 },
    { "id": 111, "name": "Management: Interdisciplinary Studies in Management", "degree_id": 11 },
    { "id": 112, "name": "Management: Marketing", "degree_id": 11 },
    { "id": 113, "name": "Management: Nonprofit and Association Management", "degree_id": 11 },
    { "id": 114, "name": "Management: Project Management", "degree_id": 11 },
    { "id": 115, "name": "Strategic Communications ", "degree_id": 11 },
    { "id": 116, "name": "Teaching", "degree_id": 7 },
    { "id": 117, "name": "Transformational Leadership", "degree_id": 11 },
    { "id": 118, "name": "Business Administration", "degree_id": 12 },
    { "id": 119, "name": "Management: Community College Policy and Administration", "degree_id": 13 },
    { "id": 120, "name": "Accounting Foundations", "degree_id": 14 },
    { "id": 121, "name": "Advanced Management", "degree_id": 14 },
    { "id": 122, "name": "American Government and Political Processes Applied Social Sciences", "degree_id": 14 },
    { "id": 123, "name": "Applied Social Sciences", "degree_id": 14},
    { "id": 124, "name": "Augmented and Virtual Reality Design", "degree_id": 14 },
    { "id": 125, "name": "Clinical Mental Health Care", "degree_id": 14 },
    { "id": 126, "name": "Computer Networking", "degree_id": 14 },
    { "id": 127, "name": "Cyber Threat Hunting", "degree_id": 14 },
    { "id": 128, "name": "Data Analytics", "degree_id": 14 },
    { "id": 129, "name": "Decision Support for Business", "degree_id": 14 },
    { "id": 130, "name": "Digital Design", "degree_id": 14 },
    { "id": 131, "name": "Digital Marketing", "degree_id": 14 },
    { "id": 132, "name": "Health Information Management and Data Analytics", "degree_id": 14 },
    { "id": 133, "name": "HR People Analytics", "degree_id": 14 },
    { "id": 134, "name": "Human Resource Management", "degree_id": 14 },
    { "id": 135, "name": "Leadership and Ethics", "degree_id": 14 },
    { "id": 136, "name": "Machine Learning", "degree_id": 14 },
    { "id": 137, "name": "Management", "degree_id": 14 },
    { "id": 138, "name": "Management Information Systems", "degree_id": 14 },
    { "id": 139, "name": "Project Management", "degree_id": 14 },
    { "id": 140, "name": "Public Safety Executive Leadership", "degree_id": 14 },
    { "id": 141, "name": "Spanish for Business and the Professions", "degree_id": 14 },
    { "id": 142, "name": "Vulnerability Assessment", "degree_id": 14 },
    { "id": 143, "name": "Watershed Management", "degree_id": 14 },
    { "id": 144, "name": "Web Design", "degree_id": 14 },
    { "id": 145, "name": "Women, Gender, and Sexuality Studies", "degree_id": 14 },
    { "id": 146, "name": "Accounting Information Security", "degree_id": 15 },
    { "id": 147, "name": "Acquisition and Contract Management", "degree_id": 15 },
    { "id": 148, "name": "Bioinformatics", "degree_id": 15 },
    { "id": 149, "name": "Business Analytics", "degree_id": 15 },
    { "id": 150, "name": "Cloud Computing and Networking", "degree_id": 15 },
    { "id": 151, "name": "Cyber Operations", "degree_id": 15 },
    { "id": 152, "name": "Cybersecurity Management and Policy", "degree_id": 15 },
    { "id": 153, "name": "Cybersecurity Technology", "degree_id": 15 },
    { "id": 154, "name": "Digital Forensics and Cyber Investigation", "degree_id": 15 },
    { "id": 155, "name": "Digital Health Leader", "degree_id": 15 },
    { "id": 156, "name": "Global Health Management", "degree_id": 15 },
    { "id": 157, "name": "Homeland Security Management", "degree_id": 15 },
    { "id": 158, "name": "Informatics", "degree_id": 15 },
    { "id": 159, "name": "Information Assurance", "degree_id": 15 },
    { "id": 160, "name": "Instructional Technology Integration", "degree_id": 15 },
    { "id": 161, "name": "Leadership and Management", "degree_id": 15 },
    { "id": 162, "name": "Learning Design and Technology", "degree_id": 15 },
    { "id": 163, "name": "Long-Term Care Administration", "degree_id": 15 },
    { "id": 164, "name": "Multicultural Marketing", "degree_id": 15 },
    { "id": 165, "name": "Project Management", "degree_id": 15 },
    { "id": 166, "name": "Strategic Communications", "degree_id": 15 },
    { "id": 167, "name": "Strategic Human Resource Management", "degree_id": 15 },
    { "id": 168, "name": "Systems Engineering", "degree_id": 15 }
]

