
%%{init: {
  'theme': 'base',
  'themeVariables': {
    'primaryColor': '#ff9999',
    'primaryTextColor': '#000000',
    'primaryBorderColor': '#000000',
    'lineColor': '#000000',
    'secondaryColor': '#bdf',
    'tertiaryColor': '#dfd'
  }
}}%%

graph TD
    classDef data fill:#ffd,stroke:#333,stroke-width:2px,stroke-dasharray: 5 5;
    classDef database fill:#bdf,stroke:#333,stroke-width:2px;
    classDef function fill:#f9f,stroke:#333,stroke-width:2px;
    classDef function_REFACTOR fill:#f9f,stroke:#333,stroke-width:2px,stroke-dasharray: 5 5;
    classDef template fill:##ff9999,stroke:#333,stroke-width:2px;
    classDef view fill:#dfd,stroke:#333,stroke-width:2px;
    classDef wave fill:#ffd,stroke:#333,stroke-width:2px;

    %% %% Legend
    %% subgraph Legend
    %%     Z1[Function]:::function
    %%     Z2[Database Table]:::database
    %%     Z3[View]:::view
    %% end

    %% templates
    html_minimal_template[html_minimal_template]:::template
    html_template[html_template]:::template
    javascript_draw_only[javascript_draw_only]:::template 

    %% database
    UMGC((UMGC)):::database

    %% data
    %% student_data[student_data]:::data
    student_data_schedule[student_data_schedule]:::data
    %% df_input[df_input]:::data

    %% views
    catalog_program_sequence_view[catalog_program_sequence_view]:::view
    program_requirements_view[program_requirements_view]:::view
    student_progress_d3_view[student_progress_d3_view]:::view

    %% function
    course_description_dialog[course_description_dialog]:::function
    create_html_template[create_html_template]:::function
    get_catalog_program_sequence[get_catalog_program_sequence]:::function
    get_choices[get_choices]:::function
    get_program_title[get_program_title]:::function
    get_required_program_courses[get_required_program_courses]:::function
    get_student_progress_d3[get_student_progress_d3]:::function
    menu_program[menu_program]:::function
    populate_q_student_info[populate_q_student_info]:::function
    prepare_d3_data[prepare_d3_data]:::function_REFACTOR 
    reset_program[reset_program]:::function
    reset_student_info_data[reset_student_info_data]:::function
    set_user_vars_given_role[set_user_vars_given_role]:::function

    %% wave functions
    add_ge[add_ge]:::wave
    dropdown_debug[dropdown_debug]:::wave
    home[home]:::wave
    home1[home1]:::wave
    home2[home2]:::wave
    home3[home3]:::wave
    initialize_app[initialize_app]:::wave
    initialize_client[initialize_client]:::wave
    initialize_user[initialize_user]:::wave
    login[login]:::wave
    menu_area[menu_area]:::wave
    menu_degree[menu_degree]:::wave
    next_demographic_1[next_demographic_1]:::wave
    next_demographic_2[next_demographic_2]:::wave
    on_shutdown[on_shutdown]:::wave
    on_startup[on_startup]:::wave
    program_table[program_table]:::wave
    program_wave[program_wave]:::wave
    program[program]:::wave
    register_submit[register_submit]:::wave
    select_sample_user[select_sample_user]:::wave
    student_program[student_program]:::wave
    view_program_description[view_program_description]:::wave

    %% cards
    render_career_assessment_card[render_career_assessment_card]:::card
    render_dropdown_menus_horizontal[render_dropdown_menus_horizontal]:::card
    render_program[render_program]:::card
    render_skills_assessment_card[render_skills_assessment_card]:::card
    return_demographics_card1[return_demographics_card1]:::card
    return_header_card[return_header_card]:::card
    return_login_welcome_card[return_login_welcome_card]:::card
    return_task1_card[return_task1_card]:::card
    return_tasks_card[return_tasks_card]:::card
    return_user_login_dropdown[return_user_login_dropdown]:::card
    return_welcome_back_card[return_welcome_back_card]:::card
    tasks_checked1[tasks_checked1]:::card

    %% page
    home_page{home_page}:::page
    program_page{program_page}:::page

    %% relationships
    catalog_program_sequence_view --> get_catalog_program_sequence
    course_description_dialog --> program_table
    course_description_dialog --> view_program_description
    create_html_template --> html_template
    get_choices --> menu_area
    get_program_title --> menu_program
    get_required_program_courses --> menu_program
    get_required_program_courses --> populate_q_student_info
    get_student_progress_d3 --> student_data_schedule
    html_minimal_template --> create_html_template
    javascript_draw_only -->|javascript| html_minimal_template
    populate_q_student_info --> initialize_user
    populate_q_student_info --> select_sample_user
    prepare_d3_data --> create_html_template
    program_requirements_view --> get_required_program_courses
    render_career_assessment_card --> home3
    render_program --> menu_program
    render_skills_assessment_card --> home2
    reset_program --> menu_area
    reset_program --> menu_degree
    reset_student_info_data --> initialize_user
    reset_student_info_data --> select_sample_user
    return_demographics_card1 --> home
    return_header_card --> select_sample_user
    return_login_welcome_card --> login
    return_task1_card --> home
    return_task1_card --> home1
    return_tasks_card --> home
    return_user_login_dropdown --> login
    return_welcome_back_card --> home
    set_user_vars_given_role --> select_sample_user
    student_data_schedule -->|df: schedule| prepare_d3_data
    student_program --> program
    student_progress_d3_view --> get_student_progress_d3
    tasks_checked1 --> home2
    UMGC --> catalog_program_sequence_view
    UMGC --> program_requirements_view
    UMGC --> student_progress_d3_view

