graph TD
    %% Define styles
    classDef function fill:#f9f,stroke:#333,stroke-width:2px;
    classDef database fill:#bdf,stroke:#333,stroke-width:2px;
    classDef view fill:#dfd,stroke:#333,stroke-width:2px;

    %% Functions
    
    A[populate_q_student_info]:::function
    B[populate_student_info_dict]:::function
    C[populate_student_data_dict]:::function
    D[get_program_title]:::function
    E[get_required_program_courses]:::function
    F[get_student_progress_d3]:::function
    G[get_query_dict]:::function
    H[get_query_one]:::function
    I[get_query_df]:::function
    J[reverse_engineer_dropdown_menu]:::function
    L[get_choices]:::function
    M[get_query]:::function
    N[get_catalog_program_sequence]:::function

    %% Database tables/views
    SI((student_info_view)):::view
    PV((programs)):::database
    DV((degrees)):::database
    PRV((program_requirements_view)):::view
    SPD((student_progress_d3_view)):::view
    MAV((menu_all_view)):::view
    CPS((catalog_program_sequence_view)):::view

    %% Relationships
    A --> B
    A --> C
    B --> D
    C --> E
    C --> F
    B --> G
    D --> H
    E --> I
    F --> I
    A --> J
    J --> K[get_query_one]:::function
    L --> M
    N --> I

    %% Database relationships
    B --> SI
    D --> PV
    D --> DV
    E --> PRV
    F --> SPD
    J --> MAV
    N --> CPS

    %% Legend
    subgraph Legend
        Z1[Function]:::function
        Z2((Database Table)):::database
        Z3((View)):::view
    end
