import sqlite3
# db connection created w/in utils
from utils import conn, c, drop_table, drop_view, column_exists

################################################################
# 'Program Requirement Courses' Table

drop_table('program_requirement_courses',c)
c.execute('''
    CREATE TABLE program_requirement_courses (
        id INTEGER PRIMARY KEY,
        program_id INTEGER,
        course_type_id INTEGER,
        course TEXT,
        substitutions TEXT,
        notes TEXT,
        FOREIGN KEY(program_id) REFERENCES programs(id),
        FOREIGN KEY(course_type_id) REFERENCES course_type(id)
    )
''')

###############################
# Undergraduate Major Courses #
###############################

bachelor_courses = [
    { 'program_id':  2, 'course_type_id': 1, 'course': 'ACCT 220', 'substitutions': '' },
    { 'program_id':  2, 'course_type_id': 1, 'course': 'ACCT 221', 'substitutions': '' },
    { 'program_id':  2, 'course_type_id': 1, 'course': 'ACCT 310', 'substitutions': '' },
    { 'program_id':  2, 'course_type_id': 1, 'course': 'ACCT 311', 'substitutions': '' },
    { 'program_id':  2, 'course_type_id': 1, 'course': 'ACCT 321', 'substitutions': '' },
    { 'program_id':  2, 'course_type_id': 1, 'course': 'ACCT 323', 'substitutions': '' },
    { 'program_id':  2, 'course_type_id': 1, 'course': 'ACCT 326', 'substitutions': '' },
    { 'program_id':  2, 'course_type_id': 1, 'course': 'ACCT 410', 'substitutions': 'ACCT 300+' },
    { 'program_id':  2, 'course_type_id': 1, 'course': 'ACCT 422', 'substitutions': '' },
    { 'program_id':  2, 'course_type_id': 1, 'course': 'ACCT 424', 'substitutions': '' },
    { 'program_id':  2, 'course_type_id': 1, 'course': 'ACCT 436', 'substitutions': 'ACCT 300+' },
    { 'program_id':  2, 'course_type_id': 1, 'course': 'ACCT 438', 'substitutions': 'ACCT 300+' },
    { 'program_id':  2, 'course_type_id': 6, 'course': 'ECON 201', 'substitutions': '' },
    { 'program_id':  2, 'course_type_id': 6, 'course': 'ECON 203', 'substitutions': '' },
    { 'program_id':  2, 'course_type_id': 6, 'course': 'STAT 200', 'substitutions': '' },
    { 'program_id':  2, 'course_type_id': 6, 'course': 'WRTG 293', 'substitutions': 'COMM 390 | WRTG 394' },
    { 'program_id':  2, 'course_type_id': 7, 'course': 'BMGT 364', 'substitutions': '' },
    { 'program_id':  2, 'course_type_id': 7, 'course': 'BMGT 380', 'substitutions': '' },
    { 'program_id':  2, 'course_type_id': 7, 'course': 'FINC 330', 'substitutions': '' },
    { 'program_id':  2, 'course_type_id': 7, 'course': 'MRKT 310', 'substitutions': '' },
    { 'program_id':  2, 'course_type_id': 7, 'course': 'ACCT 411', 'substitutions': 'BMGT 496' },
    { 'program_id':  5, 'course_type_id': 1, 'course': 'BMGT 110', 'substitutions': '' },
    { 'program_id':  5, 'course_type_id': 1, 'course': 'ACCT 220', 'substitutions': '' },
    { 'program_id':  5, 'course_type_id': 1, 'course': 'ACCT 221', 'substitutions': '' },
    { 'program_id':  5, 'course_type_id': 1, 'course': 'BMGT 364', 'substitutions': '' },
    { 'program_id':  5, 'course_type_id': 1, 'course': 'BMGT 365', 'substitutions': '' },
    { 'program_id':  5, 'course_type_id': 1, 'course': 'MRKT 310', 'substitutions': '' },
    { 'program_id':  5, 'course_type_id': 1, 'course': 'BMGT 380', 'substitutions': '' },
    { 'program_id':  5, 'course_type_id': 1, 'course': 'HRMN 300', 'substitutions': '' },
    { 'program_id':  5, 'course_type_id': 1, 'course': 'FINC 330', 'substitutions': '' },
    { 'program_id':  5, 'course_type_id': 1, 'course': 'BMGT 496', 'substitutions': '' },
    { 'program_id':  5, 'course_type_id': 1, 'course': 'BMGT 495', 'substitutions': '' },
    { 'program_id':  5, 'course_type_id': 6, 'course': 'ECON 201', 'substitutions': '' },
    { 'program_id':  5, 'course_type_id': 6, 'course': 'ECON 203', 'substitutions': '' },
    { 'program_id':  5, 'course_type_id': 6, 'course': 'IFSM 300', 'substitutions': '' },
    { 'program_id':  5, 'course_type_id': 6, 'course': 'STAT 200', 'substitutions': '' },
    { 'program_id':  6, 'course_type_id': 1, 'course': 'SPCH 100', 'substitutions': 'SPCH 100+' },
    { 'program_id':  6, 'course_type_id': 1, 'course': 'COMM 207', 'substitutions': 'COMM 100+' },
    { 'program_id':  6, 'course_type_id': 1, 'course': 'JOUR 201', 'substitutions': '' },
    { 'program_id':  6, 'course_type_id': 1, 'course': 'COMM 300', 'substitutions': '' },
    { 'program_id':  6, 'course_type_id': 1, 'course': 'COMM 302', 'substitutions': '' },
    { 'program_id':  6, 'course_type_id': 1, 'course': 'SPCH 324', 'substitutions': '' },
    { 'program_id':  6, 'course_type_id': 1, 'course': 'JOUR 330', 'substitutions': 'JOUR 300+' },
    { 'program_id':  6, 'course_type_id': 1, 'course': 'COMM 400', 'substitutions': 'COMM 300+' },
    { 'program_id':  6, 'course_type_id': 1, 'course': 'SPCH 470', 'substitutions': 'SPCH 300+' },
    { 'program_id':  6, 'course_type_id': 1, 'course': 'COMM 390', 'substitutions': 'COMM 300+' },
    { 'program_id':  6, 'course_type_id': 1, 'course': 'COMM 495', 'substitutions': '' },
    { 'program_id':  7, 'course_type_id': 1, 'course': 'CMSC 115', 'substitutions': '' },
    { 'program_id':  7, 'course_type_id': 1, 'course': 'CMSC 215', 'substitutions': '' },
    { 'program_id':  7, 'course_type_id': 1, 'course': 'CMSC 310', 'substitutions': '' },
    { 'program_id':  7, 'course_type_id': 1, 'course': 'CMIT 265', 'substitutions': '' },
    { 'program_id':  7, 'course_type_id': 1, 'course': 'CMSC 315', 'substitutions': '' },
    { 'program_id':  7, 'course_type_id': 1, 'course': 'CMSC 320', 'substitutions': '' },
    { 'program_id':  7, 'course_type_id': 1, 'course': 'CMSC 330', 'substitutions': '' },
    { 'program_id':  7, 'course_type_id': 1, 'course': 'CMSC 335', 'substitutions': '' },
    { 'program_id':  7, 'course_type_id': 1, 'course': 'CMSC 345', 'substitutions': '' },
    { 'program_id':  7, 'course_type_id': 1, 'course': 'CMSC 430', 'substitutions': '' },
    { 'program_id':  7, 'course_type_id': 1, 'course': 'CMSC 451', 'substitutions': '' },
    { 'program_id':  7, 'course_type_id': 1, 'course': 'CMSC 495', 'substitutions': '' },
    { 'program_id':  7, 'course_type_id': 6, 'course': 'MATH 140', 'substitutions': '' },
    { 'program_id':  7, 'course_type_id': 6, 'course': 'CMSC 105', 'substitutions': '' },
    { 'program_id':  7, 'course_type_id': 7, 'course': 'MATH 141', 'substitutions': '' },
    { 'program_id':  7, 'course_type_id': 7, 'course': 'CMSC 150', 'substitutions': '' },
    { 'program_id':  8, 'course_type_id': 1, 'course': 'CCJS 100', 'substitutions': '' },
    { 'program_id':  8, 'course_type_id': 1, 'course': 'CCJS 230', 'substitutions': '' },
    { 'program_id':  8, 'course_type_id': 1, 'course': 'CCJS 340', 'substitutions': '' },
    { 'program_id':  8, 'course_type_id': 1, 'course': 'CCJS 345', 'substitutions': '' },
    { 'program_id':  8, 'course_type_id': 1, 'course': 'CCJS 350', 'substitutions': '' },
    { 'program_id':  8, 'course_type_id': 1, 'course': 'CCJS 360', 'substitutions': '' },
    { 'program_id':  8, 'course_type_id': 1, 'course': 'CCJS 380', 'substitutions': '' },
    { 'program_id':  8, 'course_type_id': 1, 'course': 'CCJS 341', 'substitutions': '' },
    { 'program_id':  8, 'course_type_id': 1, 'course': 'CCJS 352', 'substitutions': '' },
    { 'program_id':  8, 'course_type_id': 1, 'course': 'CCJS 497', 'substitutions': '' },
    { 'program_id':  8, 'course_type_id': 1, 'course': 'CCJS 495', 'substitutions': '' },
    { 'program_id':  9, 'course_type_id': 1, 'course': 'CSIA 300', 'substitutions': '' },
    { 'program_id':  9, 'course_type_id': 1, 'course': 'IFSM 304', 'substitutions': '' },
    { 'program_id':  9, 'course_type_id': 1, 'course': 'CMIT 265', 'substitutions': '' },
    { 'program_id':  9, 'course_type_id': 1, 'course': 'CMIT 320', 'substitutions': '' },
    { 'program_id':  9, 'course_type_id': 1, 'course': 'CSIA 310', 'substitutions': '' },
    { 'program_id':  9, 'course_type_id': 1, 'course': 'CSIA 350', 'substitutions': '' },
    { 'program_id':  9, 'course_type_id': 1, 'course': 'CSIA 360', 'substitutions': '' },
    { 'program_id':  9, 'course_type_id': 1, 'course': 'CSIA 413', 'substitutions': '' },
    { 'program_id':  9, 'course_type_id': 1, 'course': 'CSIA 459', 'substitutions': '' },
    { 'program_id':  9, 'course_type_id': 1, 'course': 'CMIT 425', 'substitutions': '' },
    { 'program_id':  9, 'course_type_id': 1, 'course': 'CSIA 485', 'substitutions': '' },
    { 'program_id': 11, 'course_type_id': 1, 'course': 'STAT 200', 'substitutions': '' },
    { 'program_id': 11, 'course_type_id': 1, 'course': 'DATA 230', 'substitutions': '' },
    { 'program_id': 11, 'course_type_id': 1, 'course': 'DATA 300', 'substitutions': '' },
    { 'program_id': 11, 'course_type_id': 1, 'course': 'CSIA 300', 'substitutions': '' },
    { 'program_id': 11, 'course_type_id': 1, 'course': 'DATA 320', 'substitutions': '' },
    { 'program_id': 11, 'course_type_id': 1, 'course': 'IFSM 330', 'substitutions': '' },
    { 'program_id': 11, 'course_type_id': 1, 'course': 'DATA 335', 'substitutions': '' },
    { 'program_id': 11, 'course_type_id': 1, 'course': 'DATA 430', 'substitutions': '' },
    { 'program_id': 11, 'course_type_id': 1, 'course': 'DATA 440', 'substitutions': '' },
    { 'program_id': 11, 'course_type_id': 1, 'course': 'DATA 445', 'substitutions': '' },
    { 'program_id': 11, 'course_type_id': 1, 'course': 'DATA 450', 'substitutions': '' },
    { 'program_id': 11, 'course_type_id': 1, 'course': 'DATA 460', 'substitutions': '' },
    { 'program_id': 11, 'course_type_id': 1, 'course': 'DATA 495', 'substitutions': '' },
    { 'program_id': 11, 'course_type_id': 6, 'course': 'DATA 200', 'substitutions': '' },
    { 'program_id': 11, 'course_type_id': 6, 'course': 'MATH 115', 'substitutions': '' },
    { 'program_id': 14, 'course_type_id': 1, 'course': 'ENHS 300', 'substitutions': '' },
    { 'program_id': 14, 'course_type_id': 1, 'course': 'ENHS 305', 'substitutions': '' },
    { 'program_id': 14, 'course_type_id': 1, 'course': 'ENHS 310', 'substitutions': '' },
    { 'program_id': 14, 'course_type_id': 1, 'course': 'ENHS 315', 'substitutions': '' },
    { 'program_id': 14, 'course_type_id': 1, 'course': 'ENHS 320', 'substitutions': '' },
    { 'program_id': 14, 'course_type_id': 1, 'course': 'ENHS 325', 'substitutions': '' },
    { 'program_id': 14, 'course_type_id': 1, 'course': 'ENHS 330', 'substitutions': '' },
    { 'program_id': 14, 'course_type_id': 1, 'course': 'ENHS 335', 'substitutions': '' },
    { 'program_id': 14, 'course_type_id': 1, 'course': 'ENHS 340', 'substitutions': '' },
    { 'program_id': 14, 'course_type_id': 1, 'course': 'ENHS 400', 'substitutions': '' },
    { 'program_id': 14, 'course_type_id': 1, 'course': 'ENHS 405', 'substitutions': '' },
    { 'program_id': 14, 'course_type_id': 1, 'course': 'ENHS 495', 'substitutions': '' },
    { 'program_id': 14, 'course_type_id': 6, 'course': 'CHEM 297', 'substitutions': '' },
    { 'program_id': 14, 'course_type_id': 6, 'course': 'MATH 115', 'substitutions': '' },
    { 'program_id': 15, 'course_type_id': 1, 'course': 'BMGT 364', 'substitutions': '' },
    { 'program_id': 15, 'course_type_id': 1, 'course': 'ACCT 220', 'substitutions': '' },
    { 'program_id': 15, 'course_type_id': 1, 'course': 'ACCT 221', 'substitutions': '' },
    { 'program_id': 15, 'course_type_id': 1, 'course': 'FINC 330', 'substitutions': '' },
    { 'program_id': 15, 'course_type_id': 1, 'course': 'FINC 335', 'substitutions': '' },
    { 'program_id': 15, 'course_type_id': 1, 'course': 'FINC 340', 'substitutions': '' },
    { 'program_id': 15, 'course_type_id': 1, 'course': 'FINC 351', 'substitutions': '' },
    { 'program_id': 15, 'course_type_id': 1, 'course': 'FINC 421', 'substitutions': '' },
    { 'program_id': 15, 'course_type_id': 1, 'course': 'FINC 430', 'substitutions': '' },
    { 'program_id': 15, 'course_type_id': 1, 'course': 'FINC 440', 'substitutions': '' },
    { 'program_id': 15, 'course_type_id': 1, 'course': 'FINC 460', 'substitutions': '' },
    { 'program_id': 15, 'course_type_id': 1, 'course': 'ECON 430', 'substitutions': '' },
    { 'program_id': 15, 'course_type_id': 1, 'course': 'FINC 495', 'substitutions': '' },
    { 'program_id': 15, 'course_type_id': 6, 'course': 'ECON 201', 'substitutions': '' },
    { 'program_id': 15, 'course_type_id': 6, 'course': 'ECON 203', 'substitutions': '' },
    { 'program_id': 15, 'course_type_id': 6, 'course': 'STAT 200', 'substitutions': '' },
    { 'program_id': 17, 'course_type_id': 1, 'course': 'GERO 100', 'substitutions': '' },
    { 'program_id': 17, 'course_type_id': 1, 'course': 'GERO 301', 'substitutions': '' },
    { 'program_id': 17, 'course_type_id': 1, 'course': 'GERO 302', 'substitutions': '' },
    { 'program_id': 17, 'course_type_id': 1, 'course': 'GERO 306', 'substitutions': '' },
    { 'program_id': 17, 'course_type_id': 1, 'course': 'GERO 311', 'substitutions': '' },
    { 'program_id': 17, 'course_type_id': 1, 'course': 'GERO 320', 'substitutions': '' },
    { 'program_id': 17, 'course_type_id': 1, 'course': 'GERO 338', 'substitutions': '' },
    { 'program_id': 17, 'course_type_id': 1, 'course': 'GERO 342', 'substitutions': '' },
    { 'program_id': 17, 'course_type_id': 1, 'course': 'GERO 390', 'substitutions': '' },
    { 'program_id': 17, 'course_type_id': 1, 'course': 'GERO 427', 'substitutions': '' },
    { 'program_id': 17, 'course_type_id': 1, 'course': 'GERO 486A', 'substitutions': '' },
    { 'program_id': 17, 'course_type_id': 6, 'course': 'STAT 200', 'substitutions': '' },
    { 'program_id': 18, 'course_type_id': 1, 'course': 'GRCO 100', 'substitutions': '' },
    { 'program_id': 18, 'course_type_id': 1, 'course': 'ARTT 110', 'substitutions': '' },
    { 'program_id': 18, 'course_type_id': 1, 'course': 'ARTT 120', 'substitutions': '' },
    { 'program_id': 18, 'course_type_id': 1, 'course': 'ARTT 210', 'substitutions': '' },
    { 'program_id': 18, 'course_type_id': 1, 'course': 'GRCO 230', 'substitutions': '' },
    { 'program_id': 18, 'course_type_id': 1, 'course': 'GRCO 350', 'substitutions': '' },
    { 'program_id': 18, 'course_type_id': 1, 'course': 'GRCO 354', 'substitutions': '' },
    { 'program_id': 18, 'course_type_id': 1, 'course': 'GRCO 355', 'substitutions': '' },
    { 'program_id': 18, 'course_type_id': 1, 'course': 'GRCO 450', 'substitutions': '' },
    { 'program_id': 18, 'course_type_id': 1, 'course': 'GRCO 479', 'substitutions': '' },
    { 'program_id': 18, 'course_type_id': 1, 'course': 'GRCO 495', 'substitutions': '' },
    { 'program_id': 19, 'course_type_id': 1, 'course': 'HMGT 300', 'substitutions': '' },
    { 'program_id': 19, 'course_type_id': 1, 'course': 'HMGT 307', 'substitutions': '' },
    { 'program_id': 19, 'course_type_id': 1, 'course': 'HMGT 310', 'substitutions': '' },
    { 'program_id': 19, 'course_type_id': 1, 'course': 'HMGT 320', 'substitutions': '' },
    { 'program_id': 19, 'course_type_id': 1, 'course': 'HMGT 322', 'substitutions': '' },
    { 'program_id': 19, 'course_type_id': 1, 'course': 'HMGT 335', 'substitutions': '' },
    { 'program_id': 19, 'course_type_id': 1, 'course': 'HMGT 372', 'substitutions': '' },
    { 'program_id': 19, 'course_type_id': 1, 'course': 'HMGT 400', 'substitutions': '' },
    { 'program_id': 19, 'course_type_id': 1, 'course': 'HMGT 420', 'substitutions': '' },
    { 'program_id': 19, 'course_type_id': 1, 'course': 'HMGT 435', 'substitutions': '' },
    { 'program_id': 19, 'course_type_id': 1, 'course': 'HMGT 495', 'substitutions': '' },
    { 'program_id': 19, 'course_type_id': 6, 'course': 'IFSM 305', 'substitutions': '' },
    { 'program_id': 19, 'course_type_id': 6, 'course': 'STAT 200', 'substitutions': '' },
    { 'program_id': 21, 'course_type_id': 1, 'course': 'HMLS 302', 'substitutions': '' },
    { 'program_id': 21, 'course_type_id': 1, 'course': 'HMLS 310', 'substitutions': '' },
    { 'program_id': 21, 'course_type_id': 1, 'course': 'HMLS 406', 'substitutions': '' },
    { 'program_id': 21, 'course_type_id': 1, 'course': 'HMLS 408', 'substitutions': '' },
    { 'program_id': 21, 'course_type_id': 1, 'course': 'HMLS 414', 'substitutions': '' },
    { 'program_id': 21, 'course_type_id': 1, 'course': 'HMLS 416', 'substitutions': '' },
    { 'program_id': 21, 'course_type_id': 1, 'course': 'PSAD 410', 'substitutions': '' },
    { 'program_id': 21, 'course_type_id': 1, 'course': 'PSAD 414', 'substitutions': '' },
    { 'program_id': 21, 'course_type_id': 1, 'course': 'PSAD 416', 'substitutions': '' },
    { 'program_id': 21, 'course_type_id': 1, 'course': 'HMLS 304', 'substitutions': '' },
    { 'program_id': 21, 'course_type_id': 1, 'course': 'HMLS 495', 'substitutions': '' },
    { 'program_id': 21, 'course_type_id': 6, 'course': 'IFSM 300', 'substitutions': '' },
    { 'program_id': 22, 'course_type_id': 1, 'course': 'HRMN 300', 'substitutions': '' },
    { 'program_id': 22, 'course_type_id': 1, 'course': 'HRMN 302', 'substitutions': '' },
    { 'program_id': 22, 'course_type_id': 1, 'course': 'HRMN 362', 'substitutions': '' },
    { 'program_id': 22, 'course_type_id': 1, 'course': 'HRMN 367', 'substitutions': '' },
    { 'program_id': 22, 'course_type_id': 1, 'course': 'HRMN 395', 'substitutions': '' },
    { 'program_id': 22, 'course_type_id': 1, 'course': 'HRMN 400', 'substitutions': '' },
    { 'program_id': 22, 'course_type_id': 1, 'course': 'HRMN 406', 'substitutions': 'HRMN 410' },
    { 'program_id': 22, 'course_type_id': 1, 'course': 'BMGT 364', 'substitutions': '' },
    { 'program_id': 22, 'course_type_id': 1, 'course': 'FINC 331', 'substitutions': '' },
    { 'program_id': 22, 'course_type_id': 1, 'course': 'HRMN 408', 'substitutions': '' },
    { 'program_id': 22, 'course_type_id': 1, 'course': 'HRMN 467', 'substitutions': '' },
    { 'program_id': 22, 'course_type_id': 1, 'course': 'HRMN 495', 'substitutions': '' },
    { 'program_id': 22, 'course_type_id': 6, 'course': 'IFSM 300', 'substitutions': '' },
    { 'program_id': 23, 'course_type_id': 1, 'course': 'HUMN 100', 'substitutions': '' },
    { 'program_id': 23, 'course_type_id': 1, 'course': 'PHIL 100', 'substitutions': '' },
    { 'program_id': 23, 'course_type_id': 1, 'course': 'PHIL 140', 'substitutions': '' },
    { 'program_id': 23, 'course_type_id': 1, 'course': 'HIST 115', 'substitutions': 'HIST 116 | HIST 141 | HIST 142' },
    { 'program_id': 23, 'course_type_id': 1, 'course': 'MUSC 210', 'substitutions': 'MUSC 100+' },
    { 'program_id': 23, 'course_type_id': 1, 'course': 'ARTH 372', 'substitutions': 'ARTH 300+' },
    { 'program_id': 23, 'course_type_id': 1, 'course': 'PHIL 304', 'substitutions': 'PHIL 300+' },
    { 'program_id': 23, 'course_type_id': 1, 'course': 'HUMN 351', 'substitutions': 'HUMN 300+' },
    { 'program_id': 23, 'course_type_id': 1, 'course': 'PHIL 349', 'substitutions': 'PHIL 300+' },
    { 'program_id': 23, 'course_type_id': 1, 'course': 'ENGL 406', 'substitutions': 'ENGL 300+' },
    { 'program_id': 23, 'course_type_id': 1, 'course': 'HUMN 495', 'substitutions': '' },
    { 'program_id': 25, 'course_type_id': 1, 'course': 'LGST 101', 'substitutions': '' },
    { 'program_id': 25, 'course_type_id': 1, 'course': 'LGST 200', 'substitutions': '' },
    { 'program_id': 25, 'course_type_id': 1, 'course': 'LGST 201', 'substitutions': '' },
    { 'program_id': 25, 'course_type_id': 1, 'course': 'LGST 204', 'substitutions': '' },
    { 'program_id': 25, 'course_type_id': 1, 'course': 'LGST 301', 'substitutions': '' },
    { 'program_id': 25, 'course_type_id': 1, 'course': 'LGST 312', 'substitutions': '' },
    { 'program_id': 25, 'course_type_id': 1, 'course': 'LGST 315', 'substitutions': '' },
    { 'program_id': 25, 'course_type_id': 1, 'course': 'LGST 320', 'substitutions': '' },
    { 'program_id': 25, 'course_type_id': 1, 'course': 'LGST 325', 'substitutions': '' },
    { 'program_id': 25, 'course_type_id': 1, 'course': 'LGST 340', 'substitutions': '' },
    { 'program_id': 25, 'course_type_id': 1, 'course': 'LGST 495', 'substitutions': '' },
    { 'program_id': 26, 'course_type_id': 1, 'course': 'IFSM 300', 'substitutions': '' }, 
    { 'program_id': 26, 'course_type_id': 1, 'course': 'IFSM 301', 'substitutions': '' }, 
    { 'program_id': 26, 'course_type_id': 1, 'course': 'IFSM 304', 'substitutions': '' }, 
    { 'program_id': 26, 'course_type_id': 1, 'course': 'CSIA 300', 'substitutions': '' }, 
    { 'program_id': 26, 'course_type_id': 1, 'course': 'IFSM 310', 'substitutions': '' }, 
    { 'program_id': 26, 'course_type_id': 1, 'course': 'IFSM 311', 'substitutions': '' }, 
    { 'program_id': 26, 'course_type_id': 1, 'course': 'IFSM 330', 'substitutions': '' }, 
    { 'program_id': 26, 'course_type_id': 1, 'course': 'IFSM 370', 'substitutions': '' }, 
    { 'program_id': 26, 'course_type_id': 1, 'course': 'IFSM 438', 'substitutions': '' }, 
    { 'program_id': 26, 'course_type_id': 1, 'course': 'IFSM 461', 'substitutions': '' }, 
    { 'program_id': 26, 'course_type_id': 1, 'course': 'IFSM 495', 'substitutions': '' }, 
    { 'program_id': 26, 'course_type_id': 6, 'course': 'CMSC 105', 'substitutions': '' }, 
    { 'program_id': 27, 'course_type_id': 1, 'course': 'BMGT 160', 'substitutions': '' },
    { 'program_id': 27, 'course_type_id': 1, 'course': 'ACCT 301', 'substitutions': 'ACCT 220' },
    { 'program_id': 27, 'course_type_id': 1, 'course': 'BMGT 364', 'substitutions': '' },
    { 'program_id': 27, 'course_type_id': 1, 'course': 'BMGT 365', 'substitutions': 'ACCT 300+ | BMGT 300+ | FINC 300+ | HRMN 300+ | MRKT 300+' },
    { 'program_id': 27, 'course_type_id': 1, 'course': 'BMGT 464', 'substitutions': 'BMGT 465' },
    { 'program_id': 27, 'course_type_id': 1, 'course': 'BMGT 317', 'substitutions': '' },
    { 'program_id': 27, 'course_type_id': 1, 'course': 'BMGT 305', 'substitutions': '' },
    { 'program_id': 27, 'course_type_id': 1, 'course': 'BMGT 304', 'substitutions': 'ACCT 300+ | BMGT 300+ | FINC 300+ | HRMN 300+ | MRKT 300+' },
    { 'program_id': 27, 'course_type_id': 1, 'course': 'BMGT 484', 'substitutions': '' },
    { 'program_id': 27, 'course_type_id': 1, 'course': 'BMGT 496', 'substitutions': '' },
    { 'program_id': 27, 'course_type_id': 1, 'course': 'BMGT 485', 'substitutions': '' },
    { 'program_id': 27, 'course_type_id': 6, 'course': 'ECON 201', 'substitutions': '' },
    { 'program_id': 27, 'course_type_id': 6, 'course': 'IFSM 300', 'substitutions': '' },
    { 'program_id': 27, 'course_type_id': 6, 'course': 'STAT 200', 'substitutions': '' },
    { 'program_id': 28, 'course_type_id': 1, 'course': 'BMGT 110', 'substitutions': '' },
    { 'program_id': 28, 'course_type_id': 1, 'course': 'BMGT 330', 'substitutions': '' },
    { 'program_id': 28, 'course_type_id': 1, 'course': 'MRKT 310', 'substitutions': '' },
    { 'program_id': 28, 'course_type_id': 1, 'course': 'MRKT 354', 'substitutions': '' },
    { 'program_id': 28, 'course_type_id': 1, 'course': 'MRKT 394', 'substitutions': '' },
    { 'program_id': 28, 'course_type_id': 1, 'course': 'MRKT 410', 'substitutions': '' },
    { 'program_id': 28, 'course_type_id': 1, 'course': 'MRKT 412', 'substitutions': '' },
    { 'program_id': 28, 'course_type_id': 1, 'course': 'MRKT 458', 'substitutions': '' },
    { 'program_id': 28, 'course_type_id': 1, 'course': 'MRKT 311', 'substitutions': '' },
    { 'program_id': 28, 'course_type_id': 1, 'course': 'MRKT 314', 'substitutions': '' },
    { 'program_id': 28, 'course_type_id': 1, 'course': 'MRKT 454', 'substitutions': '' },
    { 'program_id': 28, 'course_type_id': 1, 'course': 'MRKT 495', 'substitutions': '' },
    { 'program_id': 30, 'course_type_id': 1, 'course': 'GVPT 100', 'substitutions': '' },
    { 'program_id': 30, 'course_type_id': 1, 'course': 'GVPT 101', 'substitutions': '' },
    { 'program_id': 30, 'course_type_id': 1, 'course': 'GVPT 170', 'substitutions': 'GVPT 200' },
    { 'program_id': 30, 'course_type_id': 1, 'course': 'GVPT 210', 'substitutions': '' },
    { 'program_id': 30, 'course_type_id': 1, 'course': 'GVPT 280', 'substitutions': '' },
    { 'program_id': 30, 'course_type_id': 1, 'course': 'GVPT 306', 'substitutions': '' },
    { 'program_id': 30, 'course_type_id': 1, 'course': 'GVPT 403', 'substitutions': 'GVPT 300+' },
    { 'program_id': 30, 'course_type_id': 1, 'course': 'GVPT 406', 'substitutions': '' },
    { 'program_id': 30, 'course_type_id': 1, 'course': 'GVPT 457', 'substitutions': 'GVPT 300+' },
    { 'program_id': 30, 'course_type_id': 1, 'course': 'GVPT 495', 'substitutions': '' },
    { 'program_id': 31, 'course_type_id': 1, 'course': 'PSYC 100', 'substitutions': '' }, 
    { 'program_id': 31, 'course_type_id': 1, 'course': 'PSYC 220', 'substitutions': '' }, 
    { 'program_id': 31, 'course_type_id': 1, 'course': 'PSYC 251', 'substitutions': '' }, 
    { 'program_id': 31, 'course_type_id': 1, 'course': 'PSYC 300', 'substitutions': '' }, 
    { 'program_id': 31, 'course_type_id': 1, 'course': 'PSYC 301', 'substitutions': '' }, 
    { 'program_id': 31, 'course_type_id': 1, 'course': 'PSYC 310', 'substitutions': '' }, 
    { 'program_id': 31, 'course_type_id': 1, 'course': 'PSYC 335', 'substitutions': '' }, 
    { 'program_id': 31, 'course_type_id': 1, 'course': 'PSYC 341', 'substitutions': '' }, 
    { 'program_id': 31, 'course_type_id': 1, 'course': 'PSYC 353', 'substitutions': '' }, 
    { 'program_id': 31, 'course_type_id': 1, 'course': 'PSYC 436', 'substitutions': '' }, 
    { 'program_id': 31, 'course_type_id': 1, 'course': 'PSYC 495', 'substitutions': '' }, 
    { 'program_id': 31, 'course_type_id': 6, 'course': 'STAT 200', 'substitutions': '' },
    { 'program_id': 32, 'course_type_id': 1, 'course': 'PSAD 302', 'substitutions': '' }, 
    { 'program_id': 32, 'course_type_id': 1, 'course': 'PSAD 304', 'substitutions': '' }, 
    { 'program_id': 32, 'course_type_id': 1, 'course': 'PSAD 306', 'substitutions': '' }, 
    { 'program_id': 32, 'course_type_id': 1, 'course': 'PSAD 408', 'substitutions': '' }, 
    { 'program_id': 32, 'course_type_id': 1, 'course': 'PSAD 410', 'substitutions': '' }, 
    { 'program_id': 32, 'course_type_id': 1, 'course': 'PSAD 414', 'substitutions': '' }, 
    { 'program_id': 32, 'course_type_id': 1, 'course': 'PSAD 416', 'substitutions': '' }, 
    { 'program_id': 32, 'course_type_id': 1, 'course': 'FINC 331', 'substitutions': '' }, 
    { 'program_id': 32, 'course_type_id': 1, 'course': 'BMGT 317', 'substitutions': '' }, 
    { 'program_id': 32, 'course_type_id': 1, 'course': 'PSAD 495', 'substitutions': '' }, 
    { 'program_id': 32, 'course_type_id': 6, 'course': 'IFSM 300', 'substitutions': '' },
    { 'program_id': 34, 'course_type_id': 1, 'course': 'CMSC 115', 'substitutions': '' },
    { 'program_id': 34, 'course_type_id': 1, 'course': 'CMSC 215', 'substitutions': '' },
    { 'program_id': 34, 'course_type_id': 1, 'course': 'CMSC 320', 'substitutions': '' },
    { 'program_id': 34, 'course_type_id': 1, 'course': 'SDEV 300', 'substitutions': '' },
    { 'program_id': 34, 'course_type_id': 1, 'course': 'SDEV 325', 'substitutions': '' },
    { 'program_id': 34, 'course_type_id': 1, 'course': 'SDEV 350', 'substitutions': '' },
    { 'program_id': 34, 'course_type_id': 1, 'course': 'SDEV 360', 'substitutions': '' },
    { 'program_id': 34, 'course_type_id': 1, 'course': 'SDEV 400', 'substitutions': '' },
    { 'program_id': 34, 'course_type_id': 1, 'course': 'SDEV 425', 'substitutions': '' },
    { 'program_id': 34, 'course_type_id': 1, 'course': 'SDEV 460', 'substitutions': '' },
    { 'program_id': 34, 'course_type_id': 1, 'course': 'CMSC 495', 'substitutions': '' }
]

c.executemany('''
    INSERT INTO program_requirement_courses (program_id, course_type_id, course, substitutions) 
       VALUES (:program_id, :course_type_id, :course, :substitutions)
''', bachelor_courses)
conn.commit()

#######################################
# Undergraduate Certification Courses #
#######################################

undergrad_certification_courses = [
    { 'program_id': 121, 'course_type_id': 2, 'course': 'ACCT 220',  'notes': '' },
    { 'program_id': 121, 'course_type_id': 2, 'course': 'ACCT 221',  'notes': '' },
    { 'program_id': 121, 'course_type_id': 4, 'course': 'ACCT 100+', 'notes': 'choose 4' },
    { 'program_id': 121, 'course_type_id': 4, 'course': 'FINC 100+', 'notes': 'choose 4' },
    { 'program_id': 121, 'course_type_id': 4, 'course': 'BMGT 110',  'notes': 'choose 4' },
    { 'program_id': 121, 'course_type_id': 4, 'course': 'CMSC 105',  'notes': 'choose 4' },
    { 'program_id': 121, 'course_type_id': 4, 'course': 'DATA 200',  'notes': 'choose 4' },
    { 'program_id': 121, 'course_type_id': 4, 'course': 'ECON 201',  'notes': 'choose 4' },
    { 'program_id': 121, 'course_type_id': 4, 'course': 'ECON 203',  'notes': 'choose 4' },
    { 'program_id': 121, 'course_type_id': 4, 'course': 'IFSM 201',  'notes': 'choose 4' },
    { 'program_id': 121, 'course_type_id': 4, 'course': 'STAT 200',  'notes': 'choose 4' },
    { 'program_id': 121, 'course_type_id': 4, 'course': 'WRTG 112',  'notes': 'choose 4' },
    { 'program_id': 122, 'course_type_id': 2, 'course': 'BMGT 160',  'notes': '' },
    { 'program_id': 122, 'course_type_id': 2, 'course': 'BMGT 364',  'notes': '' },
    { 'program_id': 122, 'course_type_id': 2, 'course': 'BMGT 484',  'notes': '' },
    { 'program_id': 122, 'course_type_id': 2, 'course': 'BMGT 317',  'notes': '' },
    { 'program_id': 122, 'course_type_id': 4, 'course': 'ACCT 301',  'notes': 'choose 2' },
    { 'program_id': 122, 'course_type_id': 4, 'course': 'BMGT 305',  'notes': 'choose 2' },
    { 'program_id': 122, 'course_type_id': 4, 'course': 'BMGT 335',  'notes': 'choose 2' },
    { 'program_id': 122, 'course_type_id': 4, 'course': 'BMGT 365',  'notes': 'choose 2' },
    { 'program_id': 122, 'course_type_id': 4, 'course': 'BMGT 380',  'notes': 'choose 2' },
    { 'program_id': 122, 'course_type_id': 4, 'course': 'BMGT 464',  'notes': 'choose 2' },
    { 'program_id': 122, 'course_type_id': 4, 'course': 'BMGT 465',  'notes': 'choose 2' },
    { 'program_id': 122, 'course_type_id': 4, 'course': 'BMGT 496',  'notes': 'choose 2' },
    { 'program_id': 122, 'course_type_id': 4, 'course': 'DATA 200',  'notes': 'choose 2' },
    { 'program_id': 122, 'course_type_id': 4, 'course': 'FINC 330',  'notes': 'choose 2' },
    { 'program_id': 122, 'course_type_id': 4, 'course': 'FINC 331',  'notes': 'choose 2' },
    { 'program_id': 122, 'course_type_id': 4, 'course': 'HRMN 300',  'notes': 'choose 2' },
    { 'program_id': 122, 'course_type_id': 4, 'course': 'HRMN 302',  'notes': 'choose 2' },
    { 'program_id': 122, 'course_type_id': 4, 'course': 'HRMN 367',  'notes': 'choose 2' },
    { 'program_id': 122, 'course_type_id': 4, 'course': 'IFSM 300',  'notes': 'choose 2' },
    { 'program_id': 122, 'course_type_id': 4, 'course': 'MRKT 310',  'notes': 'choose 2' },
    { 'program_id': 123, 'course_type_id': 2, 'course': 'GVPT 170',  'notes': '' },
    { 'program_id': 123, 'course_type_id': 2, 'course': 'GVPT 280',  'notes': '' },
    { 'program_id': 123, 'course_type_id': 2, 'course': 'GVPT 306',  'notes': '' },
    { 'program_id': 123, 'course_type_id': 2, 'course': 'GVPT 444',  'notes': '' },
    { 'program_id': 123, 'course_type_id': 2, 'course': 'GVPT 457',  'notes': '' },
    { 'program_id': 123, 'course_type_id': 2, 'course': 'GVPT 475',  'notes': '' },
    { 'program_id': 124, 'course_type_id': 2, 'course': 'PSYC 100',  'notes': '' },
    { 'program_id': 124, 'course_type_id': 2, 'course': 'SOCY 100',  'notes': '' },
    { 'program_id': 124, 'course_type_id': 4, 'course': 'ANTH 350',  'notes': 'choose 4' },
    { 'program_id': 124, 'course_type_id': 4, 'course': 'ANTH 351',  'notes': 'choose 4' },
    { 'program_id': 124, 'course_type_id': 4, 'course': 'GERO 427',  'notes': 'choose 4' },
    { 'program_id': 124, 'course_type_id': 4, 'course': 'PSYC 354',  'notes': 'choose 4' },
    { 'program_id': 124, 'course_type_id': 4, 'course': 'PSYC 386',  'notes': 'choose 4' },
    { 'program_id': 124, 'course_type_id': 4, 'course': 'SOCY 350',  'notes': 'choose 4' },
    { 'program_id': 125, 'course_type_id': 2, 'course': 'CMST 290',  'notes': '' },
    { 'program_id': 125, 'course_type_id': 2, 'course': 'CMST 295',  'notes': '' },
    { 'program_id': 125, 'course_type_id': 2, 'course': 'CMST 308',  'notes': '' },
    { 'program_id': 125, 'course_type_id': 2, 'course': 'CMST 315',  'notes': '' },
    { 'program_id': 125, 'course_type_id': 2, 'course': 'CMST 330',  'notes': '' },
    { 'program_id': 125, 'course_type_id': 2, 'course': 'CMST 331',  'notes': '' },
    { 'program_id': 126, 'course_type_id': 2, 'course': 'PSYC 100',  'notes': '' },
    { 'program_id': 126, 'course_type_id': 2, 'course': 'PSYC 300',  'notes': '' },
    { 'program_id': 126, 'course_type_id': 2, 'course': 'PSYC 301',  'notes': '' },
    { 'program_id': 126, 'course_type_id': 2, 'course': 'PSYC 335',  'notes': '' },
    { 'program_id': 126, 'course_type_id': 2, 'course': 'PSYC 353',  'notes': '' },
    { 'program_id': 126, 'course_type_id': 2, 'course': 'PSYC 436',  'notes': '' },
    { 'program_id': 127, 'course_type_id': 2, 'course': 'CMIT 202',  'notes': '' },
    { 'program_id': 127, 'course_type_id': 2, 'course': 'CMIT 265',  'notes': '' },
    { 'program_id': 127, 'course_type_id': 2, 'course': 'CMIT 320',  'notes': '' },
    { 'program_id': 127, 'course_type_id': 2, 'course': 'CMIT 326',  'notes': '' },
    { 'program_id': 127, 'course_type_id': 2, 'course': 'CMIT 351',  'notes': '' },
    { 'program_id': 127, 'course_type_id': 4, 'course': 'CMIT 300+', 'notes': 'choose 1' },
    { 'program_id': 128, 'course_type_id': 2, 'course': 'CMIT 202',  'notes': '' },
    { 'program_id': 128, 'course_type_id': 2, 'course': 'CMIT 265',  'notes': '' },
    { 'program_id': 128, 'course_type_id': 2, 'course': 'CMIT 320',  'notes': '' },
    { 'program_id': 128, 'course_type_id': 2, 'course': 'CMIT 321',  'notes': '' },
    { 'program_id': 128, 'course_type_id': 2, 'course': 'CMIT 386',  'notes': '' },
    { 'program_id': 128, 'course_type_id': 2, 'course': 'CMIT 421',  'notes': '' },
    { 'program_id': 129, 'course_type_id': 2, 'course': 'STAT 200',  'notes': '' },
    { 'program_id': 129, 'course_type_id': 2, 'course': 'DATA 200',  'notes': '' },
    { 'program_id': 129, 'course_type_id': 2, 'course': 'DATA 320',  'notes': '' },
    { 'program_id': 129, 'course_type_id': 2, 'course': 'IFSM 330',  'notes': '' },
    { 'program_id': 129, 'course_type_id': 2, 'course': 'DATA 335',  'notes': '' },
    { 'program_id': 129, 'course_type_id': 4, 'course': 'CSIA 300',  'notes': 'choose 1' },
    { 'program_id': 129, 'course_type_id': 4, 'course': 'DATA 300',  'notes': 'choose 1' },
    { 'program_id': 130, 'course_type_id': 4, 'course': 'IFSM 300',  'notes': 'choose 1' },
    { 'program_id': 130, 'course_type_id': 4, 'course': 'DATA 200',  'notes': 'choose 1' },
    { 'program_id': 130, 'course_type_id': 2, 'course': 'BMGT 364',  'notes': '' },
    { 'program_id': 130, 'course_type_id': 2, 'course': 'BMGT 365',  'notes': '' },
    { 'program_id': 130, 'course_type_id': 2, 'course': 'BMGT 495',  'notes': '' },
    { 'program_id': 130, 'course_type_id': 2, 'course': 'FINC 330',  'notes': '' },
    { 'program_id': 130, 'course_type_id': 2, 'course': 'MRKT 310',  'notes': '' },
    { 'program_id': 131, 'course_type_id': 2, 'course': 'CMST 295',  'notes': '' },
    { 'program_id': 131, 'course_type_id': 2, 'course': 'CMST 310',  'notes': '' },
    { 'program_id': 131, 'course_type_id': 2, 'course': 'CMST 311',  'notes': '' },
    { 'program_id': 131, 'course_type_id': 2, 'course': 'CMST 320',  'notes': '' },
    { 'program_id': 131, 'course_type_id': 2, 'course': 'CMST 325',  'notes': '' },
    { 'program_id': 131, 'course_type_id': 2, 'course': 'CMST 341',  'notes': '' },
    { 'program_id': 132, 'course_type_id': 2, 'course': 'MRKT 311',  'notes': '' },
    { 'program_id': 132, 'course_type_id': 2, 'course': 'MRKT 354',  'notes': '' },
    { 'program_id': 132, 'course_type_id': 2, 'course': 'MRKT 356',  'notes': '' },
    { 'program_id': 132, 'course_type_id': 2, 'course': 'MRKT 394',  'notes': '' },
    { 'program_id': 132, 'course_type_id': 2, 'course': 'MRKT 411',  'notes': '' },
    { 'program_id': 132, 'course_type_id': 2, 'course': 'MRKT 458',  'notes': '' },
    { 'program_id': 133, 'course_type_id': 2, 'course': 'HMGT 300',  'notes': '' },
    { 'program_id': 133, 'course_type_id': 2, 'course': 'IFSM 305',  'notes': '' },
    { 'program_id': 133, 'course_type_id': 2, 'course': 'STAT 200',  'notes': '' },
    { 'program_id': 133, 'course_type_id': 2, 'course': 'HMGT 307',  'notes': '' },
    { 'program_id': 133, 'course_type_id': 2, 'course': 'HMGT 320',  'notes': '' },
    { 'program_id': 133, 'course_type_id': 2, 'course': 'HMGT 400',  'notes': '' },
    { 'program_id': 134, 'course_type_id': 2, 'course': 'BMGT 364',  'notes': '' },
    { 'program_id': 134, 'course_type_id': 2, 'course': 'FINC 331',  'notes': '' },
    { 'program_id': 134, 'course_type_id': 2, 'course': 'HRMN 300',  'notes': '' },
    { 'program_id': 134, 'course_type_id': 2, 'course': 'HRMN 400',  'notes': '' },
    { 'program_id': 134, 'course_type_id': 2, 'course': 'HRMN 410',  'notes': '' },
    { 'program_id': 134, 'course_type_id': 2, 'course': 'IFSM 300',  'notes': '' },
    { 'program_id': 135, 'course_type_id': 2, 'course': 'BMGT 364',  'notes': '' },
    { 'program_id': 135, 'course_type_id': 2, 'course': 'HRMN 300',  'notes': '' },
    { 'program_id': 135, 'course_type_id': 2, 'course': 'HRMN 362',  'notes': '' },
    { 'program_id': 135, 'course_type_id': 2, 'course': 'HRMN 400',  'notes': '' },
    { 'program_id': 135, 'course_type_id': 4, 'course': 'BMGT 365',  'notes': 'choose 2' },
    { 'program_id': 135, 'course_type_id': 4, 'course': 'BMGT 464',  'notes': 'choose 2' },
    { 'program_id': 135, 'course_type_id': 4, 'course': 'BMGT 465',  'notes': 'choose 2' },
    { 'program_id': 135, 'course_type_id': 4, 'course': 'HRMN 302',  'notes': 'choose 2' },
    { 'program_id': 135, 'course_type_id': 4, 'course': 'HRMN 367',  'notes': 'choose 2' },
    { 'program_id': 135, 'course_type_id': 4, 'course': 'HRMN 395',  'notes': 'choose 2' },
    { 'program_id': 135, 'course_type_id': 4, 'course': 'HRMN 406',  'notes': 'choose 2' },
    { 'program_id': 135, 'course_type_id': 4, 'course': 'HRMN 495',  'notes': 'choose 2' },
    { 'program_id': 136, 'course_type_id': 2, 'course': 'BMGT 364',  'notes': '' },
    { 'program_id': 136, 'course_type_id': 2, 'course': 'BMGT 365',  'notes': '' },
    { 'program_id': 136, 'course_type_id': 2, 'course': 'BMGT 496',  'notes': '' },
    { 'program_id': 136, 'course_type_id': 2, 'course': 'HRMN 300',  'notes': '' },
    { 'program_id': 136, 'course_type_id': 2, 'course': 'BMGT 110',  'notes': '' },
    { 'program_id': 136, 'course_type_id': 2, 'course': 'BMGT 380',  'notes': '' },
    { 'program_id': 137, 'course_type_id': 2, 'course': 'STAT 200',  'notes': '' },
    { 'program_id': 137, 'course_type_id': 2, 'course': 'DATA 220',  'notes': '' },
    { 'program_id': 137, 'course_type_id': 2, 'course': 'DATA 300',  'notes': '' },
    { 'program_id': 137, 'course_type_id': 2, 'course': 'DATA 430',  'notes': '' },
    { 'program_id': 137, 'course_type_id': 2, 'course': 'DATA 450',  'notes': '' },
    { 'program_id': 137, 'course_type_id': 2, 'course': 'DATA 460',  'notes': '' },
    { 'program_id': 138, 'course_type_id': 2, 'course': 'BMGT 160',  'notes': '' },
    { 'program_id': 138, 'course_type_id': 2, 'course': 'BMGT 110',  'notes': '' },
    { 'program_id': 138, 'course_type_id': 4, 'course': 'ACCT 220',  'notes': 'choose 4' },
    { 'program_id': 138, 'course_type_id': 4, 'course': 'ACCT 221',  'notes': 'choose 4' },
    { 'program_id': 138, 'course_type_id': 4, 'course': 'ECON 201',  'notes': 'choose 4' },
    { 'program_id': 138, 'course_type_id': 4, 'course': 'ECON 203',  'notes': 'choose 4' },
    { 'program_id': 138, 'course_type_id': 4, 'course': 'IFSM 201',  'notes': 'choose 4' },
    { 'program_id': 138, 'course_type_id': 4, 'course': 'STAT 200',  'notes': 'choose 4' },
    { 'program_id': 139, 'course_type_id': 2, 'course': 'CSIA 300',  'notes': '' },
    { 'program_id': 139, 'course_type_id': 2, 'course': 'IFSM 300',  'notes': '' },
    { 'program_id': 139, 'course_type_id': 2, 'course': 'IFSM 301',  'notes': '' },
    { 'program_id': 139, 'course_type_id': 2, 'course': 'IFSM 310',  'notes': '' },
    { 'program_id': 139, 'course_type_id': 2, 'course': 'IFSM 370',  'notes': '' },
    { 'program_id': 139, 'course_type_id': 2, 'course': 'IFSM 330',  'notes': '' },
    { 'program_id': 140, 'course_type_id': 2, 'course': 'BMGT 487',  'notes': '' },
    { 'program_id': 140, 'course_type_id': 2, 'course': 'BMGT 488',  'notes': '' },
    { 'program_id': 140, 'course_type_id': 2, 'course': 'IFSM 438',  'notes': '' },
    { 'program_id': 140, 'course_type_id': 2, 'course': 'IFSM 441',  'notes': '' },
    { 'program_id': 140, 'course_type_id': 4, 'course': 'BMGT 317',  'notes': 'choose 2' },
    { 'program_id': 140, 'course_type_id': 4, 'course': 'BMGT 339',  'notes': 'choose 2' },
    { 'program_id': 140, 'course_type_id': 4, 'course': 'BMGT 365',  'notes': 'choose 2' },
    { 'program_id': 140, 'course_type_id': 4, 'course': 'BMGT 484',  'notes': 'choose 2' },
    { 'program_id': 140, 'course_type_id': 4, 'course': 'IFSM 300',  'notes': 'choose 2' },
    { 'program_id': 141, 'course_type_id': 2, 'course': 'PSAD 304',  'notes': '' },
    { 'program_id': 141, 'course_type_id': 2, 'course': 'PSAD 306',  'notes': '' },
    { 'program_id': 141, 'course_type_id': 2, 'course': 'PSAD 408',  'notes': '' },
    { 'program_id': 141, 'course_type_id': 2, 'course': 'PSAD 410',  'notes': '' },
    { 'program_id': 141, 'course_type_id': 2, 'course': 'PSAD 416',  'notes': '' },
    { 'program_id': 141, 'course_type_id': 2, 'course': 'PSAD 414',  'notes': '' },
    { 'program_id': 142, 'course_type_id': 2, 'course': 'SPAN 211',  'notes': '' },
    { 'program_id': 142, 'course_type_id': 2, 'course': 'SPAN 212',  'notes': '' },
    { 'program_id': 142, 'course_type_id': 2, 'course': 'SPAN 300+', 'notes': '' },
    { 'program_id': 142, 'course_type_id': 4, 'course': 'SPAN 418',  'notes': 'choose 1' },
    { 'program_id': 142, 'course_type_id': 4, 'course': 'SPAN 419',  'notes': 'choose 1' },
    { 'program_id': 143, 'course_type_id': 2, 'course': 'CMSC 105',  'notes': '' },
    { 'program_id': 143, 'course_type_id': 2, 'course': 'CMSC 115',  'notes': '' },
    { 'program_id': 143, 'course_type_id': 2, 'course': 'CMSC 215',  'notes': '' },
    { 'program_id': 143, 'course_type_id': 2, 'course': 'CMSC 320',  'notes': '' },
    { 'program_id': 143, 'course_type_id': 2, 'course': 'SDEV 300',  'notes': '' },
    { 'program_id': 143, 'course_type_id': 2, 'course': 'SDEV 325',  'notes': '' },
    { 'program_id': 143, 'course_type_id': 2, 'course': 'SDEV 360',  'notes': '' },
    { 'program_id': 144, 'course_type_id': 2, 'course': 'ENHS 300',  'notes': '' },
    { 'program_id': 144, 'course_type_id': 2, 'course': 'ENHS 305',  'notes': '' },
    { 'program_id': 144, 'course_type_id': 2, 'course': 'EHNS 340',  'notes': '' },
    { 'program_id': 144, 'course_type_id': 2, 'course': 'ENHS 350',  'notes': '' },
    { 'program_id': 144, 'course_type_id': 2, 'course': 'ENMT 360',  'notes': '' },
    { 'program_id': 144, 'course_type_id': 2, 'course': 'ENHS 405',  'notes': '' },
    { 'program_id': 145, 'course_type_id': 2, 'course': 'CMST 290',  'notes': '' },
    { 'program_id': 145, 'course_type_id': 2, 'course': 'CMST 295',  'notes': '' },
    { 'program_id': 145, 'course_type_id': 2, 'course': 'CMST 385',  'notes': '' },
    { 'program_id': 145, 'course_type_id': 2, 'course': 'CMST 386',  'notes': '' },
    { 'program_id': 145, 'course_type_id': 2, 'course': 'CMST 388',  'notes': '' },
    { 'program_id': 145, 'course_type_id': 2, 'course': 'CMST 355',  'notes': '' },
    { 'program_id': 146, 'course_type_id': 2, 'course': 'WMST 200',  'notes': '' },
    { 'program_id': 146, 'course_type_id': 4, 'course': 'BEHS 220',  'notes': 'choose 5' },
    { 'program_id': 146, 'course_type_id': 4, 'course': 'BEHS 250',  'notes': 'choose 5' },
    { 'program_id': 146, 'course_type_id': 4, 'course': 'BEHS 343',  'notes': 'choose 5' },
    { 'program_id': 146, 'course_type_id': 4, 'course': 'BEHS 453',  'notes': 'choose 5' },
    { 'program_id': 146, 'course_type_id': 4, 'course': 'ENGL 250',  'notes': 'choose 5' },
    { 'program_id': 146, 'course_type_id': 4, 'course': 'GERO 311',  'notes': 'choose 5' },
    { 'program_id': 146, 'course_type_id': 4, 'course': 'HIST 377',  'notes': 'choose 5' },
    { 'program_id': 146, 'course_type_id': 4, 'course': 'PSYC 332',  'notes': 'choose 5' },
    { 'program_id': 146, 'course_type_id': 4, 'course': 'SOCY 325',  'notes': 'choose 5' },
    { 'program_id': 146, 'course_type_id': 4, 'course': 'SOCY 443',  'notes': 'choose 5' },
    { 'program_id': 146, 'course_type_id': 4, 'course': 'SOCY 462',  'notes': 'choose 5' },
    { 'program_id': 146, 'course_type_id': 4, 'course': 'SPCH 324',  'notes': 'choose 5' }
]

c.executemany('''
    INSERT INTO program_requirement_courses (program_id, course_type_id, course, notes) 
       VALUES (:program_id, :course_type_id, :course, :notes)
''', undergrad_certification_courses)
conn.commit()

# Close the connection
conn.close()
