import sqlite3
# db connection created w/in utils
from utils import conn, c, drop_table, drop_view, column_exists

catalog_programs_add_02 = [
    { 'program_id':  2, 'seq':  1, 'course': 'LIBS 150' },
    { 'program_id':  2, 'seq':  2, 'course': 'PACE 111B' },
    { 'program_id':  2, 'seq':  3, 'course': 'WRTG 111' },
    { 'program_id':  2, 'seq':  4, 'course': 'DATA 200' },
    { 'program_id':  2, 'seq':  5, 'course': 'NUTR 100' },
    { 'program_id':  2, 'seq':  6, 'course': 'NUTR 101' },
    { 'program_id':  2, 'seq':  7, 'course': 'ACCT 220' },
    { 'program_id':  2, 'seq':  8, 'course': 'WRTG 112' },
    { 'program_id':  2, 'seq':  9, 'course': 'STAT 200' },
    { 'program_id':  2, 'seq': 10, 'course': 'WRTG 293' },
    { 'program_id':  2, 'seq': 11, 'course': 'ACCT 221' },
    { 'program_id':  2, 'seq': 12, 'course': 'HIST 125' },
    { 'program_id':  2, 'seq': 13, 'course': 'NSCI 100' },
    { 'program_id':  2, 'seq': 14, 'course': 'ECON 201' },
    { 'program_id':  2, 'seq': 15, 'course': 'ARTH 334' },
    { 'program_id':  2, 'seq': 16, 'course': 'CSIA 300' },
    { 'program_id':  2, 'seq': 17, 'course': 'ECON 203' },
    { 'program_id':  2, 'seq': 18, 'course': 'ACCT 310' },
    { 'program_id':  2, 'seq': 19, 'course': 'FINC 330' },
    { 'program_id':  2, 'seq': 20, 'course': 'ACCT 311' },
    { 'program_id':  2, 'seq': 21, 'course': 'DATA 320' },
    { 'program_id':  2, 'seq': 22, 'course': 'ACCT 326' },
    { 'program_id':  2, 'seq': 23, 'course': 'IFSM 330' },
    { 'program_id':  2, 'seq': 24, 'course': 'ACCT 321' },
    { 'program_id':  2, 'seq': 25, 'course': 'WRTG 394' },
    { 'program_id':  2, 'seq': 26, 'course': 'DATA 335' },
    { 'program_id':  2, 'seq': 27, 'course': 'ACCT 323' },
    { 'program_id':  2, 'seq': 28, 'course': 'ACCT 411' },
    { 'program_id':  2, 'seq': 29, 'course': 'CSIA 310' },
    { 'program_id':  2, 'seq': 30, 'course': 'ACCT 410' },
    { 'program_id':  2, 'seq': 31, 'course': 'BMGT 364' },
    { 'program_id':  2, 'seq': 32, 'course': 'MRKT 310' },
    { 'program_id':  2, 'seq': 33, 'course': 'ACCT 422' },
    { 'program_id':  2, 'seq': 34, 'course': 'BMGT 380' },
    { 'program_id':  2, 'seq': 35, 'course': 'CSIA 350' },
    { 'program_id':  2, 'seq': 36, 'course': 'ACCT 424' },
    { 'program_id':  2, 'seq': 37, 'course': 'FINC 328' },
    { 'program_id':  2, 'seq': 38, 'course': 'ACCT 436' },
    { 'program_id':  2, 'seq': 39, 'course': 'BMGT 335' },
    { 'program_id':  2, 'seq': 40, 'course': 'IFSM 438' },
    { 'program_id':  2, 'seq': 41, 'course': 'ACCT 438' },
    { 'program_id':  2, 'seq': 42, 'course': 'CAPL 398A' }
]

catalog_programs_add_05 = [
    { 'program_id':  5, 'seq':  1, 'course': 'LIBS 150' },
    { 'program_id':  5, 'seq':  2, 'course': 'PACE 111B' },
    { 'program_id':  5, 'seq':  3, 'course': 'WRTG 111' },
    { 'program_id':  5, 'seq':  4, 'course': 'WRTG 112' },
    { 'program_id':  5, 'seq':  5, 'course': 'NUTR 100' },
    { 'program_id':  5, 'seq':  6, 'course': 'BMGT 110' },
    { 'program_id':  5, 'seq':  7, 'course': 'SPCH 100' },
    { 'program_id':  5, 'seq':  8, 'course': 'STAT 200' },
    { 'program_id':  5, 'seq':  9, 'course': 'IFSM 300' },
    { 'program_id':  5, 'seq': 10, 'course': 'ACCT 220' },
    { 'program_id':  5, 'seq': 11, 'course': 'HUMN 100' },
    { 'program_id':  5, 'seq': 12, 'course': 'BIOL 103' },
    { 'program_id':  5, 'seq': 13, 'course': 'ECON 201' },
    { 'program_id':  5, 'seq': 14, 'course': 'ARTH 334' },
    { 'program_id':  5, 'seq': 15, 'course': 'ELECTIVE' },
    { 'program_id':  5, 'seq': 16, 'course': 'ECON 203' },
    { 'program_id':  5, 'seq': 17, 'course': 'ACCT 221' },
    { 'program_id':  5, 'seq': 18, 'course': 'ELECTIVE' },
    { 'program_id':  5, 'seq': 19, 'course': 'BMGT 364' },
    { 'program_id':  5, 'seq': 20, 'course': 'ELECTIVE' },
    { 'program_id':  5, 'seq': 21, 'course': 'BMGT 365' },
    { 'program_id':  5, 'seq': 22, 'course': 'ELECTIVE' },
    { 'program_id':  5, 'seq': 23, 'course': 'MRKT 310' },
    { 'program_id':  5, 'seq': 24, 'course': 'WRTG 394' },
    { 'program_id':  5, 'seq': 25, 'course': 'ELECTIVE' },
    { 'program_id':  5, 'seq': 26, 'course': 'BMGT 380' },
    { 'program_id':  5, 'seq': 27, 'course': 'ELECTIVE' },
    { 'program_id':  5, 'seq': 28, 'course': 'ELECTIVE' },
    { 'program_id':  5, 'seq': 29, 'course': 'HRMN 300' },
    { 'program_id':  5, 'seq': 30, 'course': 'ELECTIVE' },
    { 'program_id':  5, 'seq': 31, 'course': 'ELECTIVE' },
    { 'program_id':  5, 'seq': 32, 'course': 'FINC 330' },
    { 'program_id':  5, 'seq': 33, 'course': 'ELECTIVE' },
    { 'program_id':  5, 'seq': 34, 'course': 'ELECTIVE' },
    { 'program_id':  5, 'seq': 35, 'course': 'BMGT 496' },
    { 'program_id':  5, 'seq': 36, 'course': 'ELECTIVE' },
    { 'program_id':  5, 'seq': 37, 'course': 'ELECTIVE' },
    { 'program_id':  5, 'seq': 38, 'course': 'ELECTIVE' },
    { 'program_id':  5, 'seq': 39, 'course': 'ELECTIVE' },
    { 'program_id':  5, 'seq': 40, 'course': 'BMGT 495' },
    { 'program_id':  5, 'seq': 41, 'course': 'CAPL 398A' }
]

catalog_programs_add_06 = [
    { 'program_id':  6, 'seq':  1, 'course': 'LIBS 150' },
    { 'program_id':  6, 'seq':  2, 'course': 'PACE 111C' },
    { 'program_id':  6, 'seq':  3, 'course': 'WRTG 111' },
    { 'program_id':  6, 'seq':  4, 'course': 'SPCH 100' },
    { 'program_id':  6, 'seq':  5, 'course': 'NUTR 100' },
    { 'program_id':  6, 'seq':  6, 'course': 'COMM 207' },
    { 'program_id':  6, 'seq':  7, 'course': 'WRTG 112' },
    { 'program_id':  6, 'seq':  8, 'course': 'MATH 105' },
    { 'program_id':  6, 'seq':  9, 'course': 'COMM 202' },
    { 'program_id':  6, 'seq': 10, 'course': 'JOUR 201' },
    { 'program_id':  6, 'seq': 11, 'course': 'HUMN 100' },
    { 'program_id':  6, 'seq': 12, 'course': 'BIOL 103' },
    { 'program_id':  6, 'seq': 13, 'course': 'BEHS 103' },
    { 'program_id':  6, 'seq': 14, 'course': 'ARTH 334' },
    { 'program_id':  6, 'seq': 15, 'course': 'IFSM 201' },
    { 'program_id':  6, 'seq': 16, 'course': 'ECON 103' },
    { 'program_id':  6, 'seq': 17, 'course': 'COMM 300' },
    { 'program_id':  6, 'seq': 18, 'course': 'ELECTIVE' },
    { 'program_id':  6, 'seq': 19, 'course': 'COMM 302' },
    { 'program_id':  6, 'seq': 20, 'course': 'ELECTIVE' },
    { 'program_id':  6, 'seq': 21, 'course': 'SPCH 324' },
    { 'program_id':  6, 'seq': 22, 'course': 'ELECTIVE' },
    { 'program_id':  6, 'seq': 23, 'course': 'JOUR 330' },
    { 'program_id':  6, 'seq': 24, 'course': 'WRTG 391' },
    { 'program_id':  6, 'seq': 25, 'course': 'ELECTIVE' },
    { 'program_id':  6, 'seq': 26, 'course': 'COMM 400' },
    { 'program_id':  6, 'seq': 27, 'course': 'ELECTIVE' },
    { 'program_id':  6, 'seq': 28, 'course': 'ELECTIVE' },
    { 'program_id':  6, 'seq': 29, 'course': 'SPCH 470' },
    { 'program_id':  6, 'seq': 30, 'course': 'ELECTIVE' },
    { 'program_id':  6, 'seq': 31, 'course': 'ELECTIVE' },
    { 'program_id':  6, 'seq': 32, 'course': 'COMM 390' },
    { 'program_id':  6, 'seq': 33, 'course': 'ELECTIVE' },
    { 'program_id':  6, 'seq': 34, 'course': 'ELECTIVE' },
    { 'program_id':  6, 'seq': 35, 'course': 'ELECTIVE' },
    { 'program_id':  6, 'seq': 36, 'course': 'ELECTIVE' },
    { 'program_id':  6, 'seq': 37, 'course': 'ELECTIVE' },
    { 'program_id':  6, 'seq': 38, 'course': 'ELECTIVE' },
    { 'program_id':  6, 'seq': 39, 'course': 'ELECTIVE' },
    { 'program_id':  6, 'seq': 40, 'course': 'COMM 495' },
    { 'program_id':  6, 'seq': 41, 'course': 'CAPL 398A' }
]

catalog_programs_add_07 = [
    { 'program_id':  7, 'seq':  1, 'course': 'LIBS 150' },
    { 'program_id':  7, 'seq':  2, 'course': 'PACE 111T' },
    { 'program_id':  7, 'seq':  3, 'course': 'WRTG 111' },
    { 'program_id':  7, 'seq':  4, 'course': 'CMSC 105' },
    { 'program_id':  7, 'seq':  5, 'course': 'NUTR 100' },
    { 'program_id':  7, 'seq':  6, 'course': 'CMSC 115' },
    { 'program_id':  7, 'seq':  7, 'course': 'SPCH 100' },
    { 'program_id':  7, 'seq':  8, 'course': 'MATH 140' },
    { 'program_id':  7, 'seq':  9, 'course': 'WRTG 112' },
    { 'program_id':  7, 'seq': 10, 'course': 'CMSC 215' },
    { 'program_id':  7, 'seq': 11, 'course': 'HIST 125' },
    { 'program_id':  7, 'seq': 12, 'course': 'BIOL 103' },
    { 'program_id':  7, 'seq': 13, 'course': 'BEHS 103' },
    { 'program_id':  7, 'seq': 14, 'course': 'ARTH 334' },
    { 'program_id':  7, 'seq': 15, 'course': 'CMSC 150' },
    { 'program_id':  7, 'seq': 16, 'course': 'ECON 103' },
    { 'program_id':  7, 'seq': 17, 'course': 'CMSC 310' },
    { 'program_id':  7, 'seq': 18, 'course': 'MATH 141' },
    { 'program_id':  7, 'seq': 19, 'course': 'CMIT 265' },
    { 'program_id':  7, 'seq': 20, 'course': 'ELECTIVE' },
    { 'program_id':  7, 'seq': 21, 'course': 'CMSC 315' },
    { 'program_id':  7, 'seq': 22, 'course': 'ELECTIVE' },
    { 'program_id':  7, 'seq': 23, 'course': 'CMSC 320' },
    { 'program_id':  7, 'seq': 24, 'course': 'CMSC 330' },
    { 'program_id':  7, 'seq': 25, 'course': 'WRTG 393' },
    { 'program_id':  7, 'seq': 26, 'course': 'ELECTIVE' },
    { 'program_id':  7, 'seq': 27, 'course': 'CMSC 335' },
    { 'program_id':  7, 'seq': 28, 'course': 'ELECTIVE' },
    { 'program_id':  7, 'seq': 29, 'course': 'ELECTIVE' },
    { 'program_id':  7, 'seq': 30, 'course': 'CMSC 345' },
    { 'program_id':  7, 'seq': 31, 'course': 'ELECTIVE' },
    { 'program_id':  7, 'seq': 32, 'course': 'ELECTIVE' },
    { 'program_id':  7, 'seq': 33, 'course': 'ELECTIVE' },
    { 'program_id':  7, 'seq': 34, 'course': 'CMSC 430' },
    { 'program_id':  7, 'seq': 35, 'course': 'ELECTIVE' },
    { 'program_id':  7, 'seq': 36, 'course': 'ELECTIVE' },
    { 'program_id':  7, 'seq': 37, 'course': 'CMSC 451' },
    { 'program_id':  7, 'seq': 38, 'course': 'ELECTIVE' },
    { 'program_id':  7, 'seq': 39, 'course': 'CMSC 495' },
    { 'program_id':  7, 'seq': 40, 'course': 'ELECTIVE' }
]

catalog_programs_add_08 = [
    { 'program_id':  8, 'seq':  1, 'course': 'LIBS 150' },
    { 'program_id':  8, 'seq':  2, 'course': 'PACE 111P' },
    { 'program_id':  8, 'seq':  3, 'course': 'WRTG 111' },
    { 'program_id':  8, 'seq':  4, 'course': 'IFSM 201' },
    { 'program_id':  8, 'seq':  5, 'course': 'NUTR 100' },
    { 'program_id':  8, 'seq':  6, 'course': 'CCJS 100' },
    { 'program_id':  8, 'seq':  7, 'course': 'SPCH 100' },
    { 'program_id':  8, 'seq':  8, 'course': 'MATH 105' },
    { 'program_id':  8, 'seq':  9, 'course': 'WRTG 112' },
    { 'program_id':  8, 'seq': 10, 'course': 'CCJS 230' },
    { 'program_id':  8, 'seq': 11, 'course': 'HUMN 100' },
    { 'program_id':  8, 'seq': 12, 'course': 'BIOL 103' },
    { 'program_id':  8, 'seq': 13, 'course': 'BEHS 103' },
    { 'program_id':  8, 'seq': 14, 'course': 'HIST 125' },
    { 'program_id':  8, 'seq': 15, 'course': 'ELECTIVE' },
    { 'program_id':  8, 'seq': 16, 'course': 'ECON 103' },
    { 'program_id':  8, 'seq': 17, 'course': 'CCJS 340' },
    { 'program_id':  8, 'seq': 18, 'course': 'ELECTIVE' },
    { 'program_id':  8, 'seq': 19, 'course': 'ELECTIVE' },
    { 'program_id':  8, 'seq': 20, 'course': 'CCJS 345' },
    { 'program_id':  8, 'seq': 21, 'course': 'ELECTIVE' },
    { 'program_id':  8, 'seq': 22, 'course': 'CCJS 350' },
    { 'program_id':  8, 'seq': 23, 'course': 'WRTG 391' },
    { 'program_id':  8, 'seq': 24, 'course': 'ELECTIVE' },
    { 'program_id':  8, 'seq': 25, 'course': 'CCJS 360' },
    { 'program_id':  8, 'seq': 26, 'course': 'ELECTIVE' },
    { 'program_id':  8, 'seq': 27, 'course': 'ELECTIVE' },
    { 'program_id':  8, 'seq': 28, 'course': 'CCJS 380' },
    { 'program_id':  8, 'seq': 29, 'course': 'ELECTIVE' },
    { 'program_id':  8, 'seq': 30, 'course': 'ELECTIVE' },
    { 'program_id':  8, 'seq': 31, 'course': 'CCJS 341' },
    { 'program_id':  8, 'seq': 32, 'course': 'ELECTIVE' },
    { 'program_id':  8, 'seq': 33, 'course': 'ELECTIVE' },
    { 'program_id':  8, 'seq': 34, 'course': 'CCJS 352' },
    { 'program_id':  8, 'seq': 35, 'course': 'ELECTIVE' },
    { 'program_id':  8, 'seq': 36, 'course': 'ELECTIVE' },
    { 'program_id':  8, 'seq': 37, 'course': 'ELECTIVE' },
    { 'program_id':  8, 'seq': 38, 'course': 'CCJS 497' },
    { 'program_id':  8, 'seq': 39, 'course': 'ELECTIVE' },
    { 'program_id':  8, 'seq': 40, 'course': 'CCJS 495' },
    { 'program_id':  8, 'seq': 41, 'course': 'CAPL 398A' }
]

catalog_programs_add_09 = [
    { 'program_id':  9, 'seq':  1, 'course': 'LIBS 150' },
    { 'program_id':  9, 'seq':  2, 'course': 'PACE 111T' },
    { 'program_id':  9, 'seq':  3, 'course': 'WRTG 111' },
    { 'program_id':  9, 'seq':  4, 'course': 'IFSM 201' },
    { 'program_id':  9, 'seq':  5, 'course': 'NUTR 100' },
    { 'program_id':  9, 'seq':  6, 'course': 'CSIA 300' },
    { 'program_id':  9, 'seq':  7, 'course': 'SPCH 100' },
    { 'program_id':  9, 'seq':  8, 'course': 'MATH 107' },
    { 'program_id':  9, 'seq':  9, 'course': 'WRTG 112' },
    { 'program_id':  9, 'seq': 10, 'course': 'IFSM 304' },
    { 'program_id':  9, 'seq': 11, 'course': 'HIST 125' },
    { 'program_id':  9, 'seq': 12, 'course': 'BIOL 103' },
    { 'program_id':  9, 'seq': 13, 'course': 'BEHS 103' },
    { 'program_id':  9, 'seq': 14, 'course': 'ARTH 334' },
    { 'program_id':  9, 'seq': 15, 'course': 'ELECTIVE' },
    { 'program_id':  9, 'seq': 16, 'course': 'ECON 103' },
    { 'program_id':  9, 'seq': 17, 'course': 'CMIT 265' },
    { 'program_id':  9, 'seq': 18, 'course': 'ELECTIVE' },
    { 'program_id':  9, 'seq': 19, 'course': 'CMIT 320' },
    { 'program_id':  9, 'seq': 20, 'course': 'ELECTIVE' },
    { 'program_id':  9, 'seq': 21, 'course': 'CSIA 310' },
    { 'program_id':  9, 'seq': 22, 'course': 'ELECTIVE' },
    { 'program_id':  9, 'seq': 23, 'course': 'CSIA 350' },
    { 'program_id':  9, 'seq': 24, 'course': 'WRTG 393' },
    { 'program_id':  9, 'seq': 25, 'course': 'ELECTIVE' },
    { 'program_id':  9, 'seq': 26, 'course': 'CSIA 360' },
    { 'program_id':  9, 'seq': 27, 'course': 'ELECTIVE' },
    { 'program_id':  9, 'seq': 28, 'course': 'ELECTIVE' },
    { 'program_id':  9, 'seq': 29, 'course': 'CSIA 413' },
    { 'program_id':  9, 'seq': 30, 'course': 'ELECTIVE' },
    { 'program_id':  9, 'seq': 31, 'course': 'ELECTIVE' },
    { 'program_id':  9, 'seq': 32, 'course': 'CSIA 459' },
    { 'program_id':  9, 'seq': 33, 'course': 'ELECTIVE' },
    { 'program_id':  9, 'seq': 34, 'course': 'ELECTIVE' },
    { 'program_id':  9, 'seq': 35, 'course': 'CMIT 425' },
    { 'program_id':  9, 'seq': 36, 'course': 'ELECTIVE' },
    { 'program_id':  9, 'seq': 37, 'course': 'ELECTIVE' },
    { 'program_id':  9, 'seq': 38, 'course': 'ELECTIVE' },
    { 'program_id':  9, 'seq': 39, 'course': 'ELECTIVE' },
    { 'program_id':  9, 'seq': 40, 'course': 'CSIA 485' },
    { 'program_id':  9, 'seq': 41, 'course': 'CAPL 398A' }
]

catalog_programs_add_10 = [
    { 'program_id': 10, 'seq':  1, 'course': 'LIBS 150' },
    { 'program_id': 10, 'seq':  2, 'course': 'PACE 111T' },
    { 'program_id': 10, 'seq':  3, 'course': 'WRTG 111' },
    { 'program_id': 10, 'seq':  4, 'course': 'IFSM 201' },
    { 'program_id': 10, 'seq':  5, 'course': 'NUTR 100' },
    { 'program_id': 10, 'seq':  6, 'course': 'CMIT 202' },
    { 'program_id': 10, 'seq':  7, 'course': 'SPCH 100' },
    { 'program_id': 10, 'seq':  8, 'course': 'MATH 107' },
    { 'program_id': 10, 'seq':  9, 'course': 'WRTG 112' },
    { 'program_id': 10, 'seq': 10, 'course': 'CMIT 265' },
    { 'program_id': 10, 'seq': 11, 'course': 'HIST 125' },
    { 'program_id': 10, 'seq': 12, 'course': 'BIOL 103' },
    { 'program_id': 10, 'seq': 13, 'course': 'BEHS 103' },
    { 'program_id': 10, 'seq': 14, 'course': 'ARTH 334' },
    { 'program_id': 10, 'seq': 15, 'course': 'ELECTIVE' },
    { 'program_id': 10, 'seq': 16, 'course': 'ECON 103' },
    { 'program_id': 10, 'seq': 17, 'course': 'CMIT 291' },
    { 'program_id': 10, 'seq': 18, 'course': 'CMIT 320' },
    { 'program_id': 10, 'seq': 19, 'course': 'ELECTIVE' },
    { 'program_id': 10, 'seq': 20, 'course': 'CMIT 321' },
    { 'program_id': 10, 'seq': 21, 'course': 'ELECTIVE' },
    { 'program_id': 10, 'seq': 22, 'course': 'CMIT 351' },
    { 'program_id': 10, 'seq': 23, 'course': 'ELECTIVE' },
    { 'program_id': 10, 'seq': 24, 'course': 'CMIT 326' },
    { 'program_id': 10, 'seq': 25, 'course': 'WRTG 393' },
    { 'program_id': 10, 'seq': 26, 'course': 'ELECTIVE' },
    { 'program_id': 10, 'seq': 27, 'course': 'ELECTIVE' },
    { 'program_id': 10, 'seq': 28, 'course': 'ELECTIVE' },
    { 'program_id': 10, 'seq': 29, 'course': 'CMIT 421' },
    { 'program_id': 10, 'seq': 30, 'course': 'ELECTIVE' },
    { 'program_id': 10, 'seq': 31, 'course': 'ELECTIVE' },
    { 'program_id': 10, 'seq': 32, 'course': 'CMIT 386' },
    { 'program_id': 10, 'seq': 33, 'course': 'ELECTIVE' },
    { 'program_id': 10, 'seq': 34, 'course': 'ELECTIVE' },
    { 'program_id': 10, 'seq': 35, 'course': 'CCJS 321' },
    { 'program_id': 10, 'seq': 36, 'course': 'ELECTIVE' },
    { 'program_id': 10, 'seq': 37, 'course': 'ELECTIVE' },
    { 'program_id': 10, 'seq': 38, 'course': 'ELECTIVE' },
    { 'program_id': 10, 'seq': 39, 'course': 'ELECTIVE' },
    { 'program_id': 10, 'seq': 40, 'course': 'CMIT 495' },
    { 'program_id': 10, 'seq': 41, 'course': 'CAPL 398A' }
]

catalog_programs_add_11 = [
    { 'program_id': 11, 'seq':  1, 'course': 'LIBS 150' },
    { 'program_id': 11, 'seq':  2, 'course': 'PACE 111T' },
    { 'program_id': 11, 'seq':  3, 'course': 'WRTG 111' },
    { 'program_id': 11, 'seq':  4, 'course': 'MATH 115' },
    { 'program_id': 11, 'seq':  5, 'course': 'DATA 200' },
    { 'program_id': 11, 'seq':  6, 'course': 'NUTR 100' },
    { 'program_id': 11, 'seq':  7, 'course': 'NUTR 101' },
    { 'program_id': 11, 'seq':  8, 'course': 'STAT 200' },
    { 'program_id': 11, 'seq':  9, 'course': 'SPCH 100' },
    { 'program_id': 11, 'seq': 10, 'course': 'DATA 230' },
    { 'program_id': 11, 'seq': 11, 'course': 'WRTG 112' },
    { 'program_id': 11, 'seq': 12, 'course': 'DATA 300' },
    { 'program_id': 11, 'seq': 13, 'course': 'HIST 125' },
    { 'program_id': 11, 'seq': 14, 'course': 'NSCI 103' },
    { 'program_id': 11, 'seq': 15, 'course': 'BEHS 103' },
    { 'program_id': 11, 'seq': 16, 'course': 'ARTH 334' },
    { 'program_id': 11, 'seq': 17, 'course': 'ELECTIVE' },
    { 'program_id': 11, 'seq': 18, 'course': 'ECON 103' },
    { 'program_id': 11, 'seq': 19, 'course': 'CSIA 300' },
    { 'program_id': 11, 'seq': 20, 'course': 'ELECTIVE' },
    { 'program_id': 11, 'seq': 21, 'course': 'DATA 320' },
    { 'program_id': 11, 'seq': 22, 'course': 'ELECTIVE' },
    { 'program_id': 11, 'seq': 23, 'course': 'IFSM 330' },
    { 'program_id': 11, 'seq': 24, 'course': 'ELECTIVE' },
    { 'program_id': 11, 'seq': 25, 'course': 'DATA 335' },
    { 'program_id': 11, 'seq': 26, 'course': 'WRTG 393' },
    { 'program_id': 11, 'seq': 27, 'course': 'ELECTIVE' },
    { 'program_id': 11, 'seq': 28, 'course': 'DATA 430' },
    { 'program_id': 11, 'seq': 29, 'course': 'ELECTIVE' },
    { 'program_id': 11, 'seq': 30, 'course': 'ELECTIVE' },
    { 'program_id': 11, 'seq': 31, 'course': 'DATA 440' },
    { 'program_id': 11, 'seq': 32, 'course': 'ELECTIVE' },
    { 'program_id': 11, 'seq': 33, 'course': 'DATA 445' },
    { 'program_id': 11, 'seq': 34, 'course': 'ELECTIVE' },
    { 'program_id': 11, 'seq': 35, 'course': 'ELECTIVE' },
    { 'program_id': 11, 'seq': 36, 'course': 'DATA 450' },
    { 'program_id': 11, 'seq': 37, 'course': 'ELECTIVE' },
    { 'program_id': 11, 'seq': 38, 'course': 'ELECTIVE' },
    { 'program_id': 11, 'seq': 39, 'course': 'DATA 460' },
    { 'program_id': 11, 'seq': 40, 'course': 'ELECTIVE' },
    { 'program_id': 11, 'seq': 41, 'course': 'DATA 495' }
]

catalog_programs_add_12 = [
    { 'program_id': 12, 'seq':  1, 'course': 'LIBS 150' },
    { 'program_id': 12, 'seq':  2, 'course': 'PACE 111C' },
    { 'program_id': 12, 'seq':  3, 'course': 'WRTG 111' },
    { 'program_id': 12, 'seq':  4, 'course': 'IFSM 201' },
    { 'program_id': 12, 'seq':  5, 'course': 'CHIN 111' },
    { 'program_id': 12, 'seq':  6, 'course': 'NUTR 100' },
    { 'program_id': 12, 'seq':  7, 'course': 'ASTD 284' },
    { 'program_id': 12, 'seq':  8, 'course': 'CHIN 112' },
    { 'program_id': 12, 'seq':  9, 'course': 'SPCH 100' },
    { 'program_id': 12, 'seq': 10, 'course': 'MATH 105' },
    { 'program_id': 12, 'seq': 11, 'course': 'CHIN 114' },
    { 'program_id': 12, 'seq': 12, 'course': 'WRTG 112' },
    { 'program_id': 12, 'seq': 13, 'course': 'ASTD 285' },
    { 'program_id': 12, 'seq': 14, 'course': 'HUMN 100' },
    { 'program_id': 12, 'seq': 15, 'course': 'BIOL 103' },
    { 'program_id': 12, 'seq': 16, 'course': 'BEHS 103' },
    { 'program_id': 12, 'seq': 17, 'course': 'ARTH 334' },
    { 'program_id': 12, 'seq': 18, 'course': 'ELECTIVE' },
    { 'program_id': 12, 'seq': 19, 'course': 'ECON 103' },
    { 'program_id': 12, 'seq': 20, 'course': 'PHIL 348' },
    { 'program_id': 12, 'seq': 21, 'course': 'ELECTIVE' },
    { 'program_id': 12, 'seq': 22, 'course': 'ELECTIVE' },
    { 'program_id': 12, 'seq': 23, 'course': 'ELECTIVE' },
    { 'program_id': 12, 'seq': 24, 'course': 'ELECTIVE' },
    { 'program_id': 12, 'seq': 25, 'course': 'WRTG 391' },
    { 'program_id': 12, 'seq': 26, 'course': 'ELECTIVE' },
    { 'program_id': 12, 'seq': 27, 'course': 'ELECTIVE' },
    { 'program_id': 12, 'seq': 28, 'course': 'ELECTIVE' },
    { 'program_id': 12, 'seq': 29, 'course': 'HIST 480' },
    { 'program_id': 12, 'seq': 30, 'course': 'ELECTIVE' },
    { 'program_id': 12, 'seq': 31, 'course': 'ELECTIVE' },
    { 'program_id': 12, 'seq': 32, 'course': 'ASTD 370' },
    { 'program_id': 12, 'seq': 33, 'course': 'ELECTIVE' },
    { 'program_id': 12, 'seq': 34, 'course': 'ELECTIVE' },
    { 'program_id': 12, 'seq': 35, 'course': 'ANTH 417' },
    { 'program_id': 12, 'seq': 36, 'course': 'ELECTIVE' },
    { 'program_id': 12, 'seq': 37, 'course': 'ELECTIVE' },
    { 'program_id': 12, 'seq': 38, 'course': 'ELECTIVE' },
    { 'program_id': 12, 'seq': 39, 'course': 'ELECTIVE' },
    { 'program_id': 12, 'seq': 40, 'course': 'ASTD 485' },
    { 'program_id': 12, 'seq': 41, 'course': 'CAPL 398A' }
]

catalog_programs_add_13 = [
    { 'program_id': 13, 'seq':  1, 'course': 'LIBS 150' },
    { 'program_id': 13, 'seq':  2, 'course': 'PACE 111C' },
    { 'program_id': 13, 'seq':  3, 'course': 'WRTG 112' },
    { 'program_id': 13, 'seq':  4, 'course': 'CMST 301' },
    { 'program_id': 13, 'seq':  5, 'course': 'NUTR 100' },
    { 'program_id': 13, 'seq':  6, 'course': 'ENGL 102' },
    { 'program_id': 13, 'seq':  7, 'course': 'ENGL 281' },
    { 'program_id': 13, 'seq':  8, 'course': 'MATH 105' },
    { 'program_id': 13, 'seq':  9, 'course': 'ENGL 240' },
    { 'program_id': 13, 'seq': 10, 'course': 'ENGL 250' },
    { 'program_id': 13, 'seq': 11, 'course': 'HUMN 100' },
    { 'program_id': 13, 'seq': 12, 'course': 'BIOL 103' },
    { 'program_id': 13, 'seq': 13, 'course': 'BEHS 103' },
    { 'program_id': 13, 'seq': 14, 'course': 'ARTH 334' },
    { 'program_id': 13, 'seq': 15, 'course': 'ELECTIVE' },
    { 'program_id': 13, 'seq': 16, 'course': 'ECON 103' },
    { 'program_id': 13, 'seq': 17, 'course': 'ENGL 303' },
    { 'program_id': 13, 'seq': 18, 'course': 'ELECTIVE' },
    { 'program_id': 13, 'seq': 19, 'course': 'ELECTIVE' },
    { 'program_id': 13, 'seq': 20, 'course': 'ENGL 310' },
    { 'program_id': 13, 'seq': 21, 'course': 'ELECTIVE' },
    { 'program_id': 13, 'seq': 22, 'course': 'ENGL 363|ENGL 311' },
    { 'program_id': 13, 'seq': 23, 'course': 'WRTG 391' },
    { 'program_id': 13, 'seq': 24, 'course': 'ELECTIVE' },
    { 'program_id': 13, 'seq': 25, 'course': 'ENGL 364|ENGL 312' },
    { 'program_id': 13, 'seq': 26, 'course': 'ELECTIVE' },
    { 'program_id': 13, 'seq': 27, 'course': 'ELECTIVE' },
    { 'program_id': 13, 'seq': 28, 'course': 'ENGL 430' },
    { 'program_id': 13, 'seq': 29, 'course': 'ELECTIVE' },
    { 'program_id': 13, 'seq': 30, 'course': 'ELECTIVE' },
    { 'program_id': 13, 'seq': 31, 'course': 'ENGL 433|ENGL 386' },
    { 'program_id': 13, 'seq': 32, 'course': 'ELECTIVE' },
    { 'program_id': 13, 'seq': 33, 'course': 'ELECTIVE' },
    { 'program_id': 13, 'seq': 34, 'course': 'ENGL 441|ENGL 406' },
    { 'program_id': 13, 'seq': 35, 'course': 'ELECTIVE' },
    { 'program_id': 13, 'seq': 36, 'course': 'ELECTIVE' },
    { 'program_id': 13, 'seq': 37, 'course': 'ELECTIVE' },
    { 'program_id': 13, 'seq': 38, 'course': 'ELECTIVE' },
    { 'program_id': 13, 'seq': 39, 'course': 'ENGL 459' },
    { 'program_id': 13, 'seq': 40, 'course': 'ENGL 495' },
    { 'program_id': 13, 'seq': 41, 'course': 'CAPL 398A' }
]

catalog_programs_add_14 = [
    { 'program_id': 14, 'seq':  1, 'course': 'LIBS 150' },
    { 'program_id': 14, 'seq':  2, 'course': 'PACE 111S' },
    { 'program_id': 14, 'seq':  3, 'course': 'WRTG 111' },
    { 'program_id': 14, 'seq':  4, 'course': 'SPCH 125' },
    { 'program_id': 14, 'seq':  5, 'course': 'MATH 115' },
    { 'program_id': 14, 'seq':  6, 'course': 'ENHS 300' },
    { 'program_id': 14, 'seq':  7, 'course': 'WRTG 112' },
    { 'program_id': 14, 'seq':  8, 'course': 'CHEM 297' },
    { 'program_id': 14, 'seq':  9, 'course': 'DATA 200' },
    { 'program_id': 14, 'seq': 10, 'course': 'ENHS 305' },
    { 'program_id': 14, 'seq': 11, 'course': 'HUMN 100' },
    { 'program_id': 14, 'seq': 12, 'course': 'BIOL 103' },
    { 'program_id': 14, 'seq': 13, 'course': 'PSYC 100' },
    { 'program_id': 14, 'seq': 14, 'course': 'ARTT 152' },
    { 'program_id': 14, 'seq': 15, 'course': 'ECON 103' },
    { 'program_id': 14, 'seq': 16, 'course': 'ENHS 310' },
    { 'program_id': 14, 'seq': 17, 'course': 'ELECTIVE' },
    { 'program_id': 14, 'seq': 18, 'course': 'ENHS 315' },
    { 'program_id': 14, 'seq': 19, 'course': 'ELECTIVE' },
    { 'program_id': 14, 'seq': 20, 'course': 'ENHS 320' },
    { 'program_id': 14, 'seq': 21, 'course': 'ELECTIVE' },
    { 'program_id': 14, 'seq': 22, 'course': 'ENHS 325' },
    { 'program_id': 14, 'seq': 23, 'course': 'WRTG 393' },
    { 'program_id': 14, 'seq': 24, 'course': 'ELECTIVE' },
    { 'program_id': 14, 'seq': 25, 'course': 'ENHS 330' },
    { 'program_id': 14, 'seq': 26, 'course': 'ELECTIVE' },
    { 'program_id': 14, 'seq': 27, 'course': 'ELECTIVE' },
    { 'program_id': 14, 'seq': 28, 'course': 'ENHS 335' },
    { 'program_id': 14, 'seq': 29, 'course': 'ELECTIVE' },
    { 'program_id': 14, 'seq': 30, 'course': 'ELECTIVE' },
    { 'program_id': 14, 'seq': 31, 'course': 'ENHS 340' },
    { 'program_id': 14, 'seq': 32, 'course': 'ELECTIVE' },
    { 'program_id': 14, 'seq': 33, 'course': 'ELECTIVE' },
    { 'program_id': 14, 'seq': 34, 'course': 'ENHS 400' },
    { 'program_id': 14, 'seq': 35, 'course': 'ELECTIVE' },
    { 'program_id': 14, 'seq': 36, 'course': 'ELECTIVE' },
    { 'program_id': 14, 'seq': 37, 'course': 'ENHS 405' },
    { 'program_id': 14, 'seq': 38, 'course': 'ELECTIVE' },
    { 'program_id': 14, 'seq': 39, 'course': 'ELECTIVE' },
    { 'program_id': 14, 'seq': 40, 'course': 'ELECTIVE' },
    { 'program_id': 14, 'seq': 41, 'course': 'ENHS 495' },
    { 'program_id': 14, 'seq': 42, 'course': 'CAPL 398A' }
]

catalog_programs_add_15 = [
    { 'program_id': 15, 'seq':  1, 'course': 'LIBS 150' },
    { 'program_id': 15, 'seq':  2, 'course': 'PACE 111B' },
    { 'program_id': 15, 'seq':  3, 'course': 'WRTG 111' },
    { 'program_id': 15, 'seq':  4, 'course': 'IFSM 201' },
    { 'program_id': 15, 'seq':  5, 'course': 'NUTR 100' },
    { 'program_id': 15, 'seq':  6, 'course': 'NUTR 101' },
    { 'program_id': 15, 'seq':  7, 'course': 'BMGT 364' },
    { 'program_id': 15, 'seq':  8, 'course': 'WRTG 112' },
    { 'program_id': 15, 'seq':  9, 'course': 'STAT 200' },
    { 'program_id': 15, 'seq': 10, 'course': 'WRTG 293' },
    { 'program_id': 15, 'seq': 11, 'course': 'ACCT 220' },
    { 'program_id': 15, 'seq': 12, 'course': 'HIST 125' },
    { 'program_id': 15, 'seq': 13, 'course': 'NSCI 100' },
    { 'program_id': 15, 'seq': 14, 'course': 'ECON 201' },
    { 'program_id': 15, 'seq': 15, 'course': 'ARTH 334' },
    { 'program_id': 15, 'seq': 16, 'course': 'DATA 200' },
    { 'program_id': 15, 'seq': 17, 'course': 'ECON 203' },
    { 'program_id': 15, 'seq': 18, 'course': 'ACCT 221' },
    { 'program_id': 15, 'seq': 19, 'course': 'IFSM 330' },
    { 'program_id': 15, 'seq': 20, 'course': 'FINC 330' },
    { 'program_id': 15, 'seq': 21, 'course': 'FINC 335' },
    { 'program_id': 15, 'seq': 22, 'course': 'FINC 340' },
    { 'program_id': 15, 'seq': 23, 'course': 'DATA 320' },
    { 'program_id': 15, 'seq': 24, 'course': 'FINC 351' },
    { 'program_id': 15, 'seq': 25, 'course': 'WRTG 394' },
    { 'program_id': 15, 'seq': 26, 'course': 'DATA 335' },
    { 'program_id': 15, 'seq': 27, 'course': 'FINC 421' },
    { 'program_id': 15, 'seq': 28, 'course': 'DATA 300' },
    { 'program_id': 15, 'seq': 29, 'course': 'ELECTIVE' },
    { 'program_id': 15, 'seq': 30, 'course': 'FINC 430' },
    { 'program_id': 15, 'seq': 31, 'course': 'ELECTIVE' },
    { 'program_id': 15, 'seq': 32, 'course': 'ELECTIVE' },
    { 'program_id': 15, 'seq': 33, 'course': 'FINC 440' },
    { 'program_id': 15, 'seq': 34, 'course': 'ELECTIVE' },
    { 'program_id': 15, 'seq': 35, 'course': 'ELECTIVE' },
    { 'program_id': 15, 'seq': 36, 'course': 'FINC 460' },
    { 'program_id': 15, 'seq': 37, 'course': 'ELECTIVE' },
    { 'program_id': 15, 'seq': 38, 'course': 'ELECTIVE' },
    { 'program_id': 15, 'seq': 39, 'course': 'ECON 430' },
    { 'program_id': 15, 'seq': 40, 'course': 'ELECTIVE' },
    { 'program_id': 15, 'seq': 41, 'course': 'FINC 495' },
    { 'program_id': 15, 'seq': 42, 'course': 'CAPL 398A' }
]

catalog_programs_add_17 = [
    { 'program_id': 17, 'seq':  1, 'course': 'LIBS 150' },
    { 'program_id': 17, 'seq':  2, 'course': 'PACE 111S' },
    { 'program_id': 17, 'seq':  3, 'course': 'WRTG 111' },
    { 'program_id': 17, 'seq':  4, 'course': 'IFSM 201' },
    { 'program_id': 17, 'seq':  5, 'course': 'NUTR 100' },
    { 'program_id': 17, 'seq':  6, 'course': 'GERO 100' },
    { 'program_id': 17, 'seq':  7, 'course': 'SPCH 100' },
    { 'program_id': 17, 'seq':  8, 'course': 'STAT 200' },
    { 'program_id': 17, 'seq':  9, 'course': 'WRTG 112' },
    { 'program_id': 17, 'seq': 10, 'course': 'GERO 301' },
    { 'program_id': 17, 'seq': 11, 'course': 'HUMN 100' },
    { 'program_id': 17, 'seq': 12, 'course': 'BIOL 103' },
    { 'program_id': 17, 'seq': 13, 'course': 'BEHS 103' },
    { 'program_id': 17, 'seq': 14, 'course': 'ARTH 334' },
    { 'program_id': 17, 'seq': 15, 'course': 'ELECTIVE' },
    { 'program_id': 17, 'seq': 16, 'course': 'ECON 103' },
    { 'program_id': 17, 'seq': 17, 'course': 'GERO 302' },
    { 'program_id': 17, 'seq': 18, 'course': 'ELECTIVE' },
    { 'program_id': 17, 'seq': 19, 'course': 'GERO 306' },
    { 'program_id': 17, 'seq': 20, 'course': 'ELECTIVE' },
    { 'program_id': 17, 'seq': 21, 'course': 'GERO 311' },
    { 'program_id': 17, 'seq': 22, 'course': 'ELECTIVE' },
    { 'program_id': 17, 'seq': 23, 'course': 'GERO 320' },
    { 'program_id': 17, 'seq': 24, 'course': 'WRTG 391' },
    { 'program_id': 17, 'seq': 25, 'course': 'ELECTIVE' },
    { 'program_id': 17, 'seq': 26, 'course': 'GERO 338' },
    { 'program_id': 17, 'seq': 27, 'course': 'ELECTIVE' },
    { 'program_id': 17, 'seq': 28, 'course': 'ELECTIVE' },
    { 'program_id': 17, 'seq': 29, 'course': 'GERO 342' },
    { 'program_id': 17, 'seq': 30, 'course': 'ELECTIVE' },
    { 'program_id': 17, 'seq': 31, 'course': 'ELECTIVE' },
    { 'program_id': 17, 'seq': 32, 'course': 'GERO 390' },
    { 'program_id': 17, 'seq': 33, 'course': 'ELECTIVE' },
    { 'program_id': 17, 'seq': 34, 'course': 'ELECTIVE' },
    { 'program_id': 17, 'seq': 35, 'course': 'GERO 427' },
    { 'program_id': 17, 'seq': 36, 'course': 'ELECTIVE' },
    { 'program_id': 17, 'seq': 37, 'course': 'ELECTIVE' },
    { 'program_id': 17, 'seq': 38, 'course': 'ELECTIVE' },
    { 'program_id': 17, 'seq': 39, 'course': 'ELECTIVE' },
    { 'program_id': 17, 'seq': 40, 'course': 'GERO 486A' },
    { 'program_id': 17, 'seq': 41, 'course': 'CAPL 398A' }
]

catalog_programs_add_18 = [
    { 'program_id': 18, 'seq':  1, 'course': 'LIBS 150' },
    { 'program_id': 18, 'seq':  2, 'course': 'PACE 111C' },
    { 'program_id': 18, 'seq':  3, 'course': 'WRTG 111' },
    { 'program_id': 18, 'seq':  4, 'course': 'CMST 301' },
    { 'program_id': 18, 'seq':  5, 'course': 'NUTR 100' },
    { 'program_id': 18, 'seq':  6, 'course': 'GRCO 100' },
    { 'program_id': 18, 'seq':  7, 'course': 'SPCH 100' },
    { 'program_id': 18, 'seq':  8, 'course': 'MATH 105' },
    { 'program_id': 18, 'seq':  9, 'course': 'WRTG 112' },
    { 'program_id': 18, 'seq': 10, 'course': 'ARTT 110' },
    { 'program_id': 18, 'seq': 11, 'course': 'HUMN 100' },
    { 'program_id': 18, 'seq': 12, 'course': 'BIOL 103' },
    { 'program_id': 18, 'seq': 13, 'course': 'BEHS 103' },
    { 'program_id': 18, 'seq': 14, 'course': 'ARTH 375' },
    { 'program_id': 18, 'seq': 15, 'course': 'ELECTIVE' },
    { 'program_id': 18, 'seq': 16, 'course': 'ECON 103' },
    { 'program_id': 18, 'seq': 17, 'course': 'ARTT 120' },
    { 'program_id': 18, 'seq': 18, 'course': 'ELECTIVE' },
    { 'program_id': 18, 'seq': 19, 'course': 'ARTT 210' },
    { 'program_id': 18, 'seq': 20, 'course': 'ELECTIVE' },
    { 'program_id': 18, 'seq': 21, 'course': 'GRCO 230' },
    { 'program_id': 18, 'seq': 22, 'course': 'ELECTIVE' },
    { 'program_id': 18, 'seq': 23, 'course': 'GRCO 350' },
    { 'program_id': 18, 'seq': 24, 'course': 'WRTG 391' },
    { 'program_id': 18, 'seq': 25, 'course': 'ELECTIVE' },
    { 'program_id': 18, 'seq': 26, 'course': 'GRCO 354' },
    { 'program_id': 18, 'seq': 27, 'course': 'ELECTIVE' },
    { 'program_id': 18, 'seq': 28, 'course': 'ELECTIVE' },
    { 'program_id': 18, 'seq': 29, 'course': 'GRCO 355' },
    { 'program_id': 18, 'seq': 30, 'course': 'ELECTIVE' },
    { 'program_id': 18, 'seq': 31, 'course': 'ELECTIVE' },
    { 'program_id': 18, 'seq': 32, 'course': 'GRCO 450' },
    { 'program_id': 18, 'seq': 33, 'course': 'ELECTIVE' },
    { 'program_id': 18, 'seq': 34, 'course': 'ELECTIVE' },
    { 'program_id': 18, 'seq': 35, 'course': 'GRCO 479' },
    { 'program_id': 18, 'seq': 36, 'course': 'ELECTIVE' },
    { 'program_id': 18, 'seq': 37, 'course': 'ELECTIVE' },
    { 'program_id': 18, 'seq': 38, 'course': 'ELECTIVE' },
    { 'program_id': 18, 'seq': 39, 'course': 'ELECTIVE' },
    { 'program_id': 18, 'seq': 40, 'course': 'GRCO 495' },
    { 'program_id': 18, 'seq': 41, 'course': 'CAPL 398A' }
]

catalog_programs_add_19 = [
    { 'program_id': 19, 'seq':  1, 'course': 'LIBS 150' },
    { 'program_id': 19, 'seq':  2, 'course': 'PACE 111S' },
    { 'program_id': 19, 'seq':  3, 'course': 'WRTG 111' },
    { 'program_id': 19, 'seq':  4, 'course': 'IFSM 305' },
    { 'program_id': 19, 'seq':  5, 'course': 'WRTG 112' },
    { 'program_id': 19, 'seq':  6, 'course': 'HMGT 300' },
    { 'program_id': 19, 'seq':  7, 'course': 'SPCH 100' },
    { 'program_id': 19, 'seq':  8, 'course': 'STAT 200' },
    { 'program_id': 19, 'seq':  9, 'course': 'NUTR 100' },
    { 'program_id': 19, 'seq': 10, 'course': 'HMGT 307' },
    { 'program_id': 19, 'seq': 11, 'course': 'HUMN 100' },
    { 'program_id': 19, 'seq': 12, 'course': 'BIOL 103' },
    { 'program_id': 19, 'seq': 13, 'course': 'BEHS 103' },
    { 'program_id': 19, 'seq': 14, 'course': 'ARTH 334' },
    { 'program_id': 19, 'seq': 15, 'course': 'ECON 103' },
    { 'program_id': 19, 'seq': 16, 'course': 'HMGT 310' },
    { 'program_id': 19, 'seq': 17, 'course': 'HRMN 300' },
    { 'program_id': 19, 'seq': 18, 'course': 'HMGT 320' },
    { 'program_id': 19, 'seq': 19, 'course': 'ELECTIVE' },
    { 'program_id': 19, 'seq': 20, 'course': 'HMGT 322' },
    { 'program_id': 19, 'seq': 21, 'course': 'GERO 427' },
    { 'program_id': 19, 'seq': 22, 'course': 'HMGT 335' },
    { 'program_id': 19, 'seq': 23, 'course': 'WRTG 394' },
    { 'program_id': 19, 'seq': 24, 'course': 'ELECTIVE' },
    { 'program_id': 19, 'seq': 25, 'course': 'HMGT 372' },
    { 'program_id': 19, 'seq': 26, 'course': 'EMGT 302' },
    { 'program_id': 19, 'seq': 27, 'course': 'ELECTIVE' },
    { 'program_id': 19, 'seq': 28, 'course': 'HMGT 400' },
    { 'program_id': 19, 'seq': 29, 'course': 'COMM 300' },
    { 'program_id': 19, 'seq': 30, 'course': 'ELECTIVE' },
    { 'program_id': 19, 'seq': 31, 'course': 'HMGT 420' },
    { 'program_id': 19, 'seq': 32, 'course': 'CSIA 300' },
    { 'program_id': 19, 'seq': 33, 'course': 'ELECTIVE' },
    { 'program_id': 19, 'seq': 34, 'course': 'HMGT 435' },
    { 'program_id': 19, 'seq': 35, 'course': 'ELECTIVE' },
    { 'program_id': 19, 'seq': 36, 'course': 'BMGT 317' },
    { 'program_id': 19, 'seq': 37, 'course': 'ELECTIVE' },
    { 'program_id': 19, 'seq': 38, 'course': 'ELECTIVE' },
    { 'program_id': 19, 'seq': 39, 'course': 'BEHS 380' },
    { 'program_id': 19, 'seq': 40, 'course': 'HMGT 495' },
    { 'program_id': 19, 'seq': 41, 'course': 'CAPL 398A' }
]

catalog_programs_add_20 = [
    { 'program_id': 20, 'seq':  1, 'course': 'LIBS 150' },
    { 'program_id': 20, 'seq':  2, 'course': 'PACE 111C' },
    { 'program_id': 20, 'seq':  3, 'course': 'WRTG 111' },
    { 'program_id': 20, 'seq':  4, 'course': 'CMST 301' },
    { 'program_id': 20, 'seq':  5, 'course': 'NUTR 100' },
    { 'program_id': 20, 'seq':  6, 'course': 'NUTR 101' },
    { 'program_id': 20, 'seq':  7, 'course': 'HIST 115' },
    { 'program_id': 20, 'seq':  8, 'course': 'SPCH 100' },
    { 'program_id': 20, 'seq':  9, 'course': 'MATH 105' },
    { 'program_id': 20, 'seq': 10, 'course': 'WRTG 112' },
    { 'program_id': 20, 'seq': 11, 'course': 'HIST 116' },
    { 'program_id': 20, 'seq': 12, 'course': 'HUMN 100' },
    { 'program_id': 20, 'seq': 13, 'course': 'GEOL 100' },
    { 'program_id': 20, 'seq': 14, 'course': 'BEHS 103' },
    { 'program_id': 20, 'seq': 15, 'course': 'HIST 125' },
    { 'program_id': 20, 'seq': 16, 'course': 'ELECTIVE' },
    { 'program_id': 20, 'seq': 17, 'course': 'ECON 103' },
    { 'program_id': 20, 'seq': 18, 'course': 'HIST 156' },
    { 'program_id': 20, 'seq': 19, 'course': 'ELECTIVE' },
    { 'program_id': 20, 'seq': 20, 'course': 'HIST 157' },
    { 'program_id': 20, 'seq': 21, 'course': 'ELECTIVE' },
    { 'program_id': 20, 'seq': 22, 'course': 'HIST 289' },
    { 'program_id': 20, 'seq': 23, 'course': 'ELECTIVE' },
    { 'program_id': 20, 'seq': 24, 'course': 'HIST 309' },
    { 'program_id': 20, 'seq': 25, 'course': 'WRTG 391' },
    { 'program_id': 20, 'seq': 26, 'course': 'ELECTIVE' },
    { 'program_id': 20, 'seq': 27, 'course': 'HIST 316L|HIST 326' },
    { 'program_id': 20, 'seq': 28, 'course': 'ELECTIVE' },
    { 'program_id': 20, 'seq': 29, 'course': 'ELECTIVE' },
    { 'program_id': 20, 'seq': 30, 'course': 'HIST 365|HIST 337' },
    { 'program_id': 20, 'seq': 31, 'course': 'ELECTIVE' },
    { 'program_id': 20, 'seq': 32, 'course': 'ELECTIVE' },
    { 'program_id': 20, 'seq': 33, 'course': 'HIST 377|HIST 392' },
    { 'program_id': 20, 'seq': 34, 'course': 'ELECTIVE' },
    { 'program_id': 20, 'seq': 35, 'course': 'ELECTIVE' },
    { 'program_id': 20, 'seq': 36, 'course': 'HIST 461|HIST 480' },
    { 'program_id': 20, 'seq': 37, 'course': 'ELECTIVE' },
    { 'program_id': 20, 'seq': 38, 'course': 'ELECTIVE' },
    { 'program_id': 20, 'seq': 39, 'course': 'ELECTIVE' },
    { 'program_id': 20, 'seq': 40, 'course': 'ELECTIVE' },
    { 'program_id': 20, 'seq': 41, 'course': 'HIST 495' },
    { 'program_id': 20, 'seq': 42, 'course': 'CAPL 398A' }
]

catalog_programs_add_21 = [
    { 'program_id': 21, 'seq':  1, 'course': 'LIBS 150' },
    { 'program_id': 21, 'seq':  2, 'course': 'PACE 111P' },
    { 'program_id': 21, 'seq':  3, 'course': 'WRTG 111' },
    { 'program_id': 21, 'seq':  4, 'course': 'WRTG 112' },
    { 'program_id': 21, 'seq':  5, 'course': 'NUTR 100' },
    { 'program_id': 21, 'seq':  6, 'course': 'HMLS 302' },
    { 'program_id': 21, 'seq':  7, 'course': 'SPCH 100' },
    { 'program_id': 21, 'seq':  8, 'course': 'MATH 105' },
    { 'program_id': 21, 'seq':  9, 'course': 'IFSM 300' },
    { 'program_id': 21, 'seq': 10, 'course': 'HMLS 406' },
    { 'program_id': 21, 'seq': 11, 'course': 'HUMN 100' },
    { 'program_id': 21, 'seq': 12, 'course': 'BIOL 103' },
    { 'program_id': 21, 'seq': 13, 'course': 'BEHS 103' },
    { 'program_id': 21, 'seq': 14, 'course': 'ARTH 334' },
    { 'program_id': 21, 'seq': 15, 'course': 'ELECTIVE' },
    { 'program_id': 21, 'seq': 16, 'course': 'ECON 103' },
    { 'program_id': 21, 'seq': 17, 'course': 'HMLS 310' },
    { 'program_id': 21, 'seq': 18, 'course': 'ELECTIVE' },
    { 'program_id': 21, 'seq': 19, 'course': 'HMLS 408' },
    { 'program_id': 21, 'seq': 20, 'course': 'ELECTIVE' },
    { 'program_id': 21, 'seq': 21, 'course': 'HMLS 414' },
    { 'program_id': 21, 'seq': 22, 'course': 'ELECTIVE' },
    { 'program_id': 21, 'seq': 23, 'course': 'HMLS 416' },
    { 'program_id': 21, 'seq': 24, 'course': 'WRTG 391' },
    { 'program_id': 21, 'seq': 25, 'course': 'ELECTIVE' },
    { 'program_id': 21, 'seq': 26, 'course': 'PSAD 410' },
    { 'program_id': 21, 'seq': 27, 'course': 'ELECTIVE' },
    { 'program_id': 21, 'seq': 28, 'course': 'ELECTIVE' },
    { 'program_id': 21, 'seq': 29, 'course': 'PSAD 414' },
    { 'program_id': 21, 'seq': 30, 'course': 'ELECTIVE' },
    { 'program_id': 21, 'seq': 31, 'course': 'ELECTIVE' },
    { 'program_id': 21, 'seq': 32, 'course': 'PSAD 416' },
    { 'program_id': 21, 'seq': 33, 'course': 'ELECTIVE' },
    { 'program_id': 21, 'seq': 34, 'course': 'ELECTIVE' },
    { 'program_id': 21, 'seq': 35, 'course': 'HMLS 304' },
    { 'program_id': 21, 'seq': 36, 'course': 'ELECTIVE' },
    { 'program_id': 21, 'seq': 37, 'course': 'ELECTIVE' },
    { 'program_id': 21, 'seq': 38, 'course': 'ELECTIVE' },
    { 'program_id': 21, 'seq': 39, 'course': 'ELECTIVE' },
    { 'program_id': 21, 'seq': 40, 'course': 'HMLS 495' },
    { 'program_id': 21, 'seq': 41, 'course': 'CAPL 398A' }
]

catalog_programs_add_22 = [
    { 'program_id': 22, 'seq':  1, 'course': 'LIBS 150' },
    { 'program_id': 22, 'seq':  2, 'course': 'PACE 111B' },
    { 'program_id': 22, 'seq':  3, 'course': 'WRTG 111' },
    { 'program_id': 22, 'seq':  4, 'course': 'WRTG 112' },
    { 'program_id': 22, 'seq':  5, 'course': 'NUTR 100' },
    { 'program_id': 22, 'seq':  6, 'course': 'HRMN 300' },
    { 'program_id': 22, 'seq':  7, 'course': 'SPCH 100' },
    { 'program_id': 22, 'seq':  8, 'course': 'MATH 105' },
    { 'program_id': 22, 'seq':  9, 'course': 'IFSM 300' },
    { 'program_id': 22, 'seq': 10, 'course': 'HRMN 302' },
    { 'program_id': 22, 'seq': 11, 'course': 'HUMN 100' },
    { 'program_id': 22, 'seq': 12, 'course': 'BIOL 103' },
    { 'program_id': 22, 'seq': 13, 'course': 'BEHS 103' },
    { 'program_id': 22, 'seq': 14, 'course': 'ARTH 334' },
    { 'program_id': 22, 'seq': 15, 'course': 'ELECTIVE' },
    { 'program_id': 22, 'seq': 16, 'course': 'ECON 103' },
    { 'program_id': 22, 'seq': 17, 'course': 'HRMN 362' },
    { 'program_id': 22, 'seq': 18, 'course': 'ELECTIVE' },
    { 'program_id': 22, 'seq': 19, 'course': 'HRMN 367' },
    { 'program_id': 22, 'seq': 20, 'course': 'ELECTIVE' },
    { 'program_id': 22, 'seq': 21, 'course': 'HRMN 395' },
    { 'program_id': 22, 'seq': 22, 'course': 'ELECTIVE' },
    { 'program_id': 22, 'seq': 23, 'course': 'HRMN 400' },
    { 'program_id': 22, 'seq': 24, 'course': 'WRTG 394' },
    { 'program_id': 22, 'seq': 25, 'course': 'ELECTIVE ' },
    { 'program_id': 22, 'seq': 26, 'course': 'HRMN 406|HRMN 410' },
    { 'program_id': 22, 'seq': 27, 'course': 'ELECTIVE' },
    { 'program_id': 22, 'seq': 28, 'course': 'ELECTIVE' },
    { 'program_id': 22, 'seq': 29, 'course': 'BMGT 364' },
    { 'program_id': 22, 'seq': 30, 'course': 'ELECTIVE' },
    { 'program_id': 22, 'seq': 31, 'course': 'ELECTIVE' },
    { 'program_id': 22, 'seq': 32, 'course': 'FINC 331' },
    { 'program_id': 22, 'seq': 33, 'course': 'ELECTIVE' },
    { 'program_id': 22, 'seq': 34, 'course': 'ELECTIVE' },
    { 'program_id': 22, 'seq': 35, 'course': 'HRMN 408' },
    { 'program_id': 22, 'seq': 36, 'course': 'ELECTIVE' },
    { 'program_id': 22, 'seq': 37, 'course': 'ELECTIVE' },
    { 'program_id': 22, 'seq': 38, 'course': 'HRMN 467' },
    { 'program_id': 22, 'seq': 39, 'course': 'ELECTIVE' },
    { 'program_id': 22, 'seq': 40, 'course': 'HRMN 495' },
    { 'program_id': 22, 'seq': 41, 'course': 'CAPL 398A' }
]

catalog_programs_add_23 = [
    { 'program_id': 23, 'seq':  1, 'course': 'LIBS 150' },
    { 'program_id': 23, 'seq':  2, 'course': 'PACE 111C' },
    { 'program_id': 23, 'seq':  3, 'course': 'WRTG 111' },
    { 'program_id': 23, 'seq':  4, 'course': 'CMST 301' },
    { 'program_id': 23, 'seq':  5, 'course': 'NUTR 100' },
    { 'program_id': 23, 'seq':  6, 'course': 'HUMN 100' },
    { 'program_id': 23, 'seq':  7, 'course': 'SPCH 100' },
    { 'program_id': 23, 'seq':  8, 'course': 'MATH 105' },
    { 'program_id': 23, 'seq':  9, 'course': 'WRTG 112' },
    { 'program_id': 23, 'seq': 10, 'course': 'PHIL 100' },
    { 'program_id': 23, 'seq': 11, 'course': 'ENGL 240' },
    { 'program_id': 23, 'seq': 12, 'course': 'BIOL 103' },
    { 'program_id': 23, 'seq': 13, 'course': 'BEHS 103' },
    { 'program_id': 23, 'seq': 14, 'course': 'ARTH 334' },
    { 'program_id': 23, 'seq': 15, 'course': 'ELECTIVE' },
    { 'program_id': 23, 'seq': 16, 'course': 'ECON 103' },
    { 'program_id': 23, 'seq': 17, 'course': 'PHIL 140' },
    { 'program_id': 23, 'seq': 18, 'course': 'ELECTIVE' },
    { 'program_id': 23, 'seq': 19, 'course': 'HIST 115' },
    { 'program_id': 23, 'seq': 20, 'course': 'ELECTIVE' },
    { 'program_id': 23, 'seq': 21, 'course': 'MUSC 210' },
    { 'program_id': 23, 'seq': 22, 'course': 'ELECTIVE' },
    { 'program_id': 23, 'seq': 23, 'course': 'ARTH 372' },
    { 'program_id': 23, 'seq': 24, 'course': 'WRTG 391' },
    { 'program_id': 23, 'seq': 25, 'course': 'ELECTIVE' },
    { 'program_id': 23, 'seq': 26, 'course': 'PHIL 304' },
    { 'program_id': 23, 'seq': 27, 'course': 'ELECTIVE' },
    { 'program_id': 23, 'seq': 28, 'course': 'ELECTIVE' },
    { 'program_id': 23, 'seq': 29, 'course': 'HUMN 351' },
    { 'program_id': 23, 'seq': 30, 'course': 'ELECTIVE' },
    { 'program_id': 23, 'seq': 31, 'course': 'ELECTIVE' },
    { 'program_id': 23, 'seq': 32, 'course': 'PHIL 349' },
    { 'program_id': 23, 'seq': 33, 'course': 'ELECTIVE' },
    { 'program_id': 23, 'seq': 34, 'course': 'ELECTIVE' },
    { 'program_id': 23, 'seq': 35, 'course': 'ENGL 406' },
    { 'program_id': 23, 'seq': 36, 'course': 'ELECTIVE' },
    { 'program_id': 23, 'seq': 37, 'course': 'ELECTIVE' },
    { 'program_id': 23, 'seq': 38, 'course': 'ELECTIVE' },
    { 'program_id': 23, 'seq': 39, 'course': 'ELECTIVE' },
    { 'program_id': 23, 'seq': 40, 'course': 'HUMN 495' },
    { 'program_id': 23, 'seq': 41, 'course': 'CAPL 398A' }
]

catalog_programs_add_25 = [
    { 'program_id': 25, 'seq':  1, 'course': 'LIBS 150' },
    { 'program_id': 25, 'seq':  2, 'course': 'PACE 111P' },
    { 'program_id': 25, 'seq':  3, 'course': 'WRTG 111' },
    { 'program_id': 25, 'seq':  4, 'course': 'CMSC 100' },
    { 'program_id': 25, 'seq':  5, 'course': 'NUTR 100' },
    { 'program_id': 25, 'seq':  6, 'course': 'LGST 101' },
    { 'program_id': 25, 'seq':  7, 'course': 'SPCH 100' },
    { 'program_id': 25, 'seq':  8, 'course': 'MATH 105' },
    { 'program_id': 25, 'seq':  9, 'course': 'WRTG 112' },
    { 'program_id': 25, 'seq': 10, 'course': 'LGST 200' },
    { 'program_id': 25, 'seq': 11, 'course': 'HUMN 100' },
    { 'program_id': 25, 'seq': 12, 'course': 'BIOL 103' },
    { 'program_id': 25, 'seq': 13, 'course': 'BEHS 103' },
    { 'program_id': 25, 'seq': 14, 'course': 'ARTH 334' },
    { 'program_id': 25, 'seq': 15, 'course': 'ELECTIVE' },
    { 'program_id': 25, 'seq': 16, 'course': 'ECON 103' },
    { 'program_id': 25, 'seq': 17, 'course': 'LGST 201' },
    { 'program_id': 25, 'seq': 18, 'course': 'ELECTIVE' },
    { 'program_id': 25, 'seq': 19, 'course': 'LGST 204' },
    { 'program_id': 25, 'seq': 20, 'course': 'ELECTIVE' },
    { 'program_id': 25, 'seq': 21, 'course': 'LGST 301' },
    { 'program_id': 25, 'seq': 22, 'course': 'ELECTIVE' },
    { 'program_id': 25, 'seq': 23, 'course': 'LGST 312' },
    { 'program_id': 25, 'seq': 24, 'course': 'WRTG 394' },
    { 'program_id': 25, 'seq': 25, 'course': 'ELECTIVE' },
    { 'program_id': 25, 'seq': 26, 'course': 'LGST 315' },
    { 'program_id': 25, 'seq': 27, 'course': 'ELECTIVE' },
    { 'program_id': 25, 'seq': 28, 'course': 'ELECTIVE' },
    { 'program_id': 25, 'seq': 29, 'course': 'LGST 320' },
    { 'program_id': 25, 'seq': 30, 'course': 'ELECTIVE' },
    { 'program_id': 25, 'seq': 31, 'course': 'ELECTIVE' },
    { 'program_id': 25, 'seq': 32, 'course': 'LGST 325' },
    { 'program_id': 25, 'seq': 33, 'course': 'ELECTIVE' },
    { 'program_id': 25, 'seq': 34, 'course': 'ELECTIVE' },
    { 'program_id': 25, 'seq': 35, 'course': 'LGST 340' },
    { 'program_id': 25, 'seq': 36, 'course': 'ELECTIVE' },
    { 'program_id': 25, 'seq': 37, 'course': 'ELECTIVE' },
    { 'program_id': 25, 'seq': 38, 'course': 'ELECTIVE' },
    { 'program_id': 25, 'seq': 39, 'course': 'ELECTIVE' },
    { 'program_id': 25, 'seq': 40, 'course': 'LGST 495' },
    { 'program_id': 25, 'seq': 41, 'course': 'CAPL 398A' }
]

catalog_programs_add_26 = [
    { 'program_id': 26, 'seq':  1, 'course': 'LIBS 150' },
    { 'program_id': 26, 'seq':  2, 'course': 'PACE 111T' },
    { 'program_id': 26, 'seq':  3, 'course': 'WRTG 111' },
    { 'program_id': 26, 'seq':  4, 'course': 'WRTG 112' },
    { 'program_id': 26, 'seq':  5, 'course': 'NUTR 100' },
    { 'program_id': 26, 'seq':  6, 'course': 'IFSM 300' },
    { 'program_id': 26, 'seq':  7, 'course': 'SPCH 100' },
    { 'program_id': 26, 'seq':  8, 'course': 'STAT 200' },
    { 'program_id': 26, 'seq':  9, 'course': 'CMSC 105' },
    { 'program_id': 26, 'seq': 10, 'course': 'IFSM 301' },
    { 'program_id': 26, 'seq': 11, 'course': 'HIST 125' },
    { 'program_id': 26, 'seq': 12, 'course': 'BIOL 103' },
    { 'program_id': 26, 'seq': 13, 'course': 'BEHS 103' },
    { 'program_id': 26, 'seq': 14, 'course': 'ARTH 334' },
    { 'program_id': 26, 'seq': 15, 'course': 'ELECTIVE' },
    { 'program_id': 26, 'seq': 16, 'course': 'ECON 103' },
    { 'program_id': 26, 'seq': 17, 'course': 'IFSM 304' },
    { 'program_id': 26, 'seq': 18, 'course': 'ELECTIVE' },
    { 'program_id': 26, 'seq': 19, 'course': 'CSIA 300' },
    { 'program_id': 26, 'seq': 20, 'course': 'ELECTIVE' },
    { 'program_id': 26, 'seq': 21, 'course': 'ELECTIVE' },
    { 'program_id': 26, 'seq': 22, 'course': 'ELECTIVE' },
    { 'program_id': 26, 'seq': 23, 'course': 'IFSM 310' },
    { 'program_id': 26, 'seq': 24, 'course': 'WRTG 393' },
    { 'program_id': 26, 'seq': 25, 'course': 'ELECTIVE' },
    { 'program_id': 26, 'seq': 26, 'course': 'IFSM 330' },
    { 'program_id': 26, 'seq': 27, 'course': 'ELECTIVE' },
    { 'program_id': 26, 'seq': 28, 'course': 'ELECTIVE' },
    { 'program_id': 26, 'seq': 29, 'course': 'IFSM 311' },
    { 'program_id': 26, 'seq': 30, 'course': 'ELECTIVE' },
    { 'program_id': 26, 'seq': 31, 'course': 'ELECTIVE' },
    { 'program_id': 26, 'seq': 32, 'course': 'IFSM 370' },
    { 'program_id': 26, 'seq': 33, 'course': 'ELECTIVE' },
    { 'program_id': 26, 'seq': 34, 'course': 'ELECTIVE' },
    { 'program_id': 26, 'seq': 35, 'course': 'IFSM 438' },
    { 'program_id': 26, 'seq': 36, 'course': 'ELECTIVE' },
    { 'program_id': 26, 'seq': 37, 'course': 'IFSM 461' },
    { 'program_id': 26, 'seq': 38, 'course': 'ELECTIVE' },
    { 'program_id': 26, 'seq': 39, 'course': 'ELECTIVE' },
    { 'program_id': 26, 'seq': 40, 'course': 'IFSM 495' },
    { 'program_id': 26, 'seq': 41, 'course': 'CAPL 398A' }
]

catalog_programs_add_27 = [
    { 'program_id': 27, 'seq':  1, 'course': 'LIBS 150' },
    { 'program_id': 27, 'seq':  2, 'course': 'PACE 111B' },
    { 'program_id': 27, 'seq':  3, 'course': 'WRTG 111' },
    { 'program_id': 27, 'seq':  4, 'course': 'WRTG 112' },
    { 'program_id': 27, 'seq':  5, 'course': 'NUTR 100' },
    { 'program_id': 27, 'seq':  6, 'course': 'BMGT 160' },
    { 'program_id': 27, 'seq':  7, 'course': 'COMM 390' },
    { 'program_id': 27, 'seq':  8, 'course': 'STAT 200' },
    { 'program_id': 27, 'seq':  9, 'course': 'IFSM 300' },
    { 'program_id': 27, 'seq': 10, 'course': 'ACCT 301' },
    { 'program_id': 27, 'seq': 11, 'course': 'HUMN 100' },
    { 'program_id': 27, 'seq': 12, 'course': 'BIOL 103' },
    { 'program_id': 27, 'seq': 13, 'course': 'BEHS 103' },
    { 'program_id': 27, 'seq': 14, 'course': 'ARTH 334' },
    { 'program_id': 27, 'seq': 15, 'course': 'ELECTIVE' },
    { 'program_id': 27, 'seq': 16, 'course': 'ECON 201' },
    { 'program_id': 27, 'seq': 17, 'course': 'BMGT 364' },
    { 'program_id': 27, 'seq': 18, 'course': 'ELECTIVE' },
    { 'program_id': 27, 'seq': 19, 'course': 'BMGT 365' },
    { 'program_id': 27, 'seq': 20, 'course': 'ELECTIVE' },
    { 'program_id': 27, 'seq': 21, 'course': 'BMGT 304' },
    { 'program_id': 27, 'seq': 22, 'course': 'ELECTIVE' },
    { 'program_id': 27, 'seq': 23, 'course': 'BMGT 305' },
    { 'program_id': 27, 'seq': 24, 'course': 'WRTG 391' },
    { 'program_id': 27, 'seq': 25, 'course': 'ELECTIVE' },
    { 'program_id': 27, 'seq': 26, 'course': 'ELECTIVE' },
    { 'program_id': 27, 'seq': 27, 'course': 'BMGT 484' },
    { 'program_id': 27, 'seq': 28, 'course': 'ELECTIVE' },
    { 'program_id': 27, 'seq': 29, 'course': 'ELECTIVE' },
    { 'program_id': 27, 'seq': 30, 'course': 'BMGT 317' },
    { 'program_id': 27, 'seq': 31, 'course': 'ELECTIVE' },
    { 'program_id': 27, 'seq': 32, 'course': 'ELECTIVE' },
    { 'program_id': 27, 'seq': 33, 'course': 'BMGT 464' },
    { 'program_id': 27, 'seq': 34, 'course': 'ELECTIVE' },
    { 'program_id': 27, 'seq': 35, 'course': 'ELECTIVE' },
    { 'program_id': 27, 'seq': 36, 'course': 'BMGT 496' },
    { 'program_id': 27, 'seq': 37, 'course': 'ELECTIVE' },
    { 'program_id': 27, 'seq': 38, 'course': 'ELECTIVE' },
    { 'program_id': 27, 'seq': 39, 'course': 'ELECTIVE' },
    { 'program_id': 27, 'seq': 40, 'course': 'BMGT 485' },
    { 'program_id': 27, 'seq': 41, 'course': 'CAPL 398A' }
]

catalog_programs_add_28 = [
    { 'program_id': 28, 'seq':  1, 'course': 'LIBS 150' },
    { 'program_id': 28, 'seq':  2, 'course': 'PACE 111B' },
    { 'program_id': 28, 'seq':  3, 'course': 'WRTG 111' },
    { 'program_id': 28, 'seq':  4, 'course': 'WRTG 112' },
    { 'program_id': 28, 'seq':  5, 'course': 'NUTR 100' },
    { 'program_id': 28, 'seq':  6, 'course': 'MRKT 310' },
    { 'program_id': 28, 'seq':  7, 'course': 'SPCH 100' },
    { 'program_id': 28, 'seq':  8, 'course': 'MATH 105' },
    { 'program_id': 28, 'seq':  9, 'course': 'IFSM 300' },
    { 'program_id': 28, 'seq': 10, 'course': 'BMGT 110' },
    { 'program_id': 28, 'seq': 11, 'course': 'HUMN 100' },
    { 'program_id': 28, 'seq': 12, 'course': 'BIOL 103' },
    { 'program_id': 28, 'seq': 13, 'course': 'ECON 201' },
    { 'program_id': 28, 'seq': 14, 'course': 'ARTH 334' },
    { 'program_id': 28, 'seq': 15, 'course': 'ELECTIVE' },
    { 'program_id': 28, 'seq': 16, 'course': 'ECON 203' },
    { 'program_id': 28, 'seq': 17, 'course': 'MRKT 354' },
    { 'program_id': 28, 'seq': 18, 'course': 'ELECTIVE' },
    { 'program_id': 28, 'seq': 19, 'course': 'BMGT 330' },
    { 'program_id': 28, 'seq': 20, 'course': 'ELECTIVE' },
    { 'program_id': 28, 'seq': 21, 'course': 'MRKT 394' },
    { 'program_id': 28, 'seq': 22, 'course': 'ELECTIVE' },
    { 'program_id': 28, 'seq': 23, 'course': 'MRKT 410' },
    { 'program_id': 28, 'seq': 24, 'course': 'WRTG 394' },
    { 'program_id': 28, 'seq': 25, 'course': 'ELECTIVE' },
    { 'program_id': 28, 'seq': 26, 'course': 'MRKT 458' },
    { 'program_id': 28, 'seq': 27, 'course': 'ELECTIVE' },
    { 'program_id': 28, 'seq': 28, 'course': 'ELECTIVE' },
    { 'program_id': 28, 'seq': 29, 'course': 'MRKT 412' },
    { 'program_id': 28, 'seq': 30, 'course': 'ELECTIVE' },
    { 'program_id': 28, 'seq': 31, 'course': 'ELECTIVE' },
    { 'program_id': 28, 'seq': 32, 'course': 'MRKT 311' },
    { 'program_id': 28, 'seq': 33, 'course': 'ELECTIVE' },
    { 'program_id': 28, 'seq': 34, 'course': 'ELECTIVE' },
    { 'program_id': 28, 'seq': 35, 'course': 'MRKT 314' },
    { 'program_id': 28, 'seq': 36, 'course': 'ELECTIVE' },
    { 'program_id': 28, 'seq': 37, 'course': 'MRKT 454' },
    { 'program_id': 28, 'seq': 38, 'course': 'ELECTIVE' },
    { 'program_id': 28, 'seq': 39, 'course': 'ELECTIVE' },
    { 'program_id': 28, 'seq': 40, 'course': 'MRKT 495' },
    { 'program_id': 28, 'seq': 41, 'course': 'CAPL 398A' }
]

catalog_programs_add_30 = [
    { 'program_id': 30, 'seq':  1, 'course': 'LIBS 150' },
    { 'program_id': 30, 'seq':  2, 'course': 'PACE 111C' },
    { 'program_id': 30, 'seq':  3, 'course': 'WRTG 111' },
    { 'program_id': 30, 'seq':  4, 'course': 'CMSC 100' },
    { 'program_id': 30, 'seq':  5, 'course': 'NUTR 100' },
    { 'program_id': 30, 'seq':  6, 'course': 'GVPT 100' },
    { 'program_id': 30, 'seq':  7, 'course': 'SPCH 100' },
    { 'program_id': 30, 'seq':  8, 'course': 'MATH 105' },
    { 'program_id': 30, 'seq':  9, 'course': 'WRTG 112' },
    { 'program_id': 30, 'seq': 10, 'course': 'GVPT 101' },
    { 'program_id': 30, 'seq': 11, 'course': 'HUMN 100' },
    { 'program_id': 30, 'seq': 12, 'course': 'BIOL 103' },
    { 'program_id': 30, 'seq': 13, 'course': 'BEHS 103' },
    { 'program_id': 30, 'seq': 14, 'course': 'HIST 125' },
    { 'program_id': 30, 'seq': 15, 'course': 'ELECTIVE' },
    { 'program_id': 30, 'seq': 16, 'course': 'ECON 103' },
    { 'program_id': 30, 'seq': 17, 'course': 'GVPT 170' },
    { 'program_id': 30, 'seq': 18, 'course': 'ELECTIVE' },
    { 'program_id': 30, 'seq': 19, 'course': 'GVPT 210' },
    { 'program_id': 30, 'seq': 20, 'course': 'GVPT 280' },
    { 'program_id': 30, 'seq': 21, 'course': 'ELECTIVE' },
    { 'program_id': 30, 'seq': 22, 'course': 'GVPT 306' },
    { 'program_id': 30, 'seq': 23, 'course': 'ELECTIVE' },
    { 'program_id': 30, 'seq': 24, 'course': 'ELECTIVE' },
    { 'program_id': 30, 'seq': 25, 'course': 'WRTG 391' },
    { 'program_id': 30, 'seq': 26, 'course': 'ELECTIVE' },
    { 'program_id': 30, 'seq': 27, 'course': 'ELECTIVE' },
    { 'program_id': 30, 'seq': 28, 'course': 'ELECTIVE' },
    { 'program_id': 30, 'seq': 29, 'course': 'GVPT 403' },
    { 'program_id': 30, 'seq': 30, 'course': 'ELECTIVE' },
    { 'program_id': 30, 'seq': 31, 'course': 'ELECTIVE' },
    { 'program_id': 30, 'seq': 32, 'course': 'GVPT 406' },
    { 'program_id': 30, 'seq': 33, 'course': 'ELECTIVE' },
    { 'program_id': 30, 'seq': 34, 'course': 'ELECTIVE' },
    { 'program_id': 30, 'seq': 35, 'course': 'GVPT 457' },
    { 'program_id': 30, 'seq': 36, 'course': 'ELECTIVE' },
    { 'program_id': 30, 'seq': 37, 'course': 'ELECTIVE' },
    { 'program_id': 30, 'seq': 38, 'course': 'ELECTIVE' },
    { 'program_id': 30, 'seq': 39, 'course': 'ELECTIVE' },
    { 'program_id': 30, 'seq': 40, 'course': 'GVPT 495' },
    { 'program_id': 30, 'seq': 41, 'course': 'CAPL 398A' }
]

catalog_programs_add_31 = [
    { 'program_id': 31, 'seq':  1, 'course': 'LIBS 150' },
    { 'program_id': 31, 'seq':  2, 'course': 'PACE 111S' },
    { 'program_id': 31, 'seq':  3, 'course': 'WRTG 111' },
    { 'program_id': 31, 'seq':  4, 'course': 'CMST 301' },
    { 'program_id': 31, 'seq':  5, 'course': 'NUTR 100' },
    { 'program_id': 31, 'seq':  6, 'course': 'PSYC 100' },
    { 'program_id': 31, 'seq':  7, 'course': 'SPCH 100' },
    { 'program_id': 31, 'seq':  8, 'course': 'STAT 200' },
    { 'program_id': 31, 'seq':  9, 'course': 'WRTG 112' },
    { 'program_id': 31, 'seq': 10, 'course': 'PSYC 220' },
    { 'program_id': 31, 'seq': 11, 'course': 'HUMN 100' },
    { 'program_id': 31, 'seq': 12, 'course': 'BIOL 103' },
    { 'program_id': 31, 'seq': 13, 'course': 'BEHS 103' },
    { 'program_id': 31, 'seq': 14, 'course': 'ARTH 334' },
    { 'program_id': 31, 'seq': 15, 'course': 'ELECTIVE' },
    { 'program_id': 31, 'seq': 16, 'course': 'ECON 103' },
    { 'program_id': 31, 'seq': 17, 'course': 'PSYC 251' },
    { 'program_id': 31, 'seq': 18, 'course': 'ELECTIVE' },
    { 'program_id': 31, 'seq': 19, 'course': 'PSYC 300' },
    { 'program_id': 31, 'seq': 20, 'course': 'ELECTIVE' },
    { 'program_id': 31, 'seq': 21, 'course': 'ELECTIVE' },
    { 'program_id': 31, 'seq': 22, 'course': 'PSYC 301' },
    { 'program_id': 31, 'seq': 23, 'course': 'ELECTIVE' },
    { 'program_id': 31, 'seq': 24, 'course': 'PSYC 310' },
    { 'program_id': 31, 'seq': 25, 'course': 'ELECTIVE' },
    { 'program_id': 31, 'seq': 26, 'course': 'PSYC 335' },
    { 'program_id': 31, 'seq': 27, 'course': 'WRTG 391' },
    { 'program_id': 31, 'seq': 28, 'course': 'ELECTIVE' },
    { 'program_id': 31, 'seq': 29, 'course': 'PSYC 341' },
    { 'program_id': 31, 'seq': 30, 'course': 'ELECTIVE' },
    { 'program_id': 31, 'seq': 31, 'course': 'ELECTIVE' },
    { 'program_id': 31, 'seq': 32, 'course': 'ELECTIVE' },
    { 'program_id': 31, 'seq': 33, 'course': 'PSYC 353' },
    { 'program_id': 31, 'seq': 34, 'course': 'ELECTIVE' },
    { 'program_id': 31, 'seq': 35, 'course': 'ELECTIVE' },
    { 'program_id': 31, 'seq': 36, 'course': 'PSYC 436' },
    { 'program_id': 31, 'seq': 37, 'course': 'ELECTIVE' },
    { 'program_id': 31, 'seq': 38, 'course': 'ELECTIVE' },
    { 'program_id': 31, 'seq': 39, 'course': 'ELECTIVE' },
    { 'program_id': 31, 'seq': 40, 'course': 'PSYC 495' },
    { 'program_id': 31, 'seq': 41, 'course': 'CAPL 398A' }
]

catalog_programs_add_32 = [
    { 'program_id': 32, 'seq':  1, 'course': 'LIBS 150' },
    { 'program_id': 32, 'seq':  2, 'course': 'PACE 111P' },
    { 'program_id': 32, 'seq':  3, 'course': 'WRTG 111' },
    { 'program_id': 32, 'seq':  4, 'course': 'WRTG 112' },
    { 'program_id': 32, 'seq':  5, 'course': 'NUTR 100' },
    { 'program_id': 32, 'seq':  6, 'course': 'PSAD 302' },
    { 'program_id': 32, 'seq':  7, 'course': 'SPCH 100' },
    { 'program_id': 32, 'seq':  8, 'course': 'MATH 105' },
    { 'program_id': 32, 'seq':  9, 'course': 'IFSM 300' },
    { 'program_id': 32, 'seq': 10, 'course': 'PSAD 304' },
    { 'program_id': 32, 'seq': 11, 'course': 'HUMN 100' },
    { 'program_id': 32, 'seq': 12, 'course': 'BIOL 103' },
    { 'program_id': 32, 'seq': 13, 'course': 'BEHS 103' },
    { 'program_id': 32, 'seq': 14, 'course': 'ARTH 334' },
    { 'program_id': 32, 'seq': 15, 'course': 'ELECTIVE' },
    { 'program_id': 32, 'seq': 16, 'course': 'ECON 103' },
    { 'program_id': 32, 'seq': 17, 'course': 'PSAD 306' },
    { 'program_id': 32, 'seq': 18, 'course': 'ELECTIVE' },
    { 'program_id': 32, 'seq': 19, 'course': 'PSAD 408' },
    { 'program_id': 32, 'seq': 20, 'course': 'ELECTIVE' },
    { 'program_id': 32, 'seq': 21, 'course': 'PSAD 410' },
    { 'program_id': 32, 'seq': 22, 'course': 'ELECTIVE' },
    { 'program_id': 32, 'seq': 23, 'course': 'PSAD 414' },
    { 'program_id': 32, 'seq': 24, 'course': 'WRTG 391' },
    { 'program_id': 32, 'seq': 25, 'course': 'ELECTIVE' },
    { 'program_id': 32, 'seq': 26, 'course': 'PSAD 416' },
    { 'program_id': 32, 'seq': 27, 'course': 'ELECTIVE' },
    { 'program_id': 32, 'seq': 28, 'course': 'ELECTIVE' },
    { 'program_id': 32, 'seq': 29, 'course': 'FINC 331' },
    { 'program_id': 32, 'seq': 30, 'course': 'ELECTIVE' },
    { 'program_id': 32, 'seq': 31, 'course': 'ELECTIVE' },
    { 'program_id': 32, 'seq': 32, 'course': 'BMGT 317' },
    { 'program_id': 32, 'seq': 33, 'course': 'ELECTIVE' },
    { 'program_id': 32, 'seq': 34, 'course': 'ELECTIVE' },
    { 'program_id': 32, 'seq': 35, 'course': 'PSAD 495' },
    { 'program_id': 32, 'seq': 36, 'course': 'ELECTIVE' },
    { 'program_id': 32, 'seq': 37, 'course': 'ELECTIVE' },
    { 'program_id': 32, 'seq': 38, 'course': 'ELECTIVE' },
    { 'program_id': 32, 'seq': 39, 'course': 'ELECTIVE' },
    { 'program_id': 32, 'seq': 40, 'course': 'ELECTIVE' },
    { 'program_id': 32, 'seq': 41, 'course': 'CAPL 398A' }
]

catalog_programs_add_33 = [
    { 'program_id': 33, 'seq':  1, 'course': 'LIBS 150' },
    { 'program_id': 33, 'seq':  2, 'course': 'PACE 111S' },
    { 'program_id': 33, 'seq':  3, 'course': 'WRTG 111' },
    { 'program_id': 33, 'seq':  4, 'course': 'CMST 301' },
    { 'program_id': 33, 'seq':  5, 'course': 'NUTR 100' },
    { 'program_id': 33, 'seq':  6, 'course': 'ANTH 102|GERO 100|PSYC 100|SOCY 100' },
    { 'program_id': 33, 'seq':  7, 'course': 'SPCH 100' },
    { 'program_id': 33, 'seq':  8, 'course': 'STAT 200' },
    { 'program_id': 33, 'seq':  9, 'course': 'WRTG 112' },
    { 'program_id': 33, 'seq': 10, 'course': 'GERO 100|PSYC 100|SOCY 100|ANTH 102' },
    { 'program_id': 33, 'seq': 11, 'course': 'HUMN 100' },
    { 'program_id': 33, 'seq': 12, 'course': 'BIOL 103' },
    { 'program_id': 33, 'seq': 13, 'course': 'BEHS 103' },
    { 'program_id': 33, 'seq': 14, 'course': 'ARTH 334' },
    { 'program_id': 33, 'seq': 15, 'course': 'ELECTIVE' },
    { 'program_id': 33, 'seq': 16, 'course': 'ECON 103' },
    { 'program_id': 33, 'seq': 17, 'course': 'BEHS 210' },
    { 'program_id': 33, 'seq': 18, 'course': 'ELECTIVE' },
    { 'program_id': 33, 'seq': 19, 'course': 'BEHS 220|BEHS 250' },
    { 'program_id': 33, 'seq': 20, 'course': 'ELECTIVE' },
    { 'program_id': 33, 'seq': 21, 'course': 'BEHS 300' },
    { 'program_id': 33, 'seq': 22, 'course': 'ELECTIVE' },
    { 'program_id': 33, 'seq': 23, 'course': 'ANTH 345|GERO 302|PSYC 338|SOCY 313' },
    { 'program_id': 33, 'seq': 24, 'course': 'WRTG 391' },
    { 'program_id': 33, 'seq': 25, 'course': 'ELECTIVE' },
    { 'program_id': 33, 'seq': 26, 'course': 'ANTH 346|GERO 311|PSYC 354|SOCY 325' },
    { 'program_id': 33, 'seq': 27, 'course': 'ELECTIVE' },
    { 'program_id': 33, 'seq': 28, 'course': 'ELECTIVE' },
    { 'program_id': 33, 'seq': 29, 'course': 'ANTH 350|GERO 427|PSYC 386|SOCY 423' },
    { 'program_id': 33, 'seq': 30, 'course': 'ELECTIVE' },
    { 'program_id': 33, 'seq': 31, 'course': 'ELECTIVE' },
    { 'program_id': 33, 'seq': 32, 'course': 'ANTH 351|GERO 320|PSYC 437|SOCY 350' },
    { 'program_id': 33, 'seq': 33, 'course': 'ELECTIVE' },
    { 'program_id': 33, 'seq': 34, 'course': 'ELECTIVE' },
    { 'program_id': 33, 'seq': 35, 'course': 'ELECTIVE' },
    { 'program_id': 33, 'seq': 36, 'course': 'ELECTIVE' },
    { 'program_id': 33, 'seq': 37, 'course': 'ELECTIVE' },
    { 'program_id': 33, 'seq': 38, 'course': 'ELECTIVE' },
    { 'program_id': 33, 'seq': 39, 'course': 'ELECTIVE' },
    { 'program_id': 33, 'seq': 40, 'course': 'BEHS 495' },
    { 'program_id': 33, 'seq': 41, 'course': 'CAPL 398A' }
]

catalog_programs_add_34 = [
    { 'program_id': 34, 'seq':  1, 'course': 'LIBS 150' },
    { 'program_id': 34, 'seq':  2, 'course': 'PACE 111T' },
    { 'program_id': 34, 'seq':  3, 'course': 'WRTG 111' },
    { 'program_id': 34, 'seq':  4, 'course': 'CMSC 105' },
    { 'program_id': 34, 'seq':  5, 'course': 'NUTR 100' },
    { 'program_id': 34, 'seq':  6, 'course': 'CMSC 115' },
    { 'program_id': 34, 'seq':  7, 'course': 'SPCH 100' },
    { 'program_id': 34, 'seq':  8, 'course': 'MATH 107' },
    { 'program_id': 34, 'seq':  9, 'course': 'WRTG 112' },
    { 'program_id': 34, 'seq': 10, 'course': 'CMSC 215' },
    { 'program_id': 34, 'seq': 11, 'course': 'HIST 125' },
    { 'program_id': 34, 'seq': 12, 'course': 'NSCI 103' },
    { 'program_id': 34, 'seq': 13, 'course': 'BEHS 103' },
    { 'program_id': 34, 'seq': 14, 'course': 'ARTH 334' },
    { 'program_id': 34, 'seq': 15, 'course': 'ELECTIVE' },
    { 'program_id': 34, 'seq': 16, 'course': 'ECON 103' },
    { 'program_id': 34, 'seq': 17, 'course': 'CMSC 320' },
    { 'program_id': 34, 'seq': 18, 'course': 'ELECTIVE' },
    { 'program_id': 34, 'seq': 19, 'course': 'SDEV 300' },
    { 'program_id': 34, 'seq': 20, 'course': 'ELECTIVE' },
    { 'program_id': 34, 'seq': 21, 'course': 'SDEV 325' },
    { 'program_id': 34, 'seq': 22, 'course': 'ELECTIVE' },
    { 'program_id': 34, 'seq': 23, 'course': 'SDEV 350' },
    { 'program_id': 34, 'seq': 24, 'course': 'WRTG 393' },
    { 'program_id': 34, 'seq': 25, 'course': 'ELECTIVE' },
    { 'program_id': 34, 'seq': 26, 'course': 'SDEV 360' },
    { 'program_id': 34, 'seq': 27, 'course': 'ELECTIVE' },
    { 'program_id': 34, 'seq': 28, 'course': 'ELECTIVE' },
    { 'program_id': 34, 'seq': 29, 'course': 'SDEV 400' },
    { 'program_id': 34, 'seq': 30, 'course': 'ELECTIVE' },
    { 'program_id': 34, 'seq': 31, 'course': 'ELECTIVE' },
    { 'program_id': 34, 'seq': 32, 'course': 'SDEV 425' },
    { 'program_id': 34, 'seq': 33, 'course': 'ELECTIVE' },
    { 'program_id': 34, 'seq': 34, 'course': 'ELECTIVE' },
    { 'program_id': 34, 'seq': 35, 'course': 'SDEV 460' },
    { 'program_id': 34, 'seq': 36, 'course': 'ELECTIVE' },
    { 'program_id': 34, 'seq': 37, 'course': 'ELECTIVE' },
    { 'program_id': 34, 'seq': 38, 'course': 'ELECTIVE' },
    { 'program_id': 34, 'seq': 39, 'course': 'ELECTIVE' },
    { 'program_id': 34, 'seq': 40, 'course': 'CMSC 495' },
    { 'program_id': 34, 'seq': 41, 'course': 'CAPL 398A' }
]

catalog_programs_add_35 = [
    { 'program_id': 35, 'seq':  1, 'course': 'LIBS 150' },
    { 'program_id': 35, 'seq':  2, 'course': 'PACE 111T' },
    { 'program_id': 35, 'seq':  3, 'course': 'WRTG 111' },
    { 'program_id': 35, 'seq':  4, 'course': 'CMST 301' },
    { 'program_id': 35, 'seq':  5, 'course': 'NUTR 100' },
    { 'program_id': 35, 'seq':  6, 'course': 'CMST 290' },
    { 'program_id': 35, 'seq':  7, 'course': 'SPCH 100' },
    { 'program_id': 35, 'seq':  8, 'course': 'MATH 107' },
    { 'program_id': 35, 'seq':  9, 'course': 'WRTG 112' },
    { 'program_id': 35, 'seq': 10, 'course': 'CMST 295' },
    { 'program_id': 35, 'seq': 11, 'course': 'HIST 125' },
    { 'program_id': 35, 'seq': 12, 'course': 'BIOL 103' },
    { 'program_id': 35, 'seq': 13, 'course': 'BEHS 103' },
    { 'program_id': 35, 'seq': 14, 'course': 'ARTH 334' },
    { 'program_id': 35, 'seq': 15, 'course': 'ELECTIVE' },
    { 'program_id': 35, 'seq': 16, 'course': 'ECON 103' },
    { 'program_id': 35, 'seq': 17, 'course': 'CMST 385|CMST 310|CMST 308' },
    { 'program_id': 35, 'seq': 18, 'course': 'ELECTIVE' },
    { 'program_id': 35, 'seq': 19, 'course': 'CMST 386|CMST 311|CMST 315' },
    { 'program_id': 35, 'seq': 20, 'course': 'ELECTIVE' },
    { 'program_id': 35, 'seq': 21, 'course': 'CMST 325' },
    { 'program_id': 35, 'seq': 22, 'course': 'ELECTIVE' },
    { 'program_id': 35, 'seq': 23, 'course': 'CMST 320' },
    { 'program_id': 35, 'seq': 24, 'course': 'WRTG 393' },
    { 'program_id': 35, 'seq': 25, 'course': 'ELECTIVE' },
    { 'program_id': 35, 'seq': 26, 'course': 'CMST 388|CMST 425|CMST 330' },
    { 'program_id': 35, 'seq': 27, 'course': 'ELECTIVE' },
    { 'program_id': 35, 'seq': 28, 'course': 'ELECTIVE' },
    { 'program_id': 35, 'seq': 29, 'course': 'CMST 355|CMST 341|CMST 331' },
    { 'program_id': 35, 'seq': 30, 'course': 'ELECTIVE' },
    { 'program_id': 35, 'seq': 31, 'course': 'ELECTIVE' },
    { 'program_id': 35, 'seq': 32, 'course': 'CMST 488|CMST 351|CMST 390' },
    { 'program_id': 35, 'seq': 33, 'course': 'ELECTIVE' },
    { 'program_id': 35, 'seq': 34, 'course': 'ELECTIVE' },
    { 'program_id': 35, 'seq': 35, 'course': 'CMST 495' },
    { 'program_id': 35, 'seq': 36, 'course': 'ELECTIVE' },
    { 'program_id': 35, 'seq': 37, 'course': 'ELECTIVE' },
    { 'program_id': 35, 'seq': 38, 'course': 'ELECTIVE' },
    { 'program_id': 35, 'seq': 39, 'course': 'ELECTIVE' },
    { 'program_id': 35, 'seq': 40, 'course': 'ELECTIVE' },
    { 'program_id': 35, 'seq': 41, 'course': 'CAPL 398A' }
]

################################################################
# catalog_program_seq Table

drop_table('catalog_program_sequence',c)
c.execute('''
    CREATE TABLE catalog_program_sequence (
        id INTEGER PRIMARY KEY,
        program_id INTEGER,
        seq INTEGER,
        course TEXT
    )
''')

catalogs = [
    catalog_programs_add_02, 
    catalog_programs_add_05, 
    catalog_programs_add_06, 
    catalog_programs_add_07, 
    catalog_programs_add_08, 
    catalog_programs_add_09, 
    catalog_programs_add_10, 
    catalog_programs_add_11, 
    catalog_programs_add_12, 
    catalog_programs_add_13, 
    catalog_programs_add_14, 
    catalog_programs_add_15, 
    catalog_programs_add_17, 
    catalog_programs_add_18, 
    catalog_programs_add_19, 
    catalog_programs_add_20, 
    catalog_programs_add_21, 
    catalog_programs_add_22, 
    catalog_programs_add_23, 
    catalog_programs_add_25, 
    catalog_programs_add_26, 
    catalog_programs_add_27, 
    catalog_programs_add_28, 
    catalog_programs_add_30, 
    catalog_programs_add_31, 
    catalog_programs_add_32, 
    catalog_programs_add_33, 
    catalog_programs_add_34, 
    catalog_programs_add_35
]

for catalog in catalogs:
    c.executemany('''
        INSERT INTO catalog_program_sequence (program_id, seq, course) 
        VALUES (:program_id, :seq, :course)
    ''', catalog )
conn.commit()

# Close the connection
conn.close()
