import sqlite3
# db connection created w/in utils
from utils import conn, c, drop_table, drop_view, column_exists

################################################################
# "Program Requirements" Table
# Bachelor's program requirement summary

program_requirements = [
    { "program_id":  2, "major": 36, "related_ge": 12, "related_elective": 15, "remaining_ge": 29, "remaining_elective": 28 },
    { "program_id":  3, "major": 30, "related_ge":  0, "related_elective":  0, "remaining_ge": 41, "remaining_elective": 49 },
    { "program_id":  4, "major": 36, "related_ge":  8, "related_elective":  9, "remaining_ge": 33, "remaining_elective": 34 },
    { "program_id":  5, "major": 33, "related_ge": 12, "related_elective":  0, "remaining_ge": 29, "remaining_elective": 46 },
    { "program_id":  6, "major": 33, "related_ge":  0, "related_elective":  0, "remaining_ge": 41, "remaining_elective": 46 },
    { "program_id":  7, "major": 36, "related_ge":  7, "related_elective":  7, "remaining_ge": 34, "remaining_elective": 36 },
    { "program_id":  8, "major": 33, "related_ge":  0, "related_elective":  0, "remaining_ge": 41, "remaining_elective": 46 },
    { "program_id":  9, "major": 33, "related_ge":  0, "related_elective":  0, "remaining_ge": 41, "remaining_elective": 46 },
    { "program_id": 10, "major": 33, "related_ge":  0, "related_elective":  0, "remaining_ge": 41, "remaining_elective": 46 },
    { "program_id": 11, "major": 39, "related_ge":  6, "related_elective":  0, "remaining_ge": 35, "remaining_elective": 40 },
    { "program_id": 12, "major": 30, "related_ge":  0, "related_elective":  0, "remaining_ge": 41, "remaining_elective": 49 },
    { "program_id": 13, "major": 33, "related_ge":  0, "related_elective":  0, "remaining_ge": 41, "remaining_elective": 46 },
    { "program_id": 14, "major": 36, "related_ge":  6, "related_elective":  0, "remaining_ge": 35, "remaining_elective": 43 },
    { "program_id": 15, "major": 39, "related_ge":  9, "related_elective":  0, "remaining_ge": 32, "remaining_elective": 40 },
    { "program_id": 16, "major": 30, "related_ge":  0, "related_elective":  0, "remaining_ge": 41, "remaining_elective": 49 },
    { "program_id": 17, "major": 33, "related_ge":  3, "related_elective":  0, "remaining_ge": 38, "remaining_elective": 46 },
    { "program_id": 18, "major": 33, "related_ge":  0, "related_elective":  0, "remaining_ge": 41, "remaining_elective": 46 },
    { "program_id": 19, "major": 33, "related_ge":  6, "related_elective":  0, "remaining_ge": 35, "remaining_elective": 46 },
    { "program_id": 20, "major": 33, "related_ge":  0, "related_elective":  0, "remaining_ge": 41, "remaining_elective": 46 },
    { "program_id": 21, "major": 33, "related_ge":  3, "related_elective":  0, "remaining_ge": 38, "remaining_elective": 46 },
    { "program_id": 22, "major": 36, "related_ge":  3, "related_elective":  0, "remaining_ge": 38, "remaining_elective": 43 },
    { "program_id": 23, "major": 33, "related_ge":  0, "related_elective":  0, "remaining_ge": 41, "remaining_elective": 46 },
    { "program_id": 24, "major": 36, "related_ge":  8, "related_elective":  6, "remaining_ge": 33, "remaining_elective": 37 },
    { "program_id": 25, "major": 33, "related_ge":  0, "related_elective":  0, "remaining_ge": 41, "remaining_elective": 46 },
    { "program_id": 26, "major": 33, "related_ge":  3, "related_elective":  0, "remaining_ge": 38, "remaining_elective": 46 },
    { "program_id": 27, "major": 33, "related_ge":  9, "related_elective":  0, "remaining_ge": 32, "remaining_elective": 46 },
    { "program_id": 28, "major": 36, "related_ge":  0, "related_elective":  0, "remaining_ge": 41, "remaining_elective": 43 },
    { "program_id": 29, "major": 30, "related_ge": 17, "related_elective":  4, "remaining_ge": 24, "remaining_elective": 45 },
    { "program_id": 30, "major": 30, "related_ge":  0, "related_elective":  0, "remaining_ge": 41, "remaining_elective": 49 },
    { "program_id": 31, "major": 33, "related_ge":  3, "related_elective":  0, "remaining_ge": 38, "remaining_elective": 46 },
    { "program_id": 32, "major": 30, "related_ge":  3, "related_elective":  0, "remaining_ge": 38, "remaining_elective": 49 },
    { "program_id": 33, "major": 30, "related_ge":  3, "related_elective":  0, "remaining_ge": 38, "remaining_elective": 49 },
    { "program_id": 34, "major": 33, "related_ge":  0, "related_elective":  0, "remaining_ge": 41, "remaining_elective": 46 },
    { "program_id": 35, "major": 30, "related_ge":  0, "related_elective":  0, "remaining_ge": 41, "remaining_elective": 49 }
]

drop_table('program_requirements',c)
c.execute('''
    CREATE TABLE program_requirements (
        id INTEGER PRIMARY KEY,
        program_id INTEGER,
        major INTEGER,
        related_ge INTEGER,
        related_elective INTEGER,
        remaining_ge INTEGER,
        remaining_elective INTEGER,
        total INTEGER DEFAULT 120,
        FOREIGN KEY(program_id) REFERENCES programs(id)
    )
''')

c.executemany('''
    INSERT INTO program_requirements (program_id, major, related_ge, related_elective, remaining_ge, remaining_elective)
        VALUES (:program_id, :major, :related_ge, :related_elective, :remaining_ge, :remaining_elective )
''', program_requirements)
#c.execute('UPDATE program_requirements SET total=120')
conn.commit()

################################################################
# "Program Requirement Courses" Table

program_requirement_courses = [
    { "program_id":  2, "course_type_id": 1, "course": "ACCT 220", "substitutions": "" },
    { "program_id":  2, "course_type_id": 1, "course": "ACCT 221", "substitutions": "" },
    { "program_id":  2, "course_type_id": 1, "course": "ACCT 310", "substitutions": "" },
    { "program_id":  2, "course_type_id": 1, "course": "ACCT 311", "substitutions": "" },
    { "program_id":  2, "course_type_id": 1, "course": "ACCT 321", "substitutions": "" },
    { "program_id":  2, "course_type_id": 1, "course": "ACCT 323", "substitutions": "" },
    { "program_id":  2, "course_type_id": 1, "course": "ACCT 326", "substitutions": "" },
    { "program_id":  2, "course_type_id": 1, "course": "ACCT 410", "substitutions": "ACCT 300+" },
    { "program_id":  2, "course_type_id": 1, "course": "ACCT 422", "substitutions": "" },
    { "program_id":  2, "course_type_id": 1, "course": "ACCT 424", "substitutions": "" },
    { "program_id":  2, "course_type_id": 1, "course": "ACCT 436", "substitutions": "ACCT 300+" },
    { "program_id":  2, "course_type_id": 1, "course": "ACCT 438", "substitutions": "ACCT 300+" },
    { "program_id":  2, "course_type_id": 6, "course": "ECON 201", "substitutions": "" },
    { "program_id":  2, "course_type_id": 6, "course": "ECON 203", "substitutions": "" },
    { "program_id":  2, "course_type_id": 6, "course": "STAT 200", "substitutions": "" },
    { "program_id":  2, "course_type_id": 6, "course": "WRTG 293", "substitutions": "COMM 390 | WRTG 394" },
    { "program_id":  2, "course_type_id": 7, "course": "BMGT 364", "substitutions": "" },
    { "program_id":  2, "course_type_id": 7, "course": "BMGT 380", "substitutions": "" },
    { "program_id":  2, "course_type_id": 7, "course": "FINC 330", "substitutions": "" },
    { "program_id":  2, "course_type_id": 7, "course": "MRKT 310", "substitutions": "" },
    { "program_id":  2, "course_type_id": 7, "course": "ACCT 411", "substitutions": "BMGT 496" },
    { "program_id":  5, "course_type_id": 1, "course": "BMGT 110", "substitutions": "" },
    { "program_id":  5, "course_type_id": 1, "course": "ACCT 220", "substitutions": "" },
    { "program_id":  5, "course_type_id": 1, "course": "ACCT 221", "substitutions": "" },
    { "program_id":  5, "course_type_id": 1, "course": "BMGT 364", "substitutions": "" },
    { "program_id":  5, "course_type_id": 1, "course": "BMGT 365", "substitutions": "" },
    { "program_id":  5, "course_type_id": 1, "course": "MRKT 310", "substitutions": "" },
    { "program_id":  5, "course_type_id": 1, "course": "BMGT 380", "substitutions": "" },
    { "program_id":  5, "course_type_id": 1, "course": "HRMN 300", "substitutions": "" },
    { "program_id":  5, "course_type_id": 1, "course": "FINC 330", "substitutions": "" },
    { "program_id":  5, "course_type_id": 1, "course": "BMGT 496", "substitutions": "" },
    { "program_id":  5, "course_type_id": 1, "course": "BMGT 495", "substitutions": "" },
    { "program_id":  5, "course_type_id": 6, "course": "ECON 201", "substitutions": "" },
    { "program_id":  5, "course_type_id": 6, "course": "ECON 203", "substitutions": "" },
    { "program_id":  5, "course_type_id": 6, "course": "IFSM 300", "substitutions": "" },
    { "program_id":  5, "course_type_id": 6, "course": "STAT 200", "substitutions": "" },
	{ "program_id":  6, "course_type_id": 1, "course": "SPCH 100", "substitutions": "SPCH 100+" },
	{ "program_id":  6, "course_type_id": 1, "course": "COMM 207", "substitutions": "COMM 100+" },
	{ "program_id":  6, "course_type_id": 1, "course": "JOUR 201", "substitutions": "" },
	{ "program_id":  6, "course_type_id": 1, "course": "COMM 300", "substitutions": "" },
	{ "program_id":  6, "course_type_id": 1, "course": "COMM 302", "substitutions": "" },
	{ "program_id":  6, "course_type_id": 1, "course": "SPCH 324", "substitutions": "" },
	{ "program_id":  6, "course_type_id": 1, "course": "JOUR 330", "substitutions": "JOUR 300+" },
	{ "program_id":  6, "course_type_id": 1, "course": "COMM 400", "substitutions": "COMM 300+" },
	{ "program_id":  6, "course_type_id": 1, "course": "SPCH 470", "substitutions": "SPCH 300+" },
	{ "program_id":  6, "course_type_id": 1, "course": "COMM 390", "substitutions": "COMM 300+" },
	{ "program_id":  6, "course_type_id": 1, "course": "COMM 495", "substitutions": "" },
	{ "program_id":  7, "course_type_id": 1, "course": "CMSC 115", "substitutions": "" },
	{ "program_id":  7, "course_type_id": 1, "course": "CMSC 215", "substitutions": "" },
	{ "program_id":  7, "course_type_id": 1, "course": "CMSC 310", "substitutions": "" },
	{ "program_id":  7, "course_type_id": 1, "course": "CMIT 265", "substitutions": "" },
	{ "program_id":  7, "course_type_id": 1, "course": "CMSC 315", "substitutions": "" },
	{ "program_id":  7, "course_type_id": 1, "course": "CMSC 320", "substitutions": "" },
	{ "program_id":  7, "course_type_id": 1, "course": "CMSC 330", "substitutions": "" },
	{ "program_id":  7, "course_type_id": 1, "course": "CMSC 335", "substitutions": "" },
	{ "program_id":  7, "course_type_id": 1, "course": "CMSC 345", "substitutions": "" },
	{ "program_id":  7, "course_type_id": 1, "course": "CMSC 430", "substitutions": "" },
	{ "program_id":  7, "course_type_id": 1, "course": "CMSC 451", "substitutions": "" },
	{ "program_id":  7, "course_type_id": 1, "course": "CMSC 495", "substitutions": "" },
	{ "program_id":  7, "course_type_id": 6, "course": "MATH 140", "substitutions": "" },
	{ "program_id":  7, "course_type_id": 6, "course": "CMSC 105", "substitutions": "" },
	{ "program_id":  7, "course_type_id": 7, "course": "MATH 141", "substitutions": "" },
	{ "program_id":  7, "course_type_id": 7, "course": "CMSC 150", "substitutions": "" },
	{ "program_id":  8, "course_type_id": 1, "course": "CCJS 100", "substitutions": "" },
	{ "program_id":  8, "course_type_id": 1, "course": "CCJS 230", "substitutions": "" },
	{ "program_id":  8, "course_type_id": 1, "course": "CCJS 340", "substitutions": "" },
	{ "program_id":  8, "course_type_id": 1, "course": "CCJS 345", "substitutions": "" },
	{ "program_id":  8, "course_type_id": 1, "course": "CCJS 350", "substitutions": "" },
	{ "program_id":  8, "course_type_id": 1, "course": "CCJS 360", "substitutions": "" },
	{ "program_id":  8, "course_type_id": 1, "course": "CCJS 380", "substitutions": "" },
	{ "program_id":  8, "course_type_id": 1, "course": "CCJS 341", "substitutions": "" },
	{ "program_id":  8, "course_type_id": 1, "course": "CCJS 352", "substitutions": "" },
	{ "program_id":  8, "course_type_id": 1, "course": "CCJS 497", "substitutions": "" },
	{ "program_id":  8, "course_type_id": 1, "course": "CCJS 495", "substitutions": "" },
	{ "program_id":  9, "course_type_id": 1, "course": "CSIA 300", "substitutions": "" },
	{ "program_id":  9, "course_type_id": 1, "course": "IFSM 304", "substitutions": "" },
	{ "program_id":  9, "course_type_id": 1, "course": "CMIT 265", "substitutions": "" },
	{ "program_id":  9, "course_type_id": 1, "course": "CMIT 320", "substitutions": "" },
	{ "program_id":  9, "course_type_id": 1, "course": "CSIA 310", "substitutions": "" },
	{ "program_id":  9, "course_type_id": 1, "course": "CSIA 350", "substitutions": "" },
	{ "program_id":  9, "course_type_id": 1, "course": "CSIA 360", "substitutions": "" },
	{ "program_id":  9, "course_type_id": 1, "course": "CSIA 413", "substitutions": "" },
	{ "program_id":  9, "course_type_id": 1, "course": "CSIA 459", "substitutions": "" },
	{ "program_id":  9, "course_type_id": 1, "course": "CMIT 425", "substitutions": "" },
	{ "program_id":  9, "course_type_id": 1, "course": "CSIA 485", "substitutions": "" },
	{ "program_id": 11, "course_type_id": 1, "course": "STAT 200", "substitutions": "" },
	{ "program_id": 11, "course_type_id": 1, "course": "DATA 230", "substitutions": "" },
	{ "program_id": 11, "course_type_id": 1, "course": "DATA 300", "substitutions": "" },
	{ "program_id": 11, "course_type_id": 1, "course": "CSIA 300", "substitutions": "" },
	{ "program_id": 11, "course_type_id": 1, "course": "DATA 320", "substitutions": "" },
	{ "program_id": 11, "course_type_id": 1, "course": "IFSM 330", "substitutions": "" },
	{ "program_id": 11, "course_type_id": 1, "course": "DATA 335", "substitutions": "" },
	{ "program_id": 11, "course_type_id": 1, "course": "DATA 430", "substitutions": "" },
	{ "program_id": 11, "course_type_id": 1, "course": "DATA 440", "substitutions": "" },
	{ "program_id": 11, "course_type_id": 1, "course": "DATA 445", "substitutions": "" },
	{ "program_id": 11, "course_type_id": 1, "course": "DATA 450", "substitutions": "" },
	{ "program_id": 11, "course_type_id": 1, "course": "DATA 460", "substitutions": "" },
	{ "program_id": 11, "course_type_id": 1, "course": "DATA 495", "substitutions": "" },
	{ "program_id": 11, "course_type_id": 6, "course": "DATA 200", "substitutions": "" },
	{ "program_id": 11, "course_type_id": 6, "course": "MATH 115", "substitutions": "" },
	{ "program_id": 14, "course_type_id": 1, "course": "ENHS 300", "substitutions": "" },
	{ "program_id": 14, "course_type_id": 1, "course": "ENHS 305", "substitutions": "" },
	{ "program_id": 14, "course_type_id": 1, "course": "ENHS 310", "substitutions": "" },
	{ "program_id": 14, "course_type_id": 1, "course": "ENHS 315", "substitutions": "" },
	{ "program_id": 14, "course_type_id": 1, "course": "ENHS 320", "substitutions": "" },
	{ "program_id": 14, "course_type_id": 1, "course": "ENHS 325", "substitutions": "" },
	{ "program_id": 14, "course_type_id": 1, "course": "ENHS 330", "substitutions": "" },
	{ "program_id": 14, "course_type_id": 1, "course": "ENHS 335", "substitutions": "" },
	{ "program_id": 14, "course_type_id": 1, "course": "ENHS 340", "substitutions": "" },
	{ "program_id": 14, "course_type_id": 1, "course": "ENHS 400", "substitutions": "" },
	{ "program_id": 14, "course_type_id": 1, "course": "ENHS 405", "substitutions": "" },
	{ "program_id": 14, "course_type_id": 1, "course": "ENHS 495", "substitutions": "" },
	{ "program_id": 14, "course_type_id": 6, "course": "CHEM 297", "substitutions": "" },
	{ "program_id": 14, "course_type_id": 6, "course": "MATH 115", "substitutions": "" },
	{ "program_id": 15, "course_type_id": 1, "course": "BMGT 364", "substitutions": "" },
	{ "program_id": 15, "course_type_id": 1, "course": "ACCT 220", "substitutions": "" },
	{ "program_id": 15, "course_type_id": 1, "course": "ACCT 221", "substitutions": "" },
	{ "program_id": 15, "course_type_id": 1, "course": "FINC 330", "substitutions": "" },
	{ "program_id": 15, "course_type_id": 1, "course": "FINC 335", "substitutions": "" },
	{ "program_id": 15, "course_type_id": 1, "course": "FINC 340", "substitutions": "" },
	{ "program_id": 15, "course_type_id": 1, "course": "FINC 351", "substitutions": "" },
	{ "program_id": 15, "course_type_id": 1, "course": "FINC 421", "substitutions": "" },
	{ "program_id": 15, "course_type_id": 1, "course": "FINC 430", "substitutions": "" },
	{ "program_id": 15, "course_type_id": 1, "course": "FINC 440", "substitutions": "" },
	{ "program_id": 15, "course_type_id": 1, "course": "FINC 460", "substitutions": "" },
	{ "program_id": 15, "course_type_id": 1, "course": "ECON 430", "substitutions": "" },
	{ "program_id": 15, "course_type_id": 1, "course": "FINC 495", "substitutions": "" },
	{ "program_id": 15, "course_type_id": 6, "course": "ECON 201", "substitutions": "" },
	{ "program_id": 15, "course_type_id": 6, "course": "ECON 203", "substitutions": "" },
	{ "program_id": 15, "course_type_id": 6, "course": "STAT 200", "substitutions": "" },
	{ "program_id": 17, "course_type_id": 1, "course": "GERO 100", "substitutions": "" },
	{ "program_id": 17, "course_type_id": 1, "course": "GERO 301", "substitutions": "" },
	{ "program_id": 17, "course_type_id": 1, "course": "GERO 302", "substitutions": "" },
	{ "program_id": 17, "course_type_id": 1, "course": "GERO 306", "substitutions": "" },
	{ "program_id": 17, "course_type_id": 1, "course": "GERO 311", "substitutions": "" },
	{ "program_id": 17, "course_type_id": 1, "course": "GERO 320", "substitutions": "" },
	{ "program_id": 17, "course_type_id": 1, "course": "GERO 338", "substitutions": "" },
	{ "program_id": 17, "course_type_id": 1, "course": "GERO 342", "substitutions": "" },
	{ "program_id": 17, "course_type_id": 1, "course": "GERO 390", "substitutions": "" },
	{ "program_id": 17, "course_type_id": 1, "course": "GERO 427", "substitutions": "" },
	{ "program_id": 17, "course_type_id": 1, "course": "GERO 486A", "substitutions": "" },
	{ "program_id": 17, "course_type_id": 6, "course": "STAT 200", "substitutions": "" },
	{ "program_id": 18, "course_type_id": 1, "course": "GRCO 100", "substitutions": "" },
	{ "program_id": 18, "course_type_id": 1, "course": "ARTT 110", "substitutions": "" },
	{ "program_id": 18, "course_type_id": 1, "course": "ARTT 120", "substitutions": "" },
	{ "program_id": 18, "course_type_id": 1, "course": "ARTT 210", "substitutions": "" },
	{ "program_id": 18, "course_type_id": 1, "course": "GRCO 230", "substitutions": "" },
	{ "program_id": 18, "course_type_id": 1, "course": "GRCO 350", "substitutions": "" },
	{ "program_id": 18, "course_type_id": 1, "course": "GRCO 354", "substitutions": "" },
	{ "program_id": 18, "course_type_id": 1, "course": "GRCO 355", "substitutions": "" },
	{ "program_id": 18, "course_type_id": 1, "course": "GRCO 450", "substitutions": "" },
	{ "program_id": 18, "course_type_id": 1, "course": "GRCO 479", "substitutions": "" },
	{ "program_id": 18, "course_type_id": 1, "course": "GRCO 495", "substitutions": "" },
	{ "program_id": 19, "course_type_id": 1, "course": "HMGT 300", "substitutions": "" },
	{ "program_id": 19, "course_type_id": 1, "course": "HMGT 307", "substitutions": "" },
	{ "program_id": 19, "course_type_id": 1, "course": "HMGT 310", "substitutions": "" },
	{ "program_id": 19, "course_type_id": 1, "course": "HMGT 320", "substitutions": "" },
	{ "program_id": 19, "course_type_id": 1, "course": "HMGT 322", "substitutions": "" },
	{ "program_id": 19, "course_type_id": 1, "course": "HMGT 335", "substitutions": "" },
	{ "program_id": 19, "course_type_id": 1, "course": "HMGT 372", "substitutions": "" },
	{ "program_id": 19, "course_type_id": 1, "course": "HMGT 400", "substitutions": "" },
	{ "program_id": 19, "course_type_id": 1, "course": "HMGT 420", "substitutions": "" },
	{ "program_id": 19, "course_type_id": 1, "course": "HMGT 435", "substitutions": "" },
	{ "program_id": 19, "course_type_id": 1, "course": "HMGT 495", "substitutions": "" },
	{ "program_id": 19, "course_type_id": 6, "course": "IFSM 305", "substitutions": "" },
	{ "program_id": 19, "course_type_id": 6, "course": "STAT 200", "substitutions": "" },
	{ "program_id": 21, "course_type_id": 1, "course": "HMLS 302", "substitutions": "" },
	{ "program_id": 21, "course_type_id": 1, "course": "HMLS 310", "substitutions": "" },
	{ "program_id": 21, "course_type_id": 1, "course": "HMLS 406", "substitutions": "" },
	{ "program_id": 21, "course_type_id": 1, "course": "HMLS 408", "substitutions": "" },
	{ "program_id": 21, "course_type_id": 1, "course": "HMLS 414", "substitutions": "" },
	{ "program_id": 21, "course_type_id": 1, "course": "HMLS 416", "substitutions": "" },
	{ "program_id": 21, "course_type_id": 1, "course": "PSAD 410", "substitutions": "" },
	{ "program_id": 21, "course_type_id": 1, "course": "PSAD 414", "substitutions": "" },
	{ "program_id": 21, "course_type_id": 1, "course": "PSAD 416", "substitutions": "" },
	{ "program_id": 21, "course_type_id": 1, "course": "HMLS 304", "substitutions": "" },
	{ "program_id": 21, "course_type_id": 1, "course": "HMLS 495", "substitutions": "" },
	{ "program_id": 21, "course_type_id": 6, "course": "IFSM 300", "substitutions": "" },
    { "program_id": 22, "course_type_id": 1, "course": "HRMN 300", "substitutions": "" },
    { "program_id": 22, "course_type_id": 1, "course": "HRMN 302", "substitutions": "" },
    { "program_id": 22, "course_type_id": 1, "course": "HRMN 362", "substitutions": "" },
    { "program_id": 22, "course_type_id": 1, "course": "HRMN 367", "substitutions": "" },
    { "program_id": 22, "course_type_id": 1, "course": "HRMN 395", "substitutions": "" },
    { "program_id": 22, "course_type_id": 1, "course": "HRMN 400", "substitutions": "" },
    { "program_id": 22, "course_type_id": 1, "course": "HRMN 406", "substitutions": "HRMN 410" },
    { "program_id": 22, "course_type_id": 1, "course": "BMGT 364", "substitutions": "" },
    { "program_id": 22, "course_type_id": 1, "course": "FINC 331", "substitutions": "" },
    { "program_id": 22, "course_type_id": 1, "course": "HRMN 408", "substitutions": "" },
    { "program_id": 22, "course_type_id": 1, "course": "HRMN 467", "substitutions": "" },
    { "program_id": 22, "course_type_id": 1, "course": "HRMN 495", "substitutions": "" },
    { "program_id": 22, "course_type_id": 6, "course": "IFSM 300", "substitutions": "" },
    { "program_id": 23, "course_type_id": 1, "course": "HUMN 100", "substitutions": "" },
    { "program_id": 23, "course_type_id": 1, "course": "PHIL 100", "substitutions": "" },
    { "program_id": 23, "course_type_id": 1, "course": "PHIL 140", "substitutions": "" },
    { "program_id": 23, "course_type_id": 1, "course": "HIST 115", "substitutions": "HIST 116 | HIST 141 | HIST 142" },
    { "program_id": 23, "course_type_id": 1, "course": "MUSC 210", "substitutions": "MUSC 100+" },
    { "program_id": 23, "course_type_id": 1, "course": "ARTH 372", "substitutions": "ARTH 300+" },
    { "program_id": 23, "course_type_id": 1, "course": "PHIL 304", "substitutions": "PHIL 300+" },
    { "program_id": 23, "course_type_id": 1, "course": "HUMN 351", "substitutions": "HUMN 300+" },
    { "program_id": 23, "course_type_id": 1, "course": "PHIL 349", "substitutions": "PHIL 300+" },
    { "program_id": 23, "course_type_id": 1, "course": "ENGL 406", "substitutions": "ENGL 300+" },
    { "program_id": 23, "course_type_id": 1, "course": "HUMN 495", "substitutions": "" },
    { "program_id": 25, "course_type_id": 1, "course": "LGST 101", "substitutions": "" },
    { "program_id": 25, "course_type_id": 1, "course": "LGST 200", "substitutions": "" },
    { "program_id": 25, "course_type_id": 1, "course": "LGST 201", "substitutions": "" },
    { "program_id": 25, "course_type_id": 1, "course": "LGST 204", "substitutions": "" },
    { "program_id": 25, "course_type_id": 1, "course": "LGST 301", "substitutions": "" },
    { "program_id": 25, "course_type_id": 1, "course": "LGST 312", "substitutions": "" },
    { "program_id": 25, "course_type_id": 1, "course": "LGST 315", "substitutions": "" },
    { "program_id": 25, "course_type_id": 1, "course": "LGST 320", "substitutions": "" },
    { "program_id": 25, "course_type_id": 1, "course": "LGST 325", "substitutions": "" },
    { "program_id": 25, "course_type_id": 1, "course": "LGST 340", "substitutions": "" },
    { "program_id": 25, "course_type_id": 1, "course": "LGST 495", "substitutions": "" },
    { "program_id": 26, "course_type_id": 1, "course": "IFSM 300", "substitutions": "" }, 
    { "program_id": 26, "course_type_id": 1, "course": "IFSM 301", "substitutions": "" }, 
    { "program_id": 26, "course_type_id": 1, "course": "IFSM 304", "substitutions": "" }, 
    { "program_id": 26, "course_type_id": 1, "course": "CSIA 300", "substitutions": "" }, 
    { "program_id": 26, "course_type_id": 1, "course": "IFSM 310", "substitutions": "" }, 
    { "program_id": 26, "course_type_id": 1, "course": "IFSM 311", "substitutions": "" }, 
    { "program_id": 26, "course_type_id": 1, "course": "IFSM 330", "substitutions": "" }, 
    { "program_id": 26, "course_type_id": 1, "course": "IFSM 370", "substitutions": "" }, 
    { "program_id": 26, "course_type_id": 1, "course": "IFSM 438", "substitutions": "" }, 
    { "program_id": 26, "course_type_id": 1, "course": "IFSM 461", "substitutions": "" }, 
    { "program_id": 26, "course_type_id": 1, "course": "IFSM 495", "substitutions": "" }, 
    { "program_id": 26, "course_type_id": 6, "course": "CMSC 105", "substitutions": "" }, 
    { "program_id": 27, "course_type_id": 1, "course": "BMGT 160", "substitutions": "" },
    { "program_id": 27, "course_type_id": 1, "course": "ACCT 301", "substitutions": "ACCT 220" },
    { "program_id": 27, "course_type_id": 1, "course": "BMGT 364", "substitutions": "" },
    { "program_id": 27, "course_type_id": 1, "course": "BMGT 365", "substitutions": "ACCT 300+ | BMGT 300+ | FINC 300+ | HRMN 300+ | MRKT 300+" },
    { "program_id": 27, "course_type_id": 1, "course": "BMGT 464", "substitutions": "BMGT 465" },
    { "program_id": 27, "course_type_id": 1, "course": "BMGT 317", "substitutions": "" },
    { "program_id": 27, "course_type_id": 1, "course": "BMGT 305", "substitutions": "" },
    { "program_id": 27, "course_type_id": 1, "course": "BMGT 304", "substitutions": "ACCT 300+ | BMGT 300+ | FINC 300+ | HRMN 300+ | MRKT 300+" },
    { "program_id": 27, "course_type_id": 1, "course": "BMGT 484", "substitutions": "" },
    { "program_id": 27, "course_type_id": 1, "course": "BMGT 496", "substitutions": "" },
    { "program_id": 27, "course_type_id": 1, "course": "BMGT 485", "substitutions": "" },
    { "program_id": 27, "course_type_id": 6, "course": "ECON 201", "substitutions": "" },
    { "program_id": 27, "course_type_id": 6, "course": "IFSM 300", "substitutions": "" },
    { "program_id": 27, "course_type_id": 6, "course": "STAT 200", "substitutions": "" },
    { "program_id": 28, "course_type_id": 1, "course": "BMGT 110", "substitutions": "" },
    { "program_id": 28, "course_type_id": 1, "course": "BMGT 330", "substitutions": "" },
    { "program_id": 28, "course_type_id": 1, "course": "MRKT 310", "substitutions": "" },
    { "program_id": 28, "course_type_id": 1, "course": "MRKT 354", "substitutions": "" },
    { "program_id": 28, "course_type_id": 1, "course": "MRKT 394", "substitutions": "" },
    { "program_id": 28, "course_type_id": 1, "course": "MRKT 410", "substitutions": "" },
    { "program_id": 28, "course_type_id": 1, "course": "MRKT 412", "substitutions": "" },
    { "program_id": 28, "course_type_id": 1, "course": "MRKT 458", "substitutions": "" },
    { "program_id": 28, "course_type_id": 1, "course": "MRKT 311", "substitutions": "" },
    { "program_id": 28, "course_type_id": 1, "course": "MRKT 314", "substitutions": "" },
    { "program_id": 28, "course_type_id": 1, "course": "MRKT 454", "substitutions": "" },
    { "program_id": 28, "course_type_id": 1, "course": "MRKT 495", "substitutions": "" },
    { "program_id": 30, "course_type_id": 1, "course": "GVPT 100", "substitutions": "" },
    { "program_id": 30, "course_type_id": 1, "course": "GVPT 101", "substitutions": "" },
    { "program_id": 30, "course_type_id": 1, "course": "GVPT 170", "substitutions": "GVPT 200" },
    { "program_id": 30, "course_type_id": 1, "course": "GVPT 210", "substitutions": "" },
    { "program_id": 30, "course_type_id": 1, "course": "GVPT 280", "substitutions": "" },
    { "program_id": 30, "course_type_id": 1, "course": "GVPT 306", "substitutions": "" },
    { "program_id": 30, "course_type_id": 1, "course": "GVPT 403", "substitutions": "GVPT 300+" },
    { "program_id": 30, "course_type_id": 1, "course": "GVPT 406", "substitutions": "" },
    { "program_id": 30, "course_type_id": 1, "course": "GVPT 457", "substitutions": "GVPT 300+" },
    { "program_id": 30, "course_type_id": 1, "course": "GVPT 495", "substitutions": "" },
    { "program_id": 31, "course_type_id": 1, "course": "PSYC 100", "substitutions": "" }, 
    { "program_id": 31, "course_type_id": 1, "course": "PSYC 220", "substitutions": "" }, 
    { "program_id": 31, "course_type_id": 1, "course": "PSYC 251", "substitutions": "" }, 
    { "program_id": 31, "course_type_id": 1, "course": "PSYC 300", "substitutions": "" }, 
    { "program_id": 31, "course_type_id": 1, "course": "PSYC 301", "substitutions": "" }, 
    { "program_id": 31, "course_type_id": 1, "course": "PSYC 310", "substitutions": "" }, 
    { "program_id": 31, "course_type_id": 1, "course": "PSYC 335", "substitutions": "" }, 
    { "program_id": 31, "course_type_id": 1, "course": "PSYC 341", "substitutions": "" }, 
    { "program_id": 31, "course_type_id": 1, "course": "PSYC 353", "substitutions": "" }, 
    { "program_id": 31, "course_type_id": 1, "course": "PSYC 436", "substitutions": "" }, 
    { "program_id": 31, "course_type_id": 1, "course": "PSYC 495", "substitutions": "" }, 
    { "program_id": 31, "course_type_id": 6, "course": "STAT 200", "substitutions": "" },
    { "program_id": 32, "course_type_id": 1, "course": "PSAD 302", "substitutions": "" }, 
    { "program_id": 32, "course_type_id": 1, "course": "PSAD 304", "substitutions": "" }, 
    { "program_id": 32, "course_type_id": 1, "course": "PSAD 306", "substitutions": "" }, 
    { "program_id": 32, "course_type_id": 1, "course": "PSAD 408", "substitutions": "" }, 
    { "program_id": 32, "course_type_id": 1, "course": "PSAD 410", "substitutions": "" }, 
    { "program_id": 32, "course_type_id": 1, "course": "PSAD 414", "substitutions": "" }, 
    { "program_id": 32, "course_type_id": 1, "course": "PSAD 416", "substitutions": "" }, 
    { "program_id": 32, "course_type_id": 1, "course": "FINC 331", "substitutions": "" }, 
    { "program_id": 32, "course_type_id": 1, "course": "BMGT 317", "substitutions": "" }, 
    { "program_id": 32, "course_type_id": 1, "course": "PSAD 495", "substitutions": "" }, 
    { "program_id": 32, "course_type_id": 6, "course": "IFSM 300", "substitutions": "" },
    { "program_id": 34, "course_type_id": 1, "course": "CMSC 115", "substitutions": "" },
    { "program_id": 34, "course_type_id": 1, "course": "CMSC 215", "substitutions": "" },
    { "program_id": 34, "course_type_id": 1, "course": "CMSC 320", "substitutions": "" },
    { "program_id": 34, "course_type_id": 1, "course": "SDEV 300", "substitutions": "" },
    { "program_id": 34, "course_type_id": 1, "course": "SDEV 325", "substitutions": "" },
    { "program_id": 34, "course_type_id": 1, "course": "SDEV 350", "substitutions": "" },
    { "program_id": 34, "course_type_id": 1, "course": "SDEV 360", "substitutions": "" },
    { "program_id": 34, "course_type_id": 1, "course": "SDEV 400", "substitutions": "" },
    { "program_id": 34, "course_type_id": 1, "course": "SDEV 425", "substitutions": "" },
    { "program_id": 34, "course_type_id": 1, "course": "SDEV 460", "substitutions": "" },
    { "program_id": 34, "course_type_id": 1, "course": "CMSC 495", "substitutions": "" }
]

drop_table('program_requirement_courses',c)
c.execute('''
    CREATE TABLE program_requirement_courses (
        id INTEGER PRIMARY KEY,
        program_id INTEGER,
        course_type_id INTEGER,
        course TEXT,
        substitutions TEXT,
        FOREIGN KEY(program_id) REFERENCES programs(id),
        FOREIGN KEY(course_type_id) REFERENCES course_type(id)
    )
''')

c.executemany('''
    INSERT INTO program_requirement_courses (program_id, course_type_id, course, substitutions) 
       VALUES (:program_id, :course_type_id, :course, :substitutions)
''', program_requirement_courses)
conn.commit()

# Close the connection
conn.close()
