import sqlite3
# db connection created w/in utils
from utils import conn, c, drop_table, drop_view, column_exists

################################################################
# Programs Table

programs = [
    { "id":   1, "degree_id":  1, "name": "General Studies" },
    { "id":   2, "degree_id":  3, "name": "Accounting" },
    { "id":   3, "degree_id":  3, "name": "Applied Technology" },
    { "id":   4, "degree_id":  3, "name": "Biotechnology" },
    { "id":   5, "degree_id":  3, "name": "Business Administration" },
    { "id":   6, "degree_id":  2, "name": "Communication Studies" },
    { "id":   7, "degree_id":  3, "name": "Computer Science" },
    { "id":   8, "degree_id":  3, "name": "Criminal Justice" },
    { "id":   9, "degree_id":  3, "name": "Cybersecurity Management and Policy" },
    { "id":  10, "degree_id":  3, "name": "Cybersecurity Technology" },
    { "id":  11, "degree_id":  3, "name": "Data Science" },
    { "id":  12, "degree_id":  2, "name": "East Asian Studies" },
    { "id":  13, "degree_id":  2, "name": "English" },
    { "id":  14, "degree_id":  3, "name": "Environmental Health and Safety" },
    { "id":  15, "degree_id":  3, "name": "Finance" },
    { "id":  16, "degree_id":  3, "name": "General Studies" },
    { "id":  17, "degree_id":  3, "name": "Gerontology and Aging Services" },
    { "id":  18, "degree_id":  2, "name": "Graphic Communication" },
    { "id":  19, "degree_id":  3, "name": "Health Services Management" },
    { "id":  20, "degree_id":  2, "name": "History" },
    { "id":  21, "degree_id":  3, "name": "Homeland Security" },
    { "id":  22, "degree_id":  3, "name": "Human Resource Management" },
    { "id":  23, "degree_id":  2, "name": "Humanities" },
    { "id":  24, "degree_id":  3, "name": "Laboratory Management" },
    { "id":  25, "degree_id":  3, "name": "Legal Studies" },
    { "id":  26, "degree_id":  3, "name": "Management Information Systems" },
    { "id":  27, "degree_id":  3, "name": "Management Studies" },
    { "id":  28, "degree_id":  3, "name": "Marketing" },
    { "id":  29, "degree_id":  4, "name": "Nursing for Registered Nurses" },
    { "id":  30, "degree_id":  3, "name": "Political Science" },
    { "id":  31, "degree_id":  3, "name": "Psychology" },
    { "id":  32, "degree_id":  3, "name": "Public Safety Administration" },
    { "id":  33, "degree_id":  3, "name": "Social Science" },
    { "id":  34, "degree_id":  3, "name": "Software Development and Security" },
    { "id":  35, "degree_id":  3, "name": "Web and Digital Design" },
    { "id":  36, "degree_id":  5, "name": "Accounting" },
    { "id":  37, "degree_id":  5, "name": "African American Studies" },
    { "id":  38, "degree_id":  5, "name": "Art" },
    { "id":  39, "degree_id":  5, "name": "Art History" },
    { "id":  40, "degree_id":  5, "name": "Biology" },
    { "id":  41, "degree_id":  5, "name": "Business Administration" },
    { "id":  42, "degree_id":  5, "name": "Communication Studies" },
    { "id":  43, "degree_id":  5, "name": "Computer Science" },
    { "id":  44, "degree_id":  5, "name": "Criminal Justice" },
    { "id":  45, "degree_id":  5, "name": "Cybersecurity" },
    { "id":  46, "degree_id":  5, "name": "Data Science" },
    { "id":  47, "degree_id":  5, "name": "Diversity Awareness" },
    { "id":  48, "degree_id":  5, "name": "East Asian Studies" },
    { "id":  49, "degree_id":  5, "name": "Economics" },
    { "id":  50, "degree_id":  5, "name": "Emergency Management" },
    { "id":  51, "degree_id":  5, "name": "English" },
    { "id":  52, "degree_id":  5, "name": "Environmental Health and Safety" },
    { "id":  53, "degree_id":  5, "name": "Finance" },
    { "id":  54, "degree_id":  5, "name": "Fire Service Administration" },
    { "id":  55, "degree_id":  5, "name": "Forensics" },
    { "id":  56, "degree_id":  5, "name": "Gerontology and Aging Services" },
    { "id":  57, "degree_id":  5, "name": "Health Services Management" },
    { "id":  58, "degree_id":  5, "name": "History" },
    { "id":  59, "degree_id":  5, "name": "Homeland Security" },
    { "id":  60, "degree_id":  5, "name": "Human Resource Management" },
    { "id":  61, "degree_id":  5, "name": "Law for Business" },
    { "id":  62, "degree_id":  5, "name": "Management Information Systems" },
    { "id":  63, "degree_id":  5, "name": "Marketing" },
    { "id":  64, "degree_id":  5, "name": "Mathematical Sciences" },
    { "id":  65, "degree_id":  5, "name": "Natural Science" },
    { "id":  66, "degree_id":  5, "name": "Personal Financial Planning" },
    { "id":  67, "degree_id":  5, "name": "Philosophy" },
    { "id":  68, "degree_id":  5, "name": "Political Science" },
    { "id":  69, "degree_id":  5, "name": "Psychology" },
    { "id":  70, "degree_id":  5, "name": "Public Safety Administration" },
    { "id":  71, "degree_id":  5, "name": "Small Business Management and Entrepreneurship" },
    { "id":  72, "degree_id":  5, "name": "Sociology" },
    { "id":  73, "degree_id":  5, "name": "Speech Communication" },
    { "id":  74, "degree_id":  5, "name": "Terrorism and Critical Infrastructure" },
    { "id":  75, "degree_id":  5, "name": "Web and Digital Design" },
    { "id":  76, "degree_id":  5, "name": "Women, Gender, and Sexuality Studies" },
    { "id":  77, "degree_id": 11, "name": "Accounting and Financial Management" },
    { "id":  78, "degree_id": 11, "name": "Acquisition and Contract Management" },
    { "id":  79, "degree_id": 11, "name": "Biotechnology: Bioinformatics" },
    { "id":  80, "degree_id": 11, "name": "Biotechnology: Biosecurity and Biodefense" },
    { "id":  81, "degree_id": 11, "name": "Biotechnology: Biotechnology Management" },
    { "id":  82, "degree_id": 11, "name": "Biotechnology: Biotechnology Regulatory Affairs" },
    { "id":  83, "degree_id":  8, "name": "Business Administration" },
    { "id":  84, "degree_id": 11, "name": "Cloud Computing Systems" },
    { "id":  85, "degree_id": 11, "name": "CyberAccounting" },
    { "id":  86, "degree_id": 11, "name": "Cyber Operations" },
    { "id":  87, "degree_id": 11, "name": "Cybersecurity Management and Policy" },
    { "id":  88, "degree_id": 11, "name": "Cybersecurity Technology" },
    { "id":  89, "degree_id": 11, "name": "Data Analytics" },
    { "id":  90, "degree_id": 11, "name": "Digital Forensics and Cyber Investigation" },
    { "id":  91, "degree_id":  9, "name": "Distance Education and E-Learning" },
    { "id":  92, "degree_id": 11, "name": "Environmental Management" },
    { "id":  93, "degree_id": 11, "name": "Healthcare Administration" },
    { "id":  94, "degree_id": 11, "name": "Health Information Management and Technology" },
    { "id":  95, "degree_id": 11, "name": "Information Technology: Database Systems Technology" },
    { "id":  96, "degree_id": 11, "name": "Information Technology: Homeland Security Management" },
    { "id":  97, "degree_id": 11, "name": "Information Technology: Informatics" },
    { "id":  98, "degree_id": 11, "name": "Information Technology: Information Assurance" },
    { "id":  99, "degree_id": 11, "name": "Information Technology: Project Management" },
    { "id": 100, "degree_id": 11, "name": "Information Technology: Software Engineering" },
    { "id": 101, "degree_id": 11, "name": "Information Technology: Systems Engineering" },
    { "id": 102, "degree_id": 10, "name": "Instructional Technology" },
    { "id": 103, "degree_id": 11, "name": "Learning Design and Technology" },
    { "id": 104, "degree_id": 11, "name": "Management: Accounting" },
    { "id": 105, "degree_id": 11, "name": "Management: Criminal Justice Management" },
    { "id": 106, "degree_id": 11, "name": "Management: Emergency Management" },
    { "id": 107, "degree_id": 11, "name": "Management: Financial Management" },
    { "id": 108, "degree_id": 11, "name": "Management: Homeland Security Management" },
    { "id": 109, "degree_id": 11, "name": "Management: Human Resource Management" },
    { "id": 110, "degree_id": 11, "name": "Management: Information Systems and Services" },
    { "id": 111, "degree_id": 11, "name": "Management: Intelligence Management" },
    { "id": 112, "degree_id": 11, "name": "Management: Interdisciplinary Studies in Management" },
    { "id": 113, "degree_id": 11, "name": "Management: Marketing" },
    { "id": 114, "degree_id": 11, "name": "Management: Nonprofit and Association Management" },
    { "id": 115, "degree_id": 11, "name": "Management: Project Management" },
    { "id": 116, "degree_id": 11, "name": "Strategic Communications" },
    { "id": 117, "degree_id":  7, "name": "Teaching" },
    { "id": 118, "degree_id": 11, "name": "Transformational Leadership" },
    { "id": 119, "degree_id": 12, "name": "Business Administration" },
    { "id": 120, "degree_id": 13, "name": "Management: Community College Policy and Administration" },
    { "id": 121, "degree_id": 14, "name": "Accounting Foundations" },
    { "id": 122, "degree_id": 14, "name": "Advanced Management" },
    { "id": 123, "degree_id": 14, "name": "American Government and Political Processes" },
    { "id": 124, "degree_id": 14, "name": "Applied Social Sciences" },
    { "id": 125, "degree_id": 14, "name": "Augmented and Virtual Reality Design" },
    { "id": 126, "degree_id": 14, "name": "Clinical Mental Health Care" },
    { "id": 127, "degree_id": 14, "name": "Computer Networking" },
    { "id": 128, "degree_id": 14, "name": "Cyber Threat Hunting" },
    { "id": 129, "degree_id": 14, "name": "Data Analytics" },
    { "id": 130, "degree_id": 14, "name": "Decision Support for Business" },
    { "id": 131, "degree_id": 14, "name": "Digital Design" },
    { "id": 132, "degree_id": 14, "name": "Digital Marketing" },
    { "id": 133, "degree_id": 14, "name": "Health Information Management and Data Analytics" },
    { "id": 134, "degree_id": 14, "name": "HR People Analytics" },
    { "id": 135, "degree_id": 14, "name": "Human Resource Management" },
    { "id": 136, "degree_id": 14, "name": "Leadership and Ethics" },
    { "id": 137, "degree_id": 14, "name": "Machine Learning" },
    { "id": 138, "degree_id": 14, "name": "Management" },
    { "id": 139, "degree_id": 14, "name": "Management Information Systems" },
    { "id": 140, "degree_id": 14, "name": "Project Management" },
    { "id": 141, "degree_id": 14, "name": "Public Safety Executive Leadership" },
    { "id": 142, "degree_id": 14, "name": "Spanish for Business and the Professions" },
    { "id": 143, "degree_id": 14, "name": "Vulnerability Assessment" },
    { "id": 144, "degree_id": 14, "name": "Watershed Management" },
    { "id": 145, "degree_id": 14, "name": "Web Design" },
    { "id": 146, "degree_id": 14, "name": "Women, Gender, and Sexuality Studies" },
    { "id": 147, "degree_id": 15, "name": "Accounting Information Security" },
    { "id": 148, "degree_id": 15, "name": "Acquisition and Contract Management" },
    { "id": 149, "degree_id": 15, "name": "Bioinformatics" },
    { "id": 150, "degree_id": 15, "name": "Business Analytics" },
    { "id": 151, "degree_id": 15, "name": "Cloud Computing and Networking" },
    { "id": 152, "degree_id": 15, "name": "Cyber Operations" },
    { "id": 153, "degree_id": 15, "name": "Cybersecurity Management and Policy" },
    { "id": 154, "degree_id": 15, "name": "Cybersecurity Technology" },
    { "id": 155, "degree_id": 15, "name": "Digital Forensics and Cyber Investigation" },
    { "id": 156, "degree_id": 15, "name": "Digital Health Leader" },
    { "id": 157, "degree_id": 15, "name": "Global Health Management" },
    { "id": 158, "degree_id": 15, "name": "Homeland Security Management" },
    { "id": 159, "degree_id": 15, "name": "Informatics" },
    { "id": 160, "degree_id": 15, "name": "Information Assurance" },
    { "id": 161, "degree_id": 15, "name": "Instructional Technology Integration" },
    { "id": 162, "degree_id": 15, "name": "Leadership and Management" },
    { "id": 163, "degree_id": 15, "name": "Learning Design and Technology" },
    { "id": 164, "degree_id": 15, "name": "Long-Term Care Administration" },
    { "id": 165, "degree_id": 15, "name": "Multicultural Marketing" },
    { "id": 166, "degree_id": 15, "name": "Project Management" },
    { "id": 167, "degree_id": 15, "name": "Strategic Communications" },
    { "id": 168, "degree_id": 15, "name": "Strategic Human Resource Management" },
    { "id": 169, "degree_id": 15, "name": "Systems Engineering" }
]

drop_table('programs',c)
c.execute('''
    CREATE TABLE programs (
        id INTEGER PRIMARY KEY,
        name TEXT,
        degree_id INTEGER
    )
''')

c.executemany('INSERT INTO programs VALUES (:id, :name, :degree_id)', programs)

# Update programs to contain catalog version
c.execute('ALTER TABLE programs ADD catalog_id INTEGER')
c.execute('UPDATE programs SET catalog_id = 1')

conn.commit()

# Close the connection
conn.close()